// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/metrics/catalog.proto

#include "proto/metrics/catalog.pb.h"
#include "proto/metrics/catalog.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace rl {
namespace training {
namespace v1 {

static const char* MetricCatalogService_method_names[] = {
  "/rl.training.v1.MetricCatalogService/GetMetricCatalog",
};

std::unique_ptr< MetricCatalogService::Stub> MetricCatalogService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MetricCatalogService::Stub> stub(new MetricCatalogService::Stub(channel, options));
  return stub;
}

MetricCatalogService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetMetricCatalog_(MetricCatalogService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MetricCatalogService::Stub::GetMetricCatalog(::grpc::ClientContext* context, const ::rl::training::v1::GetMetricCatalogReq& request, ::rl::training::v1::GetMetricCatalogRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rl::training::v1::GetMetricCatalogReq, ::rl::training::v1::GetMetricCatalogRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetMetricCatalog_, context, request, response);
}

void MetricCatalogService::Stub::async::GetMetricCatalog(::grpc::ClientContext* context, const ::rl::training::v1::GetMetricCatalogReq* request, ::rl::training::v1::GetMetricCatalogRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rl::training::v1::GetMetricCatalogReq, ::rl::training::v1::GetMetricCatalogRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMetricCatalog_, context, request, response, std::move(f));
}

void MetricCatalogService::Stub::async::GetMetricCatalog(::grpc::ClientContext* context, const ::rl::training::v1::GetMetricCatalogReq* request, ::rl::training::v1::GetMetricCatalogRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMetricCatalog_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::GetMetricCatalogRsp>* MetricCatalogService::Stub::PrepareAsyncGetMetricCatalogRaw(::grpc::ClientContext* context, const ::rl::training::v1::GetMetricCatalogReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rl::training::v1::GetMetricCatalogRsp, ::rl::training::v1::GetMetricCatalogReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetMetricCatalog_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::GetMetricCatalogRsp>* MetricCatalogService::Stub::AsyncGetMetricCatalogRaw(::grpc::ClientContext* context, const ::rl::training::v1::GetMetricCatalogReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetMetricCatalogRaw(context, request, cq);
  result->StartCall();
  return result;
}

MetricCatalogService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MetricCatalogService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MetricCatalogService::Service, ::rl::training::v1::GetMetricCatalogReq, ::rl::training::v1::GetMetricCatalogRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MetricCatalogService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rl::training::v1::GetMetricCatalogReq* req,
             ::rl::training::v1::GetMetricCatalogRsp* resp) {
               return service->GetMetricCatalog(ctx, req, resp);
             }, this)));
}

MetricCatalogService::Service::~Service() {
}

::grpc::Status MetricCatalogService::Service::GetMetricCatalog(::grpc::ServerContext* context, const ::rl::training::v1::GetMetricCatalogReq* request, ::rl::training::v1::GetMetricCatalogRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace rl
}  // namespace training
}  // namespace v1

