// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/metrics/catalog.proto
#ifndef GRPC_proto_2fmetrics_2fcatalog_2eproto__INCLUDED
#define GRPC_proto_2fmetrics_2fcatalog_2eproto__INCLUDED

#include "proto/metrics/catalog.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace rl {
namespace training {
namespace v1 {

class MetricCatalogService final {
 public:
  static constexpr char const* service_full_name() {
    return "rl.training.v1.MetricCatalogService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetMetricCatalog(::grpc::ClientContext* context, const ::rl::training::v1::GetMetricCatalogReq& request, ::rl::training::v1::GetMetricCatalogRsp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rl::training::v1::GetMetricCatalogRsp>> AsyncGetMetricCatalog(::grpc::ClientContext* context, const ::rl::training::v1::GetMetricCatalogReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rl::training::v1::GetMetricCatalogRsp>>(AsyncGetMetricCatalogRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rl::training::v1::GetMetricCatalogRsp>> PrepareAsyncGetMetricCatalog(::grpc::ClientContext* context, const ::rl::training::v1::GetMetricCatalogReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rl::training::v1::GetMetricCatalogRsp>>(PrepareAsyncGetMetricCatalogRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetMetricCatalog(::grpc::ClientContext* context, const ::rl::training::v1::GetMetricCatalogReq* request, ::rl::training::v1::GetMetricCatalogRsp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetMetricCatalog(::grpc::ClientContext* context, const ::rl::training::v1::GetMetricCatalogReq* request, ::rl::training::v1::GetMetricCatalogRsp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rl::training::v1::GetMetricCatalogRsp>* AsyncGetMetricCatalogRaw(::grpc::ClientContext* context, const ::rl::training::v1::GetMetricCatalogReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rl::training::v1::GetMetricCatalogRsp>* PrepareAsyncGetMetricCatalogRaw(::grpc::ClientContext* context, const ::rl::training::v1::GetMetricCatalogReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetMetricCatalog(::grpc::ClientContext* context, const ::rl::training::v1::GetMetricCatalogReq& request, ::rl::training::v1::GetMetricCatalogRsp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rl::training::v1::GetMetricCatalogRsp>> AsyncGetMetricCatalog(::grpc::ClientContext* context, const ::rl::training::v1::GetMetricCatalogReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rl::training::v1::GetMetricCatalogRsp>>(AsyncGetMetricCatalogRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rl::training::v1::GetMetricCatalogRsp>> PrepareAsyncGetMetricCatalog(::grpc::ClientContext* context, const ::rl::training::v1::GetMetricCatalogReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rl::training::v1::GetMetricCatalogRsp>>(PrepareAsyncGetMetricCatalogRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetMetricCatalog(::grpc::ClientContext* context, const ::rl::training::v1::GetMetricCatalogReq* request, ::rl::training::v1::GetMetricCatalogRsp* response, std::function<void(::grpc::Status)>) override;
      void GetMetricCatalog(::grpc::ClientContext* context, const ::rl::training::v1::GetMetricCatalogReq* request, ::rl::training::v1::GetMetricCatalogRsp* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::rl::training::v1::GetMetricCatalogRsp>* AsyncGetMetricCatalogRaw(::grpc::ClientContext* context, const ::rl::training::v1::GetMetricCatalogReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rl::training::v1::GetMetricCatalogRsp>* PrepareAsyncGetMetricCatalogRaw(::grpc::ClientContext* context, const ::rl::training::v1::GetMetricCatalogReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetMetricCatalog_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetMetricCatalog(::grpc::ServerContext* context, const ::rl::training::v1::GetMetricCatalogReq* request, ::rl::training::v1::GetMetricCatalogRsp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetMetricCatalog : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetMetricCatalog() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetMetricCatalog() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMetricCatalog(::grpc::ServerContext* /*context*/, const ::rl::training::v1::GetMetricCatalogReq* /*request*/, ::rl::training::v1::GetMetricCatalogRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetMetricCatalog(::grpc::ServerContext* context, ::rl::training::v1::GetMetricCatalogReq* request, ::grpc::ServerAsyncResponseWriter< ::rl::training::v1::GetMetricCatalogRsp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetMetricCatalog<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetMetricCatalog : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetMetricCatalog() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::rl::training::v1::GetMetricCatalogReq, ::rl::training::v1::GetMetricCatalogRsp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rl::training::v1::GetMetricCatalogReq* request, ::rl::training::v1::GetMetricCatalogRsp* response) { return this->GetMetricCatalog(context, request, response); }));}
    void SetMessageAllocatorFor_GetMetricCatalog(
        ::grpc::MessageAllocator< ::rl::training::v1::GetMetricCatalogReq, ::rl::training::v1::GetMetricCatalogRsp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rl::training::v1::GetMetricCatalogReq, ::rl::training::v1::GetMetricCatalogRsp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetMetricCatalog() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMetricCatalog(::grpc::ServerContext* /*context*/, const ::rl::training::v1::GetMetricCatalogReq* /*request*/, ::rl::training::v1::GetMetricCatalogRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetMetricCatalog(
      ::grpc::CallbackServerContext* /*context*/, const ::rl::training::v1::GetMetricCatalogReq* /*request*/, ::rl::training::v1::GetMetricCatalogRsp* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetMetricCatalog<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetMetricCatalog : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetMetricCatalog() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetMetricCatalog() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMetricCatalog(::grpc::ServerContext* /*context*/, const ::rl::training::v1::GetMetricCatalogReq* /*request*/, ::rl::training::v1::GetMetricCatalogRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetMetricCatalog : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetMetricCatalog() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetMetricCatalog() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMetricCatalog(::grpc::ServerContext* /*context*/, const ::rl::training::v1::GetMetricCatalogReq* /*request*/, ::rl::training::v1::GetMetricCatalogRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetMetricCatalog(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetMetricCatalog : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetMetricCatalog() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetMetricCatalog(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetMetricCatalog() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMetricCatalog(::grpc::ServerContext* /*context*/, const ::rl::training::v1::GetMetricCatalogReq* /*request*/, ::rl::training::v1::GetMetricCatalogRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetMetricCatalog(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetMetricCatalog : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetMetricCatalog() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rl::training::v1::GetMetricCatalogReq, ::rl::training::v1::GetMetricCatalogRsp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rl::training::v1::GetMetricCatalogReq, ::rl::training::v1::GetMetricCatalogRsp>* streamer) {
                       return this->StreamedGetMetricCatalog(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetMetricCatalog() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetMetricCatalog(::grpc::ServerContext* /*context*/, const ::rl::training::v1::GetMetricCatalogReq* /*request*/, ::rl::training::v1::GetMetricCatalogRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetMetricCatalog(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rl::training::v1::GetMetricCatalogReq,::rl::training::v1::GetMetricCatalogRsp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetMetricCatalog<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetMetricCatalog<Service > StreamedService;
};

}  // namespace v1
}  // namespace training
}  // namespace rl


#endif  // GRPC_proto_2fmetrics_2fcatalog_2eproto__INCLUDED
