// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/metrics/registry.proto

#include "proto/metrics/registry.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace rl {
namespace training {
namespace v1 {
PROTOBUF_CONSTEXPR RawMetricSumCount::RawMetricSumCount(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.field_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.sum_)*/0
  , /*decltype(_impl_.count_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RawMetricSumCountDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RawMetricSumCountDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RawMetricSumCountDefaultTypeInternal() {}
  union {
    RawMetricSumCount _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RawMetricSumCountDefaultTypeInternal _RawMetricSumCount_default_instance_;
PROTOBUF_CONSTEXPR MetricDefinition::MetricDefinition(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.metric_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.display_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.unit_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.scope_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.denominator_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.category_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.description_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.value_type_)*/0
  , /*decltype(_impl_.aggregation_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MetricDefinitionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MetricDefinitionDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MetricDefinitionDefaultTypeInternal() {}
  union {
    MetricDefinition _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MetricDefinitionDefaultTypeInternal _MetricDefinition_default_instance_;
PROTOBUF_CONSTEXPR MetricSumCount::MetricSumCount(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.sum_)*/0
  , /*decltype(_impl_.count_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MetricSumCountDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MetricSumCountDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MetricSumCountDefaultTypeInternal() {}
  union {
    MetricSumCount _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MetricSumCountDefaultTypeInternal _MetricSumCount_default_instance_;
PROTOBUF_CONSTEXPR MetricPoint_AttributesEntry_DoNotUse::MetricPoint_AttributesEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct MetricPoint_AttributesEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MetricPoint_AttributesEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MetricPoint_AttributesEntry_DoNotUseDefaultTypeInternal() {}
  union {
    MetricPoint_AttributesEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MetricPoint_AttributesEntry_DoNotUseDefaultTypeInternal _MetricPoint_AttributesEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR MetricPoint::MetricPoint(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.attributes_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_.metric_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.interval_start_unix_ms_)*/int64_t{0}
  , /*decltype(_impl_.interval_end_unix_ms_)*/int64_t{0}
  , /*decltype(_impl_.value_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct MetricPointDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MetricPointDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MetricPointDefaultTypeInternal() {}
  union {
    MetricPoint _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MetricPointDefaultTypeInternal _MetricPoint_default_instance_;
PROTOBUF_CONSTEXPR RegisteredMetricRecord_AttributesEntry_DoNotUse::RegisteredMetricRecord_AttributesEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct RegisteredMetricRecord_AttributesEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RegisteredMetricRecord_AttributesEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RegisteredMetricRecord_AttributesEntry_DoNotUseDefaultTypeInternal() {}
  union {
    RegisteredMetricRecord_AttributesEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RegisteredMetricRecord_AttributesEntry_DoNotUseDefaultTypeInternal _RegisteredMetricRecord_AttributesEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR RegisteredMetricRecord::RegisteredMetricRecord(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.definitions_)*/{}
  , /*decltype(_impl_.points_)*/{}
  , /*decltype(_impl_.attributes_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RegisteredMetricRecordDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RegisteredMetricRecordDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RegisteredMetricRecordDefaultTypeInternal() {}
  union {
    RegisteredMetricRecord _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RegisteredMetricRecordDefaultTypeInternal _RegisteredMetricRecord_default_instance_;
}  // namespace v1
}  // namespace training
}  // namespace rl
static ::_pb::Metadata file_level_metadata_proto_2fmetrics_2fregistry_2eproto[7];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_proto_2fmetrics_2fregistry_2eproto[2];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_proto_2fmetrics_2fregistry_2eproto = nullptr;

const uint32_t TableStruct_proto_2fmetrics_2fregistry_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::RawMetricSumCount, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::RawMetricSumCount, _impl_.field_id_),
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::RawMetricSumCount, _impl_.sum_),
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::RawMetricSumCount, _impl_.count_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::MetricDefinition, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::MetricDefinition, _impl_.metric_id_),
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::MetricDefinition, _impl_.display_name_),
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::MetricDefinition, _impl_.unit_),
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::MetricDefinition, _impl_.scope_),
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::MetricDefinition, _impl_.value_type_),
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::MetricDefinition, _impl_.aggregation_),
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::MetricDefinition, _impl_.denominator_),
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::MetricDefinition, _impl_.category_),
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::MetricDefinition, _impl_.description_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::MetricSumCount, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::MetricSumCount, _impl_.sum_),
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::MetricSumCount, _impl_.count_),
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::MetricPoint_AttributesEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::MetricPoint_AttributesEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::MetricPoint_AttributesEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::MetricPoint_AttributesEntry_DoNotUse, value_),
  0,
  1,
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::MetricPoint, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::MetricPoint, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::MetricPoint, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::MetricPoint, _impl_.metric_id_),
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::MetricPoint, _impl_.attributes_),
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::MetricPoint, _impl_.interval_start_unix_ms_),
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::MetricPoint, _impl_.interval_end_unix_ms_),
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::MetricPoint, _impl_.value_),
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  0,
  1,
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::RegisteredMetricRecord_AttributesEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::RegisteredMetricRecord_AttributesEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::RegisteredMetricRecord_AttributesEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::RegisteredMetricRecord_AttributesEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::RegisteredMetricRecord, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::RegisteredMetricRecord, _impl_.definitions_),
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::RegisteredMetricRecord, _impl_.points_),
  PROTOBUF_FIELD_OFFSET(::rl::training::v1::RegisteredMetricRecord, _impl_.attributes_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::rl::training::v1::RawMetricSumCount)},
  { 9, -1, -1, sizeof(::rl::training::v1::MetricDefinition)},
  { 24, -1, -1, sizeof(::rl::training::v1::MetricSumCount)},
  { 32, 40, -1, sizeof(::rl::training::v1::MetricPoint_AttributesEntry_DoNotUse)},
  { 42, 56, -1, sizeof(::rl::training::v1::MetricPoint)},
  { 63, 71, -1, sizeof(::rl::training::v1::RegisteredMetricRecord_AttributesEntry_DoNotUse)},
  { 73, -1, -1, sizeof(::rl::training::v1::RegisteredMetricRecord)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::rl::training::v1::_RawMetricSumCount_default_instance_._instance,
  &::rl::training::v1::_MetricDefinition_default_instance_._instance,
  &::rl::training::v1::_MetricSumCount_default_instance_._instance,
  &::rl::training::v1::_MetricPoint_AttributesEntry_DoNotUse_default_instance_._instance,
  &::rl::training::v1::_MetricPoint_default_instance_._instance,
  &::rl::training::v1::_RegisteredMetricRecord_AttributesEntry_DoNotUse_default_instance_._instance,
  &::rl::training::v1::_RegisteredMetricRecord_default_instance_._instance,
};

const char descriptor_table_protodef_proto_2fmetrics_2fregistry_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\034proto/metrics/registry.proto\022\016rl.train"
  "ing.v1\"A\n\021RawMetricSumCount\022\020\n\010field_id\030"
  "\001 \001(\t\022\013\n\003sum\030\002 \001(\001\022\r\n\005count\030\003 \001(\004\"\201\002\n\020Me"
  "tricDefinition\022\021\n\tmetric_id\030\001 \001(\t\022\024\n\014dis"
  "play_name\030\002 \001(\t\022\014\n\004unit\030\003 \001(\t\022\r\n\005scope\030\004"
  " \001(\t\0223\n\nvalue_type\030\005 \001(\0162\037.rl.training.v"
  "1.MetricValueType\0226\n\013aggregation\030\006 \001(\0162!"
  ".rl.training.v1.MetricAggregation\022\023\n\013den"
  "ominator\030\007 \001(\t\022\020\n\010category\030\010 \001(\t\022\023\n\013desc"
  "ription\030\t \001(\t\",\n\016MetricSumCount\022\013\n\003sum\030\001"
  " \001(\001\022\r\n\005count\030\002 \001(\004\"\372\002\n\013MetricPoint\022\021\n\tm"
  "etric_id\030\001 \001(\t\022\020\n\006scalar\030\002 \001(\001H\000\022\030\n\016unsi"
  "gned_value\030\003 \001(\004H\000\0223\n\tsum_count\030\004 \001(\0132\036."
  "rl.training.v1.MetricSumCountH\000\022\?\n\nattri"
  "butes\030\005 \003(\0132+.rl.training.v1.MetricPoint"
  ".AttributesEntry\022#\n\026interval_start_unix_"
  "ms\030\006 \001(\003H\001\210\001\001\022!\n\024interval_end_unix_ms\030\007 "
  "\001(\003H\002\210\001\001\0321\n\017AttributesEntry\022\013\n\003key\030\001 \001(\t"
  "\022\r\n\005value\030\002 \001(\t:\0028\001B\007\n\005valueB\031\n\027_interva"
  "l_start_unix_msB\027\n\025_interval_end_unix_ms"
  "\"\373\001\n\026RegisteredMetricRecord\0225\n\013definitio"
  "ns\030\001 \003(\0132 .rl.training.v1.MetricDefiniti"
  "on\022+\n\006points\030\002 \003(\0132\033.rl.training.v1.Metr"
  "icPoint\022J\n\nattributes\030\003 \003(\01326.rl.trainin"
  "g.v1.RegisteredMetricRecord.AttributesEn"
  "try\0321\n\017AttributesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005v"
  "alue\030\002 \001(\t:\0028\001*\223\001\n\017MetricValueType\022!\n\035ME"
  "TRIC_VALUE_TYPE_UNSPECIFIED\020\000\022\034\n\030METRIC_"
  "VALUE_TYPE_SCALAR\020\001\022\036\n\032METRIC_VALUE_TYPE"
  "_UNSIGNED\020\002\022\037\n\033METRIC_VALUE_TYPE_SUM_COU"
  "NT\020\003*\307\001\n\021MetricAggregation\022\"\n\036METRIC_AGG"
  "REGATION_UNSPECIFIED\020\000\022\035\n\031METRIC_AGGREGA"
  "TION_LATEST\020\001\022\032\n\026METRIC_AGGREGATION_SUM\020"
  "\002\022\032\n\026METRIC_AGGREGATION_MIN\020\003\022\032\n\026METRIC_"
  "AGGREGATION_MAX\020\004\022\033\n\027METRIC_AGGREGATION_"
  "MEAN\020\005B\003\200\001\000b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_proto_2fmetrics_2fregistry_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_proto_2fmetrics_2fregistry_2eproto = {
    false, false, 1419, descriptor_table_protodef_proto_2fmetrics_2fregistry_2eproto,
    "proto/metrics/registry.proto",
    &descriptor_table_proto_2fmetrics_2fregistry_2eproto_once, nullptr, 0, 7,
    schemas, file_default_instances, TableStruct_proto_2fmetrics_2fregistry_2eproto::offsets,
    file_level_metadata_proto_2fmetrics_2fregistry_2eproto, file_level_enum_descriptors_proto_2fmetrics_2fregistry_2eproto,
    file_level_service_descriptors_proto_2fmetrics_2fregistry_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_proto_2fmetrics_2fregistry_2eproto_getter() {
  return &descriptor_table_proto_2fmetrics_2fregistry_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_proto_2fmetrics_2fregistry_2eproto(&descriptor_table_proto_2fmetrics_2fregistry_2eproto);
namespace rl {
namespace training {
namespace v1 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MetricValueType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_proto_2fmetrics_2fregistry_2eproto);
  return file_level_enum_descriptors_proto_2fmetrics_2fregistry_2eproto[0];
}
bool MetricValueType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MetricAggregation_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_proto_2fmetrics_2fregistry_2eproto);
  return file_level_enum_descriptors_proto_2fmetrics_2fregistry_2eproto[1];
}
bool MetricAggregation_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class RawMetricSumCount::_Internal {
 public:
};

RawMetricSumCount::RawMetricSumCount(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:rl.training.v1.RawMetricSumCount)
}
RawMetricSumCount::RawMetricSumCount(const RawMetricSumCount& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RawMetricSumCount* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.field_id_){}
    , decltype(_impl_.sum_){}
    , decltype(_impl_.count_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.field_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.field_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_field_id().empty()) {
    _this->_impl_.field_id_.Set(from._internal_field_id(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.sum_, &from._impl_.sum_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.count_) -
    reinterpret_cast<char*>(&_impl_.sum_)) + sizeof(_impl_.count_));
  // @@protoc_insertion_point(copy_constructor:rl.training.v1.RawMetricSumCount)
}

inline void RawMetricSumCount::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.field_id_){}
    , decltype(_impl_.sum_){0}
    , decltype(_impl_.count_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.field_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.field_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

RawMetricSumCount::~RawMetricSumCount() {
  // @@protoc_insertion_point(destructor:rl.training.v1.RawMetricSumCount)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RawMetricSumCount::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.field_id_.Destroy();
}

void RawMetricSumCount::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RawMetricSumCount::Clear() {
// @@protoc_insertion_point(message_clear_start:rl.training.v1.RawMetricSumCount)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.field_id_.ClearToEmpty();
  ::memset(&_impl_.sum_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.count_) -
      reinterpret_cast<char*>(&_impl_.sum_)) + sizeof(_impl_.count_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RawMetricSumCount::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string field_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_field_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "rl.training.v1.RawMetricSumCount.field_id"));
        } else
          goto handle_unusual;
        continue;
      // double sum = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _impl_.sum_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // uint64 count = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.count_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RawMetricSumCount::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rl.training.v1.RawMetricSumCount)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string field_id = 1;
  if (!this->_internal_field_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_field_id().data(), static_cast<int>(this->_internal_field_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "rl.training.v1.RawMetricSumCount.field_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_field_id(), target);
  }

  // double sum = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_sum = this->_internal_sum();
  uint64_t raw_sum;
  memcpy(&raw_sum, &tmp_sum, sizeof(tmp_sum));
  if (raw_sum != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_sum(), target);
  }

  // uint64 count = 3;
  if (this->_internal_count() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_count(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rl.training.v1.RawMetricSumCount)
  return target;
}

size_t RawMetricSumCount::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rl.training.v1.RawMetricSumCount)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string field_id = 1;
  if (!this->_internal_field_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_field_id());
  }

  // double sum = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_sum = this->_internal_sum();
  uint64_t raw_sum;
  memcpy(&raw_sum, &tmp_sum, sizeof(tmp_sum));
  if (raw_sum != 0) {
    total_size += 1 + 8;
  }

  // uint64 count = 3;
  if (this->_internal_count() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_count());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RawMetricSumCount::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RawMetricSumCount::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RawMetricSumCount::GetClassData() const { return &_class_data_; }


void RawMetricSumCount::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RawMetricSumCount*>(&to_msg);
  auto& from = static_cast<const RawMetricSumCount&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rl.training.v1.RawMetricSumCount)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_field_id().empty()) {
    _this->_internal_set_field_id(from._internal_field_id());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_sum = from._internal_sum();
  uint64_t raw_sum;
  memcpy(&raw_sum, &tmp_sum, sizeof(tmp_sum));
  if (raw_sum != 0) {
    _this->_internal_set_sum(from._internal_sum());
  }
  if (from._internal_count() != 0) {
    _this->_internal_set_count(from._internal_count());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RawMetricSumCount::CopyFrom(const RawMetricSumCount& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rl.training.v1.RawMetricSumCount)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RawMetricSumCount::IsInitialized() const {
  return true;
}

void RawMetricSumCount::InternalSwap(RawMetricSumCount* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.field_id_, lhs_arena,
      &other->_impl_.field_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RawMetricSumCount, _impl_.count_)
      + sizeof(RawMetricSumCount::_impl_.count_)
      - PROTOBUF_FIELD_OFFSET(RawMetricSumCount, _impl_.sum_)>(
          reinterpret_cast<char*>(&_impl_.sum_),
          reinterpret_cast<char*>(&other->_impl_.sum_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RawMetricSumCount::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fmetrics_2fregistry_2eproto_getter, &descriptor_table_proto_2fmetrics_2fregistry_2eproto_once,
      file_level_metadata_proto_2fmetrics_2fregistry_2eproto[0]);
}

// ===================================================================

class MetricDefinition::_Internal {
 public:
};

MetricDefinition::MetricDefinition(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:rl.training.v1.MetricDefinition)
}
MetricDefinition::MetricDefinition(const MetricDefinition& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MetricDefinition* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.metric_id_){}
    , decltype(_impl_.display_name_){}
    , decltype(_impl_.unit_){}
    , decltype(_impl_.scope_){}
    , decltype(_impl_.denominator_){}
    , decltype(_impl_.category_){}
    , decltype(_impl_.description_){}
    , decltype(_impl_.value_type_){}
    , decltype(_impl_.aggregation_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.metric_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.metric_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_metric_id().empty()) {
    _this->_impl_.metric_id_.Set(from._internal_metric_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.display_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.display_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_display_name().empty()) {
    _this->_impl_.display_name_.Set(from._internal_display_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.unit_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.unit_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_unit().empty()) {
    _this->_impl_.unit_.Set(from._internal_unit(), 
      _this->GetArenaForAllocation());
  }
  _impl_.scope_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.scope_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_scope().empty()) {
    _this->_impl_.scope_.Set(from._internal_scope(), 
      _this->GetArenaForAllocation());
  }
  _impl_.denominator_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.denominator_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_denominator().empty()) {
    _this->_impl_.denominator_.Set(from._internal_denominator(), 
      _this->GetArenaForAllocation());
  }
  _impl_.category_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.category_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_category().empty()) {
    _this->_impl_.category_.Set(from._internal_category(), 
      _this->GetArenaForAllocation());
  }
  _impl_.description_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.description_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_description().empty()) {
    _this->_impl_.description_.Set(from._internal_description(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.value_type_, &from._impl_.value_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.aggregation_) -
    reinterpret_cast<char*>(&_impl_.value_type_)) + sizeof(_impl_.aggregation_));
  // @@protoc_insertion_point(copy_constructor:rl.training.v1.MetricDefinition)
}

inline void MetricDefinition::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.metric_id_){}
    , decltype(_impl_.display_name_){}
    , decltype(_impl_.unit_){}
    , decltype(_impl_.scope_){}
    , decltype(_impl_.denominator_){}
    , decltype(_impl_.category_){}
    , decltype(_impl_.description_){}
    , decltype(_impl_.value_type_){0}
    , decltype(_impl_.aggregation_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.metric_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.metric_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.display_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.display_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.unit_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.unit_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.scope_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.scope_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.denominator_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.denominator_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.category_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.category_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.description_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.description_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

MetricDefinition::~MetricDefinition() {
  // @@protoc_insertion_point(destructor:rl.training.v1.MetricDefinition)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MetricDefinition::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.metric_id_.Destroy();
  _impl_.display_name_.Destroy();
  _impl_.unit_.Destroy();
  _impl_.scope_.Destroy();
  _impl_.denominator_.Destroy();
  _impl_.category_.Destroy();
  _impl_.description_.Destroy();
}

void MetricDefinition::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MetricDefinition::Clear() {
// @@protoc_insertion_point(message_clear_start:rl.training.v1.MetricDefinition)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.metric_id_.ClearToEmpty();
  _impl_.display_name_.ClearToEmpty();
  _impl_.unit_.ClearToEmpty();
  _impl_.scope_.ClearToEmpty();
  _impl_.denominator_.ClearToEmpty();
  _impl_.category_.ClearToEmpty();
  _impl_.description_.ClearToEmpty();
  ::memset(&_impl_.value_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.aggregation_) -
      reinterpret_cast<char*>(&_impl_.value_type_)) + sizeof(_impl_.aggregation_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MetricDefinition::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string metric_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_metric_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "rl.training.v1.MetricDefinition.metric_id"));
        } else
          goto handle_unusual;
        continue;
      // string display_name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_display_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "rl.training.v1.MetricDefinition.display_name"));
        } else
          goto handle_unusual;
        continue;
      // string unit = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_unit();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "rl.training.v1.MetricDefinition.unit"));
        } else
          goto handle_unusual;
        continue;
      // string scope = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_scope();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "rl.training.v1.MetricDefinition.scope"));
        } else
          goto handle_unusual;
        continue;
      // .rl.training.v1.MetricValueType value_type = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_value_type(static_cast<::rl::training::v1::MetricValueType>(val));
        } else
          goto handle_unusual;
        continue;
      // .rl.training.v1.MetricAggregation aggregation = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_aggregation(static_cast<::rl::training::v1::MetricAggregation>(val));
        } else
          goto handle_unusual;
        continue;
      // string denominator = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_denominator();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "rl.training.v1.MetricDefinition.denominator"));
        } else
          goto handle_unusual;
        continue;
      // string category = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          auto str = _internal_mutable_category();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "rl.training.v1.MetricDefinition.category"));
        } else
          goto handle_unusual;
        continue;
      // string description = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          auto str = _internal_mutable_description();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "rl.training.v1.MetricDefinition.description"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MetricDefinition::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rl.training.v1.MetricDefinition)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string metric_id = 1;
  if (!this->_internal_metric_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_metric_id().data(), static_cast<int>(this->_internal_metric_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "rl.training.v1.MetricDefinition.metric_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_metric_id(), target);
  }

  // string display_name = 2;
  if (!this->_internal_display_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_display_name().data(), static_cast<int>(this->_internal_display_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "rl.training.v1.MetricDefinition.display_name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_display_name(), target);
  }

  // string unit = 3;
  if (!this->_internal_unit().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_unit().data(), static_cast<int>(this->_internal_unit().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "rl.training.v1.MetricDefinition.unit");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_unit(), target);
  }

  // string scope = 4;
  if (!this->_internal_scope().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_scope().data(), static_cast<int>(this->_internal_scope().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "rl.training.v1.MetricDefinition.scope");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_scope(), target);
  }

  // .rl.training.v1.MetricValueType value_type = 5;
  if (this->_internal_value_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      5, this->_internal_value_type(), target);
  }

  // .rl.training.v1.MetricAggregation aggregation = 6;
  if (this->_internal_aggregation() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      6, this->_internal_aggregation(), target);
  }

  // string denominator = 7;
  if (!this->_internal_denominator().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_denominator().data(), static_cast<int>(this->_internal_denominator().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "rl.training.v1.MetricDefinition.denominator");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_denominator(), target);
  }

  // string category = 8;
  if (!this->_internal_category().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_category().data(), static_cast<int>(this->_internal_category().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "rl.training.v1.MetricDefinition.category");
    target = stream->WriteStringMaybeAliased(
        8, this->_internal_category(), target);
  }

  // string description = 9;
  if (!this->_internal_description().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_description().data(), static_cast<int>(this->_internal_description().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "rl.training.v1.MetricDefinition.description");
    target = stream->WriteStringMaybeAliased(
        9, this->_internal_description(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rl.training.v1.MetricDefinition)
  return target;
}

size_t MetricDefinition::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rl.training.v1.MetricDefinition)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string metric_id = 1;
  if (!this->_internal_metric_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_metric_id());
  }

  // string display_name = 2;
  if (!this->_internal_display_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_display_name());
  }

  // string unit = 3;
  if (!this->_internal_unit().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_unit());
  }

  // string scope = 4;
  if (!this->_internal_scope().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_scope());
  }

  // string denominator = 7;
  if (!this->_internal_denominator().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_denominator());
  }

  // string category = 8;
  if (!this->_internal_category().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_category());
  }

  // string description = 9;
  if (!this->_internal_description().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_description());
  }

  // .rl.training.v1.MetricValueType value_type = 5;
  if (this->_internal_value_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_value_type());
  }

  // .rl.training.v1.MetricAggregation aggregation = 6;
  if (this->_internal_aggregation() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_aggregation());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MetricDefinition::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MetricDefinition::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MetricDefinition::GetClassData() const { return &_class_data_; }


void MetricDefinition::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MetricDefinition*>(&to_msg);
  auto& from = static_cast<const MetricDefinition&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rl.training.v1.MetricDefinition)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_metric_id().empty()) {
    _this->_internal_set_metric_id(from._internal_metric_id());
  }
  if (!from._internal_display_name().empty()) {
    _this->_internal_set_display_name(from._internal_display_name());
  }
  if (!from._internal_unit().empty()) {
    _this->_internal_set_unit(from._internal_unit());
  }
  if (!from._internal_scope().empty()) {
    _this->_internal_set_scope(from._internal_scope());
  }
  if (!from._internal_denominator().empty()) {
    _this->_internal_set_denominator(from._internal_denominator());
  }
  if (!from._internal_category().empty()) {
    _this->_internal_set_category(from._internal_category());
  }
  if (!from._internal_description().empty()) {
    _this->_internal_set_description(from._internal_description());
  }
  if (from._internal_value_type() != 0) {
    _this->_internal_set_value_type(from._internal_value_type());
  }
  if (from._internal_aggregation() != 0) {
    _this->_internal_set_aggregation(from._internal_aggregation());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MetricDefinition::CopyFrom(const MetricDefinition& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rl.training.v1.MetricDefinition)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MetricDefinition::IsInitialized() const {
  return true;
}

void MetricDefinition::InternalSwap(MetricDefinition* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.metric_id_, lhs_arena,
      &other->_impl_.metric_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.display_name_, lhs_arena,
      &other->_impl_.display_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.unit_, lhs_arena,
      &other->_impl_.unit_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.scope_, lhs_arena,
      &other->_impl_.scope_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.denominator_, lhs_arena,
      &other->_impl_.denominator_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.category_, lhs_arena,
      &other->_impl_.category_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.description_, lhs_arena,
      &other->_impl_.description_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MetricDefinition, _impl_.aggregation_)
      + sizeof(MetricDefinition::_impl_.aggregation_)
      - PROTOBUF_FIELD_OFFSET(MetricDefinition, _impl_.value_type_)>(
          reinterpret_cast<char*>(&_impl_.value_type_),
          reinterpret_cast<char*>(&other->_impl_.value_type_));
}

::PROTOBUF_NAMESPACE_ID::Metadata MetricDefinition::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fmetrics_2fregistry_2eproto_getter, &descriptor_table_proto_2fmetrics_2fregistry_2eproto_once,
      file_level_metadata_proto_2fmetrics_2fregistry_2eproto[1]);
}

// ===================================================================

class MetricSumCount::_Internal {
 public:
};

MetricSumCount::MetricSumCount(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:rl.training.v1.MetricSumCount)
}
MetricSumCount::MetricSumCount(const MetricSumCount& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MetricSumCount* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.sum_){}
    , decltype(_impl_.count_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.sum_, &from._impl_.sum_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.count_) -
    reinterpret_cast<char*>(&_impl_.sum_)) + sizeof(_impl_.count_));
  // @@protoc_insertion_point(copy_constructor:rl.training.v1.MetricSumCount)
}

inline void MetricSumCount::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.sum_){0}
    , decltype(_impl_.count_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MetricSumCount::~MetricSumCount() {
  // @@protoc_insertion_point(destructor:rl.training.v1.MetricSumCount)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MetricSumCount::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void MetricSumCount::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MetricSumCount::Clear() {
// @@protoc_insertion_point(message_clear_start:rl.training.v1.MetricSumCount)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.sum_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.count_) -
      reinterpret_cast<char*>(&_impl_.sum_)) + sizeof(_impl_.count_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MetricSumCount::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // double sum = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 9)) {
          _impl_.sum_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // uint64 count = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.count_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MetricSumCount::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rl.training.v1.MetricSumCount)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // double sum = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_sum = this->_internal_sum();
  uint64_t raw_sum;
  memcpy(&raw_sum, &tmp_sum, sizeof(tmp_sum));
  if (raw_sum != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(1, this->_internal_sum(), target);
  }

  // uint64 count = 2;
  if (this->_internal_count() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_count(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rl.training.v1.MetricSumCount)
  return target;
}

size_t MetricSumCount::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rl.training.v1.MetricSumCount)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double sum = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_sum = this->_internal_sum();
  uint64_t raw_sum;
  memcpy(&raw_sum, &tmp_sum, sizeof(tmp_sum));
  if (raw_sum != 0) {
    total_size += 1 + 8;
  }

  // uint64 count = 2;
  if (this->_internal_count() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_count());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MetricSumCount::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MetricSumCount::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MetricSumCount::GetClassData() const { return &_class_data_; }


void MetricSumCount::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MetricSumCount*>(&to_msg);
  auto& from = static_cast<const MetricSumCount&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rl.training.v1.MetricSumCount)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_sum = from._internal_sum();
  uint64_t raw_sum;
  memcpy(&raw_sum, &tmp_sum, sizeof(tmp_sum));
  if (raw_sum != 0) {
    _this->_internal_set_sum(from._internal_sum());
  }
  if (from._internal_count() != 0) {
    _this->_internal_set_count(from._internal_count());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MetricSumCount::CopyFrom(const MetricSumCount& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rl.training.v1.MetricSumCount)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MetricSumCount::IsInitialized() const {
  return true;
}

void MetricSumCount::InternalSwap(MetricSumCount* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MetricSumCount, _impl_.count_)
      + sizeof(MetricSumCount::_impl_.count_)
      - PROTOBUF_FIELD_OFFSET(MetricSumCount, _impl_.sum_)>(
          reinterpret_cast<char*>(&_impl_.sum_),
          reinterpret_cast<char*>(&other->_impl_.sum_));
}

::PROTOBUF_NAMESPACE_ID::Metadata MetricSumCount::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fmetrics_2fregistry_2eproto_getter, &descriptor_table_proto_2fmetrics_2fregistry_2eproto_once,
      file_level_metadata_proto_2fmetrics_2fregistry_2eproto[2]);
}

// ===================================================================

MetricPoint_AttributesEntry_DoNotUse::MetricPoint_AttributesEntry_DoNotUse() {}
MetricPoint_AttributesEntry_DoNotUse::MetricPoint_AttributesEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void MetricPoint_AttributesEntry_DoNotUse::MergeFrom(const MetricPoint_AttributesEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata MetricPoint_AttributesEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fmetrics_2fregistry_2eproto_getter, &descriptor_table_proto_2fmetrics_2fregistry_2eproto_once,
      file_level_metadata_proto_2fmetrics_2fregistry_2eproto[3]);
}

// ===================================================================

class MetricPoint::_Internal {
 public:
  using HasBits = decltype(std::declval<MetricPoint>()._impl_._has_bits_);
  static const ::rl::training::v1::MetricSumCount& sum_count(const MetricPoint* msg);
  static void set_has_interval_start_unix_ms(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_interval_end_unix_ms(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

const ::rl::training::v1::MetricSumCount&
MetricPoint::_Internal::sum_count(const MetricPoint* msg) {
  return *msg->_impl_.value_.sum_count_;
}
void MetricPoint::set_allocated_sum_count(::rl::training::v1::MetricSumCount* sum_count) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_value();
  if (sum_count) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(sum_count);
    if (message_arena != submessage_arena) {
      sum_count = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, sum_count, submessage_arena);
    }
    set_has_sum_count();
    _impl_.value_.sum_count_ = sum_count;
  }
  // @@protoc_insertion_point(field_set_allocated:rl.training.v1.MetricPoint.sum_count)
}
MetricPoint::MetricPoint(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  if (arena != nullptr && !is_message_owned) {
    arena->OwnCustomDestructor(this, &MetricPoint::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:rl.training.v1.MetricPoint)
}
MetricPoint::MetricPoint(const MetricPoint& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MetricPoint* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_.attributes_)*/{}
    , decltype(_impl_.metric_id_){}
    , decltype(_impl_.interval_start_unix_ms_){}
    , decltype(_impl_.interval_end_unix_ms_){}
    , decltype(_impl_.value_){}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.attributes_.MergeFrom(from._impl_.attributes_);
  _impl_.metric_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.metric_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_metric_id().empty()) {
    _this->_impl_.metric_id_.Set(from._internal_metric_id(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.interval_start_unix_ms_, &from._impl_.interval_start_unix_ms_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.interval_end_unix_ms_) -
    reinterpret_cast<char*>(&_impl_.interval_start_unix_ms_)) + sizeof(_impl_.interval_end_unix_ms_));
  clear_has_value();
  switch (from.value_case()) {
    case kScalar: {
      _this->_internal_set_scalar(from._internal_scalar());
      break;
    }
    case kUnsignedValue: {
      _this->_internal_set_unsigned_value(from._internal_unsigned_value());
      break;
    }
    case kSumCount: {
      _this->_internal_mutable_sum_count()->::rl::training::v1::MetricSumCount::MergeFrom(
          from._internal_sum_count());
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:rl.training.v1.MetricPoint)
}

inline void MetricPoint::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_.attributes_)*/{::_pbi::ArenaInitialized(), arena}
    , decltype(_impl_.metric_id_){}
    , decltype(_impl_.interval_start_unix_ms_){int64_t{0}}
    , decltype(_impl_.interval_end_unix_ms_){int64_t{0}}
    , decltype(_impl_.value_){}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  _impl_.metric_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.metric_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  clear_has_value();
}

MetricPoint::~MetricPoint() {
  // @@protoc_insertion_point(destructor:rl.training.v1.MetricPoint)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void MetricPoint::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.attributes_.Destruct();
  _impl_.attributes_.~MapField();
  _impl_.metric_id_.Destroy();
  if (has_value()) {
    clear_value();
  }
}

void MetricPoint::ArenaDtor(void* object) {
  MetricPoint* _this = reinterpret_cast< MetricPoint* >(object);
  _this->_impl_.attributes_.Destruct();
}
void MetricPoint::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MetricPoint::clear_value() {
// @@protoc_insertion_point(one_of_clear_start:rl.training.v1.MetricPoint)
  switch (value_case()) {
    case kScalar: {
      // No need to clear
      break;
    }
    case kUnsignedValue: {
      // No need to clear
      break;
    }
    case kSumCount: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.value_.sum_count_;
      }
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = VALUE_NOT_SET;
}


void MetricPoint::Clear() {
// @@protoc_insertion_point(message_clear_start:rl.training.v1.MetricPoint)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.attributes_.Clear();
  _impl_.metric_id_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    ::memset(&_impl_.interval_start_unix_ms_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.interval_end_unix_ms_) -
        reinterpret_cast<char*>(&_impl_.interval_start_unix_ms_)) + sizeof(_impl_.interval_end_unix_ms_));
  }
  clear_value();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MetricPoint::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string metric_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_metric_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "rl.training.v1.MetricPoint.metric_id"));
        } else
          goto handle_unusual;
        continue;
      // double scalar = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _internal_set_scalar(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // uint64 unsigned_value = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _internal_set_unsigned_value(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .rl.training.v1.MetricSumCount sum_count = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_sum_count(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // map<string, string> attributes = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.attributes_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else
          goto handle_unusual;
        continue;
      // optional int64 interval_start_unix_ms = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _Internal::set_has_interval_start_unix_ms(&has_bits);
          _impl_.interval_start_unix_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional int64 interval_end_unix_ms = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _Internal::set_has_interval_end_unix_ms(&has_bits);
          _impl_.interval_end_unix_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MetricPoint::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rl.training.v1.MetricPoint)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string metric_id = 1;
  if (!this->_internal_metric_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_metric_id().data(), static_cast<int>(this->_internal_metric_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "rl.training.v1.MetricPoint.metric_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_metric_id(), target);
  }

  // double scalar = 2;
  if (_internal_has_scalar()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_scalar(), target);
  }

  // uint64 unsigned_value = 3;
  if (_internal_has_unsigned_value()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_unsigned_value(), target);
  }

  // .rl.training.v1.MetricSumCount sum_count = 4;
  if (_internal_has_sum_count()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::sum_count(this),
        _Internal::sum_count(this).GetCachedSize(), target, stream);
  }

  // map<string, string> attributes = 5;
  if (!this->_internal_attributes().empty()) {
    using MapType = ::_pb::Map<std::string, std::string>;
    using WireHelper = MetricPoint_AttributesEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_attributes();
    auto check_utf8 = [](const MapType::value_type& entry) {
      (void)entry;
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.first.data(), static_cast<int>(entry.first.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "rl.training.v1.MetricPoint.AttributesEntry.key");
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.second.data(), static_cast<int>(entry.second.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "rl.training.v1.MetricPoint.AttributesEntry.value");
    };

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterPtr<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(5, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(5, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    }
  }

  // optional int64 interval_start_unix_ms = 6;
  if (_internal_has_interval_start_unix_ms()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(6, this->_internal_interval_start_unix_ms(), target);
  }

  // optional int64 interval_end_unix_ms = 7;
  if (_internal_has_interval_end_unix_ms()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(7, this->_internal_interval_end_unix_ms(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rl.training.v1.MetricPoint)
  return target;
}

size_t MetricPoint::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rl.training.v1.MetricPoint)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, string> attributes = 5;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_attributes_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
      it = this->_internal_attributes().begin();
      it != this->_internal_attributes().end(); ++it) {
    total_size += MetricPoint_AttributesEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // string metric_id = 1;
  if (!this->_internal_metric_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_metric_id());
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional int64 interval_start_unix_ms = 6;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_interval_start_unix_ms());
    }

    // optional int64 interval_end_unix_ms = 7;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_interval_end_unix_ms());
    }

  }
  switch (value_case()) {
    // double scalar = 2;
    case kScalar: {
      total_size += 1 + 8;
      break;
    }
    // uint64 unsigned_value = 3;
    case kUnsignedValue: {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_unsigned_value());
      break;
    }
    // .rl.training.v1.MetricSumCount sum_count = 4;
    case kSumCount: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.value_.sum_count_);
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MetricPoint::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MetricPoint::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MetricPoint::GetClassData() const { return &_class_data_; }


void MetricPoint::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MetricPoint*>(&to_msg);
  auto& from = static_cast<const MetricPoint&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rl.training.v1.MetricPoint)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.attributes_.MergeFrom(from._impl_.attributes_);
  if (!from._internal_metric_id().empty()) {
    _this->_internal_set_metric_id(from._internal_metric_id());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.interval_start_unix_ms_ = from._impl_.interval_start_unix_ms_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.interval_end_unix_ms_ = from._impl_.interval_end_unix_ms_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  switch (from.value_case()) {
    case kScalar: {
      _this->_internal_set_scalar(from._internal_scalar());
      break;
    }
    case kUnsignedValue: {
      _this->_internal_set_unsigned_value(from._internal_unsigned_value());
      break;
    }
    case kSumCount: {
      _this->_internal_mutable_sum_count()->::rl::training::v1::MetricSumCount::MergeFrom(
          from._internal_sum_count());
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MetricPoint::CopyFrom(const MetricPoint& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rl.training.v1.MetricPoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MetricPoint::IsInitialized() const {
  return true;
}

void MetricPoint::InternalSwap(MetricPoint* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.attributes_.InternalSwap(&other->_impl_.attributes_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.metric_id_, lhs_arena,
      &other->_impl_.metric_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MetricPoint, _impl_.interval_end_unix_ms_)
      + sizeof(MetricPoint::_impl_.interval_end_unix_ms_)
      - PROTOBUF_FIELD_OFFSET(MetricPoint, _impl_.interval_start_unix_ms_)>(
          reinterpret_cast<char*>(&_impl_.interval_start_unix_ms_),
          reinterpret_cast<char*>(&other->_impl_.interval_start_unix_ms_));
  swap(_impl_.value_, other->_impl_.value_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata MetricPoint::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fmetrics_2fregistry_2eproto_getter, &descriptor_table_proto_2fmetrics_2fregistry_2eproto_once,
      file_level_metadata_proto_2fmetrics_2fregistry_2eproto[4]);
}

// ===================================================================

RegisteredMetricRecord_AttributesEntry_DoNotUse::RegisteredMetricRecord_AttributesEntry_DoNotUse() {}
RegisteredMetricRecord_AttributesEntry_DoNotUse::RegisteredMetricRecord_AttributesEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void RegisteredMetricRecord_AttributesEntry_DoNotUse::MergeFrom(const RegisteredMetricRecord_AttributesEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata RegisteredMetricRecord_AttributesEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fmetrics_2fregistry_2eproto_getter, &descriptor_table_proto_2fmetrics_2fregistry_2eproto_once,
      file_level_metadata_proto_2fmetrics_2fregistry_2eproto[5]);
}

// ===================================================================

class RegisteredMetricRecord::_Internal {
 public:
};

RegisteredMetricRecord::RegisteredMetricRecord(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  if (arena != nullptr && !is_message_owned) {
    arena->OwnCustomDestructor(this, &RegisteredMetricRecord::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:rl.training.v1.RegisteredMetricRecord)
}
RegisteredMetricRecord::RegisteredMetricRecord(const RegisteredMetricRecord& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RegisteredMetricRecord* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.definitions_){from._impl_.definitions_}
    , decltype(_impl_.points_){from._impl_.points_}
    , /*decltype(_impl_.attributes_)*/{}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.attributes_.MergeFrom(from._impl_.attributes_);
  // @@protoc_insertion_point(copy_constructor:rl.training.v1.RegisteredMetricRecord)
}

inline void RegisteredMetricRecord::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.definitions_){arena}
    , decltype(_impl_.points_){arena}
    , /*decltype(_impl_.attributes_)*/{::_pbi::ArenaInitialized(), arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

RegisteredMetricRecord::~RegisteredMetricRecord() {
  // @@protoc_insertion_point(destructor:rl.training.v1.RegisteredMetricRecord)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void RegisteredMetricRecord::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.definitions_.~RepeatedPtrField();
  _impl_.points_.~RepeatedPtrField();
  _impl_.attributes_.Destruct();
  _impl_.attributes_.~MapField();
}

void RegisteredMetricRecord::ArenaDtor(void* object) {
  RegisteredMetricRecord* _this = reinterpret_cast< RegisteredMetricRecord* >(object);
  _this->_impl_.attributes_.Destruct();
}
void RegisteredMetricRecord::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RegisteredMetricRecord::Clear() {
// @@protoc_insertion_point(message_clear_start:rl.training.v1.RegisteredMetricRecord)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.definitions_.Clear();
  _impl_.points_.Clear();
  _impl_.attributes_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RegisteredMetricRecord::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .rl.training.v1.MetricDefinition definitions = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_definitions(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .rl.training.v1.MetricPoint points = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_points(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      // map<string, string> attributes = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.attributes_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RegisteredMetricRecord::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rl.training.v1.RegisteredMetricRecord)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .rl.training.v1.MetricDefinition definitions = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_definitions_size()); i < n; i++) {
    const auto& repfield = this->_internal_definitions(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .rl.training.v1.MetricPoint points = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_points_size()); i < n; i++) {
    const auto& repfield = this->_internal_points(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  // map<string, string> attributes = 3;
  if (!this->_internal_attributes().empty()) {
    using MapType = ::_pb::Map<std::string, std::string>;
    using WireHelper = RegisteredMetricRecord_AttributesEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_attributes();
    auto check_utf8 = [](const MapType::value_type& entry) {
      (void)entry;
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.first.data(), static_cast<int>(entry.first.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "rl.training.v1.RegisteredMetricRecord.AttributesEntry.key");
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.second.data(), static_cast<int>(entry.second.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "rl.training.v1.RegisteredMetricRecord.AttributesEntry.value");
    };

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterPtr<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(3, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(3, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rl.training.v1.RegisteredMetricRecord)
  return target;
}

size_t RegisteredMetricRecord::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rl.training.v1.RegisteredMetricRecord)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .rl.training.v1.MetricDefinition definitions = 1;
  total_size += 1UL * this->_internal_definitions_size();
  for (const auto& msg : this->_impl_.definitions_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .rl.training.v1.MetricPoint points = 2;
  total_size += 1UL * this->_internal_points_size();
  for (const auto& msg : this->_impl_.points_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // map<string, string> attributes = 3;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_attributes_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
      it = this->_internal_attributes().begin();
      it != this->_internal_attributes().end(); ++it) {
    total_size += RegisteredMetricRecord_AttributesEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RegisteredMetricRecord::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RegisteredMetricRecord::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RegisteredMetricRecord::GetClassData() const { return &_class_data_; }


void RegisteredMetricRecord::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RegisteredMetricRecord*>(&to_msg);
  auto& from = static_cast<const RegisteredMetricRecord&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rl.training.v1.RegisteredMetricRecord)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.definitions_.MergeFrom(from._impl_.definitions_);
  _this->_impl_.points_.MergeFrom(from._impl_.points_);
  _this->_impl_.attributes_.MergeFrom(from._impl_.attributes_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RegisteredMetricRecord::CopyFrom(const RegisteredMetricRecord& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rl.training.v1.RegisteredMetricRecord)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RegisteredMetricRecord::IsInitialized() const {
  return true;
}

void RegisteredMetricRecord::InternalSwap(RegisteredMetricRecord* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.definitions_.InternalSwap(&other->_impl_.definitions_);
  _impl_.points_.InternalSwap(&other->_impl_.points_);
  _impl_.attributes_.InternalSwap(&other->_impl_.attributes_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RegisteredMetricRecord::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fmetrics_2fregistry_2eproto_getter, &descriptor_table_proto_2fmetrics_2fregistry_2eproto_once,
      file_level_metadata_proto_2fmetrics_2fregistry_2eproto[6]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace training
}  // namespace rl
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::rl::training::v1::RawMetricSumCount*
Arena::CreateMaybeMessage< ::rl::training::v1::RawMetricSumCount >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rl::training::v1::RawMetricSumCount >(arena);
}
template<> PROTOBUF_NOINLINE ::rl::training::v1::MetricDefinition*
Arena::CreateMaybeMessage< ::rl::training::v1::MetricDefinition >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rl::training::v1::MetricDefinition >(arena);
}
template<> PROTOBUF_NOINLINE ::rl::training::v1::MetricSumCount*
Arena::CreateMaybeMessage< ::rl::training::v1::MetricSumCount >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rl::training::v1::MetricSumCount >(arena);
}
template<> PROTOBUF_NOINLINE ::rl::training::v1::MetricPoint_AttributesEntry_DoNotUse*
Arena::CreateMaybeMessage< ::rl::training::v1::MetricPoint_AttributesEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rl::training::v1::MetricPoint_AttributesEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::rl::training::v1::MetricPoint*
Arena::CreateMaybeMessage< ::rl::training::v1::MetricPoint >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rl::training::v1::MetricPoint >(arena);
}
template<> PROTOBUF_NOINLINE ::rl::training::v1::RegisteredMetricRecord_AttributesEntry_DoNotUse*
Arena::CreateMaybeMessage< ::rl::training::v1::RegisteredMetricRecord_AttributesEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rl::training::v1::RegisteredMetricRecord_AttributesEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::rl::training::v1::RegisteredMetricRecord*
Arena::CreateMaybeMessage< ::rl::training::v1::RegisteredMetricRecord >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rl::training::v1::RegisteredMetricRecord >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
