// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/communication/session.proto

#include "proto/communication/session.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace rl {
namespace session {
namespace v1 {
PROTOBUF_CONSTEXPR CommandIdentity::CommandIdentity(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.session_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.episode_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.session_epoch_)*/uint64_t{0u}
  , /*decltype(_impl_.sequence_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CommandIdentityDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CommandIdentityDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CommandIdentityDefaultTypeInternal() {}
  union {
    CommandIdentity _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CommandIdentityDefaultTypeInternal _CommandIdentity_default_instance_;
PROTOBUF_CONSTEXPR CommandReply::CommandReply(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.result_)*/0
  , /*decltype(_impl_.error_code_)*/0
  , /*decltype(_impl_.applied_sequence_)*/uint64_t{0u}
  , /*decltype(_impl_.phase_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CommandReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CommandReplyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CommandReplyDefaultTypeInternal() {}
  union {
    CommandReply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CommandReplyDefaultTypeInternal _CommandReply_default_instance_;
}  // namespace v1
}  // namespace session
}  // namespace rl
static ::_pb::Metadata file_level_metadata_proto_2fcommunication_2fsession_2eproto[2];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_proto_2fcommunication_2fsession_2eproto[3];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_proto_2fcommunication_2fsession_2eproto = nullptr;

const uint32_t TableStruct_proto_2fcommunication_2fsession_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::rl::session::v1::CommandIdentity, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::rl::session::v1::CommandIdentity, _impl_.session_id_),
  PROTOBUF_FIELD_OFFSET(::rl::session::v1::CommandIdentity, _impl_.session_epoch_),
  PROTOBUF_FIELD_OFFSET(::rl::session::v1::CommandIdentity, _impl_.sequence_),
  PROTOBUF_FIELD_OFFSET(::rl::session::v1::CommandIdentity, _impl_.episode_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::rl::session::v1::CommandReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::rl::session::v1::CommandReply, _impl_.result_),
  PROTOBUF_FIELD_OFFSET(::rl::session::v1::CommandReply, _impl_.error_code_),
  PROTOBUF_FIELD_OFFSET(::rl::session::v1::CommandReply, _impl_.message_),
  PROTOBUF_FIELD_OFFSET(::rl::session::v1::CommandReply, _impl_.applied_sequence_),
  PROTOBUF_FIELD_OFFSET(::rl::session::v1::CommandReply, _impl_.phase_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::rl::session::v1::CommandIdentity)},
  { 10, -1, -1, sizeof(::rl::session::v1::CommandReply)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::rl::session::v1::_CommandIdentity_default_instance_._instance,
  &::rl::session::v1::_CommandReply_default_instance_._instance,
};

const char descriptor_table_protodef_proto_2fcommunication_2fsession_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n!proto/communication/session.proto\022\rrl."
  "session.v1\"b\n\017CommandIdentity\022\022\n\nsession"
  "_id\030\001 \001(\t\022\025\n\rsession_epoch\030\002 \001(\004\022\020\n\010sequ"
  "ence\030\003 \001(\004\022\022\n\nepisode_id\030\004 \001(\t\"\310\001\n\014Comma"
  "ndReply\022,\n\006result\030\001 \001(\0162\034.rl.session.v1."
  "CommandResult\0223\n\nerror_code\030\002 \001(\0162\037.rl.s"
  "ession.v1.CommandErrorCode\022\017\n\007message\030\003 "
  "\001(\t\022\030\n\020applied_sequence\030\004 \001(\004\022*\n\005phase\030\005"
  " \001(\0162\033.rl.session.v1.SessionPhase*\245\001\n\rCo"
  "mmandResult\022\036\n\032COMMAND_RESULT_UNSPECIFIE"
  "D\020\000\022\032\n\026COMMAND_RESULT_APPLIED\020\001\022\"\n\036COMMA"
  "ND_RESULT_ALREADY_APPLIED\020\002\022\027\n\023COMMAND_R"
  "ESULT_WAIT\020\003\022\033\n\027COMMAND_RESULT_REJECTED\020"
  "\004*\323\002\n\020CommandErrorCode\022\"\n\036COMMAND_ERROR_"
  "CODE_UNSPECIFIED\020\000\022\'\n#COMMAND_ERROR_CODE"
  "_INVALID_IDENTITY\020\001\022\"\n\036COMMAND_ERROR_COD"
  "E_STALE_EPOCH\020\002\022#\n\037COMMAND_ERROR_CODE_OU"
  "T_OF_ORDER\020\003\022\'\n#COMMAND_ERROR_CODE_PAYLO"
  "AD_CONFLICT\020\004\022%\n!COMMAND_ERROR_CODE_STAT"
  "E_CONFLICT\020\005\022)\n%COMMAND_ERROR_CODE_TASK_"
  "INPUT_INVALID\020\006\022.\n*COMMAND_ERROR_CODE_MO"
  "DEL_IDENTITY_MISMATCH\020\007*\373\001\n\014SessionPhase"
  "\022\035\n\031SESSION_PHASE_UNSPECIFIED\020\000\022\026\n\022SESSI"
  "ON_PHASE_OPEN\020\001\022\027\n\023SESSION_PHASE_READY\020\002"
  "\022!\n\035SESSION_PHASE_EPISODE_RUNNING\020\003\022\"\n\036S"
  "ESSION_PHASE_EPISODE_TERMINAL\020\004\022\037\n\033SESSI"
  "ON_PHASE_TASK_COMPLETE\020\005\022\030\n\024SESSION_PHAS"
  "E_CLOSED\020\006\022\031\n\025SESSION_PHASE_ABORTED\020\007B\003\200"
  "\001\000b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_proto_2fcommunication_2fsession_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_proto_2fcommunication_2fsession_2eproto = {
    false, false, 1130, descriptor_table_protodef_proto_2fcommunication_2fsession_2eproto,
    "proto/communication/session.proto",
    &descriptor_table_proto_2fcommunication_2fsession_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_proto_2fcommunication_2fsession_2eproto::offsets,
    file_level_metadata_proto_2fcommunication_2fsession_2eproto, file_level_enum_descriptors_proto_2fcommunication_2fsession_2eproto,
    file_level_service_descriptors_proto_2fcommunication_2fsession_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_proto_2fcommunication_2fsession_2eproto_getter() {
  return &descriptor_table_proto_2fcommunication_2fsession_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_proto_2fcommunication_2fsession_2eproto(&descriptor_table_proto_2fcommunication_2fsession_2eproto);
namespace rl {
namespace session {
namespace v1 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CommandResult_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_proto_2fcommunication_2fsession_2eproto);
  return file_level_enum_descriptors_proto_2fcommunication_2fsession_2eproto[0];
}
bool CommandResult_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CommandErrorCode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_proto_2fcommunication_2fsession_2eproto);
  return file_level_enum_descriptors_proto_2fcommunication_2fsession_2eproto[1];
}
bool CommandErrorCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SessionPhase_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_proto_2fcommunication_2fsession_2eproto);
  return file_level_enum_descriptors_proto_2fcommunication_2fsession_2eproto[2];
}
bool SessionPhase_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class CommandIdentity::_Internal {
 public:
};

CommandIdentity::CommandIdentity(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:rl.session.v1.CommandIdentity)
}
CommandIdentity::CommandIdentity(const CommandIdentity& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CommandIdentity* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.session_id_){}
    , decltype(_impl_.episode_id_){}
    , decltype(_impl_.session_epoch_){}
    , decltype(_impl_.sequence_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.session_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.session_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_session_id().empty()) {
    _this->_impl_.session_id_.Set(from._internal_session_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.episode_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.episode_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_episode_id().empty()) {
    _this->_impl_.episode_id_.Set(from._internal_episode_id(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.session_epoch_, &from._impl_.session_epoch_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.sequence_) -
    reinterpret_cast<char*>(&_impl_.session_epoch_)) + sizeof(_impl_.sequence_));
  // @@protoc_insertion_point(copy_constructor:rl.session.v1.CommandIdentity)
}

inline void CommandIdentity::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.session_id_){}
    , decltype(_impl_.episode_id_){}
    , decltype(_impl_.session_epoch_){uint64_t{0u}}
    , decltype(_impl_.sequence_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.session_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.session_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.episode_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.episode_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

CommandIdentity::~CommandIdentity() {
  // @@protoc_insertion_point(destructor:rl.session.v1.CommandIdentity)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CommandIdentity::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.session_id_.Destroy();
  _impl_.episode_id_.Destroy();
}

void CommandIdentity::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CommandIdentity::Clear() {
// @@protoc_insertion_point(message_clear_start:rl.session.v1.CommandIdentity)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.session_id_.ClearToEmpty();
  _impl_.episode_id_.ClearToEmpty();
  ::memset(&_impl_.session_epoch_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.sequence_) -
      reinterpret_cast<char*>(&_impl_.session_epoch_)) + sizeof(_impl_.sequence_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CommandIdentity::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string session_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_session_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "rl.session.v1.CommandIdentity.session_id"));
        } else
          goto handle_unusual;
        continue;
      // uint64 session_epoch = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.session_epoch_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 sequence = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.sequence_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string episode_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_episode_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "rl.session.v1.CommandIdentity.episode_id"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CommandIdentity::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rl.session.v1.CommandIdentity)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string session_id = 1;
  if (!this->_internal_session_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_session_id().data(), static_cast<int>(this->_internal_session_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "rl.session.v1.CommandIdentity.session_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_session_id(), target);
  }

  // uint64 session_epoch = 2;
  if (this->_internal_session_epoch() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_session_epoch(), target);
  }

  // uint64 sequence = 3;
  if (this->_internal_sequence() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_sequence(), target);
  }

  // string episode_id = 4;
  if (!this->_internal_episode_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_episode_id().data(), static_cast<int>(this->_internal_episode_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "rl.session.v1.CommandIdentity.episode_id");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_episode_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rl.session.v1.CommandIdentity)
  return target;
}

size_t CommandIdentity::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rl.session.v1.CommandIdentity)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string session_id = 1;
  if (!this->_internal_session_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_session_id());
  }

  // string episode_id = 4;
  if (!this->_internal_episode_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_episode_id());
  }

  // uint64 session_epoch = 2;
  if (this->_internal_session_epoch() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_session_epoch());
  }

  // uint64 sequence = 3;
  if (this->_internal_sequence() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_sequence());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CommandIdentity::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CommandIdentity::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CommandIdentity::GetClassData() const { return &_class_data_; }


void CommandIdentity::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CommandIdentity*>(&to_msg);
  auto& from = static_cast<const CommandIdentity&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rl.session.v1.CommandIdentity)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_session_id().empty()) {
    _this->_internal_set_session_id(from._internal_session_id());
  }
  if (!from._internal_episode_id().empty()) {
    _this->_internal_set_episode_id(from._internal_episode_id());
  }
  if (from._internal_session_epoch() != 0) {
    _this->_internal_set_session_epoch(from._internal_session_epoch());
  }
  if (from._internal_sequence() != 0) {
    _this->_internal_set_sequence(from._internal_sequence());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CommandIdentity::CopyFrom(const CommandIdentity& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rl.session.v1.CommandIdentity)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CommandIdentity::IsInitialized() const {
  return true;
}

void CommandIdentity::InternalSwap(CommandIdentity* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.session_id_, lhs_arena,
      &other->_impl_.session_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.episode_id_, lhs_arena,
      &other->_impl_.episode_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CommandIdentity, _impl_.sequence_)
      + sizeof(CommandIdentity::_impl_.sequence_)
      - PROTOBUF_FIELD_OFFSET(CommandIdentity, _impl_.session_epoch_)>(
          reinterpret_cast<char*>(&_impl_.session_epoch_),
          reinterpret_cast<char*>(&other->_impl_.session_epoch_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CommandIdentity::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fcommunication_2fsession_2eproto_getter, &descriptor_table_proto_2fcommunication_2fsession_2eproto_once,
      file_level_metadata_proto_2fcommunication_2fsession_2eproto[0]);
}

// ===================================================================

class CommandReply::_Internal {
 public:
};

CommandReply::CommandReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:rl.session.v1.CommandReply)
}
CommandReply::CommandReply(const CommandReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CommandReply* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){}
    , decltype(_impl_.result_){}
    , decltype(_impl_.error_code_){}
    , decltype(_impl_.applied_sequence_){}
    , decltype(_impl_.phase_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message().empty()) {
    _this->_impl_.message_.Set(from._internal_message(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.result_, &from._impl_.result_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.phase_) -
    reinterpret_cast<char*>(&_impl_.result_)) + sizeof(_impl_.phase_));
  // @@protoc_insertion_point(copy_constructor:rl.session.v1.CommandReply)
}

inline void CommandReply::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){}
    , decltype(_impl_.result_){0}
    , decltype(_impl_.error_code_){0}
    , decltype(_impl_.applied_sequence_){uint64_t{0u}}
    , decltype(_impl_.phase_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

CommandReply::~CommandReply() {
  // @@protoc_insertion_point(destructor:rl.session.v1.CommandReply)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CommandReply::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.message_.Destroy();
}

void CommandReply::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CommandReply::Clear() {
// @@protoc_insertion_point(message_clear_start:rl.session.v1.CommandReply)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  ::memset(&_impl_.result_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.phase_) -
      reinterpret_cast<char*>(&_impl_.result_)) + sizeof(_impl_.phase_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CommandReply::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .rl.session.v1.CommandResult result = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_result(static_cast<::rl::session::v1::CommandResult>(val));
        } else
          goto handle_unusual;
        continue;
      // .rl.session.v1.CommandErrorCode error_code = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_error_code(static_cast<::rl::session::v1::CommandErrorCode>(val));
        } else
          goto handle_unusual;
        continue;
      // string message = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "rl.session.v1.CommandReply.message"));
        } else
          goto handle_unusual;
        continue;
      // uint64 applied_sequence = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.applied_sequence_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .rl.session.v1.SessionPhase phase = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_phase(static_cast<::rl::session::v1::SessionPhase>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CommandReply::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rl.session.v1.CommandReply)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .rl.session.v1.CommandResult result = 1;
  if (this->_internal_result() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_result(), target);
  }

  // .rl.session.v1.CommandErrorCode error_code = 2;
  if (this->_internal_error_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_error_code(), target);
  }

  // string message = 3;
  if (!this->_internal_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message().data(), static_cast<int>(this->_internal_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "rl.session.v1.CommandReply.message");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_message(), target);
  }

  // uint64 applied_sequence = 4;
  if (this->_internal_applied_sequence() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(4, this->_internal_applied_sequence(), target);
  }

  // .rl.session.v1.SessionPhase phase = 5;
  if (this->_internal_phase() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      5, this->_internal_phase(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rl.session.v1.CommandReply)
  return target;
}

size_t CommandReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rl.session.v1.CommandReply)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 3;
  if (!this->_internal_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message());
  }

  // .rl.session.v1.CommandResult result = 1;
  if (this->_internal_result() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_result());
  }

  // .rl.session.v1.CommandErrorCode error_code = 2;
  if (this->_internal_error_code() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_error_code());
  }

  // uint64 applied_sequence = 4;
  if (this->_internal_applied_sequence() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_applied_sequence());
  }

  // .rl.session.v1.SessionPhase phase = 5;
  if (this->_internal_phase() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_phase());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CommandReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CommandReply::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CommandReply::GetClassData() const { return &_class_data_; }


void CommandReply::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CommandReply*>(&to_msg);
  auto& from = static_cast<const CommandReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rl.session.v1.CommandReply)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_result() != 0) {
    _this->_internal_set_result(from._internal_result());
  }
  if (from._internal_error_code() != 0) {
    _this->_internal_set_error_code(from._internal_error_code());
  }
  if (from._internal_applied_sequence() != 0) {
    _this->_internal_set_applied_sequence(from._internal_applied_sequence());
  }
  if (from._internal_phase() != 0) {
    _this->_internal_set_phase(from._internal_phase());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CommandReply::CopyFrom(const CommandReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rl.session.v1.CommandReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CommandReply::IsInitialized() const {
  return true;
}

void CommandReply::InternalSwap(CommandReply* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_, lhs_arena,
      &other->_impl_.message_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CommandReply, _impl_.phase_)
      + sizeof(CommandReply::_impl_.phase_)
      - PROTOBUF_FIELD_OFFSET(CommandReply, _impl_.result_)>(
          reinterpret_cast<char*>(&_impl_.result_),
          reinterpret_cast<char*>(&other->_impl_.result_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CommandReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fcommunication_2fsession_2eproto_getter, &descriptor_table_proto_2fcommunication_2fsession_2eproto_once,
      file_level_metadata_proto_2fcommunication_2fsession_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace session
}  // namespace rl
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::rl::session::v1::CommandIdentity*
Arena::CreateMaybeMessage< ::rl::session::v1::CommandIdentity >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rl::session::v1::CommandIdentity >(arena);
}
template<> PROTOBUF_NOINLINE ::rl::session::v1::CommandReply*
Arena::CreateMaybeMessage< ::rl::session::v1::CommandReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rl::session::v1::CommandReply >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
