// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/common/identity.proto

#include "proto/common/identity.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace rl {
namespace common {
namespace v1 {
PROTOBUF_CONSTEXPR ServiceInstanceIdentity::ServiceInstanceIdentity(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.component_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.instance_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.lifecycle_epoch_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ServiceInstanceIdentityDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ServiceInstanceIdentityDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ServiceInstanceIdentityDefaultTypeInternal() {}
  union {
    ServiceInstanceIdentity _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ServiceInstanceIdentityDefaultTypeInternal _ServiceInstanceIdentity_default_instance_;
}  // namespace v1
}  // namespace common
}  // namespace rl
static ::_pb::Metadata file_level_metadata_proto_2fcommon_2fidentity_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_proto_2fcommon_2fidentity_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_proto_2fcommon_2fidentity_2eproto = nullptr;

const uint32_t TableStruct_proto_2fcommon_2fidentity_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::rl::common::v1::ServiceInstanceIdentity, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::rl::common::v1::ServiceInstanceIdentity, _impl_.component_),
  PROTOBUF_FIELD_OFFSET(::rl::common::v1::ServiceInstanceIdentity, _impl_.instance_id_),
  PROTOBUF_FIELD_OFFSET(::rl::common::v1::ServiceInstanceIdentity, _impl_.lifecycle_epoch_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::rl::common::v1::ServiceInstanceIdentity)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::rl::common::v1::_ServiceInstanceIdentity_default_instance_._instance,
};

const char descriptor_table_protodef_proto_2fcommon_2fidentity_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\033proto/common/identity.proto\022\014rl.common"
  ".v1\"Z\n\027ServiceInstanceIdentity\022\021\n\tcompon"
  "ent\030\001 \001(\t\022\023\n\013instance_id\030\002 \001(\t\022\027\n\017lifecy"
  "cle_epoch\030\003 \001(\004*\226\001\n\017OperationResult\022 \n\034O"
  "PERATION_RESULT_UNSPECIFIED\020\000\022\034\n\030OPERATI"
  "ON_RESULT_APPLIED\020\001\022$\n OPERATION_RESULT_"
  "ALREADY_APPLIED\020\002\022\035\n\031OPERATION_RESULT_RE"
  "JECTED\020\003B\003\200\001\000b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_proto_2fcommon_2fidentity_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_proto_2fcommon_2fidentity_2eproto = {
    false, false, 301, descriptor_table_protodef_proto_2fcommon_2fidentity_2eproto,
    "proto/common/identity.proto",
    &descriptor_table_proto_2fcommon_2fidentity_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_proto_2fcommon_2fidentity_2eproto::offsets,
    file_level_metadata_proto_2fcommon_2fidentity_2eproto, file_level_enum_descriptors_proto_2fcommon_2fidentity_2eproto,
    file_level_service_descriptors_proto_2fcommon_2fidentity_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_proto_2fcommon_2fidentity_2eproto_getter() {
  return &descriptor_table_proto_2fcommon_2fidentity_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_proto_2fcommon_2fidentity_2eproto(&descriptor_table_proto_2fcommon_2fidentity_2eproto);
namespace rl {
namespace common {
namespace v1 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* OperationResult_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_proto_2fcommon_2fidentity_2eproto);
  return file_level_enum_descriptors_proto_2fcommon_2fidentity_2eproto[0];
}
bool OperationResult_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class ServiceInstanceIdentity::_Internal {
 public:
};

ServiceInstanceIdentity::ServiceInstanceIdentity(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:rl.common.v1.ServiceInstanceIdentity)
}
ServiceInstanceIdentity::ServiceInstanceIdentity(const ServiceInstanceIdentity& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ServiceInstanceIdentity* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.component_){}
    , decltype(_impl_.instance_id_){}
    , decltype(_impl_.lifecycle_epoch_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.component_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.component_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_component().empty()) {
    _this->_impl_.component_.Set(from._internal_component(), 
      _this->GetArenaForAllocation());
  }
  _impl_.instance_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.instance_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_instance_id().empty()) {
    _this->_impl_.instance_id_.Set(from._internal_instance_id(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.lifecycle_epoch_ = from._impl_.lifecycle_epoch_;
  // @@protoc_insertion_point(copy_constructor:rl.common.v1.ServiceInstanceIdentity)
}

inline void ServiceInstanceIdentity::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.component_){}
    , decltype(_impl_.instance_id_){}
    , decltype(_impl_.lifecycle_epoch_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.component_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.component_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.instance_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.instance_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ServiceInstanceIdentity::~ServiceInstanceIdentity() {
  // @@protoc_insertion_point(destructor:rl.common.v1.ServiceInstanceIdentity)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ServiceInstanceIdentity::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.component_.Destroy();
  _impl_.instance_id_.Destroy();
}

void ServiceInstanceIdentity::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ServiceInstanceIdentity::Clear() {
// @@protoc_insertion_point(message_clear_start:rl.common.v1.ServiceInstanceIdentity)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.component_.ClearToEmpty();
  _impl_.instance_id_.ClearToEmpty();
  _impl_.lifecycle_epoch_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ServiceInstanceIdentity::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string component = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_component();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "rl.common.v1.ServiceInstanceIdentity.component"));
        } else
          goto handle_unusual;
        continue;
      // string instance_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_instance_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "rl.common.v1.ServiceInstanceIdentity.instance_id"));
        } else
          goto handle_unusual;
        continue;
      // uint64 lifecycle_epoch = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.lifecycle_epoch_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ServiceInstanceIdentity::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rl.common.v1.ServiceInstanceIdentity)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string component = 1;
  if (!this->_internal_component().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_component().data(), static_cast<int>(this->_internal_component().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "rl.common.v1.ServiceInstanceIdentity.component");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_component(), target);
  }

  // string instance_id = 2;
  if (!this->_internal_instance_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_instance_id().data(), static_cast<int>(this->_internal_instance_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "rl.common.v1.ServiceInstanceIdentity.instance_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_instance_id(), target);
  }

  // uint64 lifecycle_epoch = 3;
  if (this->_internal_lifecycle_epoch() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_lifecycle_epoch(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rl.common.v1.ServiceInstanceIdentity)
  return target;
}

size_t ServiceInstanceIdentity::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rl.common.v1.ServiceInstanceIdentity)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string component = 1;
  if (!this->_internal_component().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_component());
  }

  // string instance_id = 2;
  if (!this->_internal_instance_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_instance_id());
  }

  // uint64 lifecycle_epoch = 3;
  if (this->_internal_lifecycle_epoch() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_lifecycle_epoch());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ServiceInstanceIdentity::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ServiceInstanceIdentity::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ServiceInstanceIdentity::GetClassData() const { return &_class_data_; }


void ServiceInstanceIdentity::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ServiceInstanceIdentity*>(&to_msg);
  auto& from = static_cast<const ServiceInstanceIdentity&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rl.common.v1.ServiceInstanceIdentity)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_component().empty()) {
    _this->_internal_set_component(from._internal_component());
  }
  if (!from._internal_instance_id().empty()) {
    _this->_internal_set_instance_id(from._internal_instance_id());
  }
  if (from._internal_lifecycle_epoch() != 0) {
    _this->_internal_set_lifecycle_epoch(from._internal_lifecycle_epoch());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ServiceInstanceIdentity::CopyFrom(const ServiceInstanceIdentity& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rl.common.v1.ServiceInstanceIdentity)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ServiceInstanceIdentity::IsInitialized() const {
  return true;
}

void ServiceInstanceIdentity::InternalSwap(ServiceInstanceIdentity* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.component_, lhs_arena,
      &other->_impl_.component_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.instance_id_, lhs_arena,
      &other->_impl_.instance_id_, rhs_arena
  );
  swap(_impl_.lifecycle_epoch_, other->_impl_.lifecycle_epoch_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ServiceInstanceIdentity::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fcommon_2fidentity_2eproto_getter, &descriptor_table_proto_2fcommon_2fidentity_2eproto_once,
      file_level_metadata_proto_2fcommon_2fidentity_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace common
}  // namespace rl
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::rl::common::v1::ServiceInstanceIdentity*
Arena::CreateMaybeMessage< ::rl::common::v1::ServiceInstanceIdentity >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rl::common::v1::ServiceInstanceIdentity >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
