// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

#include "common.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace rl {
namespace common {
namespace v1 {
PROTOBUF_CONSTEXPR ContentDigest::ContentDigest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.hex_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.algorithm_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ContentDigestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ContentDigestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ContentDigestDefaultTypeInternal() {}
  union {
    ContentDigest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ContentDigestDefaultTypeInternal _ContentDigest_default_instance_;
PROTOBUF_CONSTEXPR ContractIdentity::ContractIdentity(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.package_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.package_version_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.platform_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.generator_identity_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.source_digest_)*/nullptr
  , /*decltype(_impl_.artifact_digest_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ContractIdentityDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ContractIdentityDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ContractIdentityDefaultTypeInternal() {}
  union {
    ContractIdentity _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ContractIdentityDefaultTypeInternal _ContractIdentity_default_instance_;
PROTOBUF_CONSTEXPR SchemaIdentity::SchemaIdentity(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.schema_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.canonical_digest_)*/nullptr
  , /*decltype(_impl_.schema_version_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SchemaIdentityDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SchemaIdentityDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SchemaIdentityDefaultTypeInternal() {}
  union {
    SchemaIdentity _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SchemaIdentityDefaultTypeInternal _SchemaIdentity_default_instance_;
PROTOBUF_CONSTEXPR ServiceInstanceIdentity::ServiceInstanceIdentity(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.component_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.instance_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.lifecycle_epoch_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ServiceInstanceIdentityDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ServiceInstanceIdentityDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ServiceInstanceIdentityDefaultTypeInternal() {}
  union {
    ServiceInstanceIdentity _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ServiceInstanceIdentityDefaultTypeInternal _ServiceInstanceIdentity_default_instance_;
}  // namespace v1
}  // namespace common
}  // namespace rl
static ::_pb::Metadata file_level_metadata_common_2eproto[4];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_common_2eproto[2];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_common_2eproto = nullptr;

const uint32_t TableStruct_common_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::rl::common::v1::ContentDigest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::rl::common::v1::ContentDigest, _impl_.algorithm_),
  PROTOBUF_FIELD_OFFSET(::rl::common::v1::ContentDigest, _impl_.hex_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::rl::common::v1::ContractIdentity, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::rl::common::v1::ContractIdentity, _impl_.package_name_),
  PROTOBUF_FIELD_OFFSET(::rl::common::v1::ContractIdentity, _impl_.package_version_),
  PROTOBUF_FIELD_OFFSET(::rl::common::v1::ContractIdentity, _impl_.source_digest_),
  PROTOBUF_FIELD_OFFSET(::rl::common::v1::ContractIdentity, _impl_.artifact_digest_),
  PROTOBUF_FIELD_OFFSET(::rl::common::v1::ContractIdentity, _impl_.platform_),
  PROTOBUF_FIELD_OFFSET(::rl::common::v1::ContractIdentity, _impl_.generator_identity_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::rl::common::v1::SchemaIdentity, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::rl::common::v1::SchemaIdentity, _impl_.schema_id_),
  PROTOBUF_FIELD_OFFSET(::rl::common::v1::SchemaIdentity, _impl_.schema_version_),
  PROTOBUF_FIELD_OFFSET(::rl::common::v1::SchemaIdentity, _impl_.canonical_digest_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::rl::common::v1::ServiceInstanceIdentity, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::rl::common::v1::ServiceInstanceIdentity, _impl_.component_),
  PROTOBUF_FIELD_OFFSET(::rl::common::v1::ServiceInstanceIdentity, _impl_.instance_id_),
  PROTOBUF_FIELD_OFFSET(::rl::common::v1::ServiceInstanceIdentity, _impl_.lifecycle_epoch_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::rl::common::v1::ContentDigest)},
  { 8, -1, -1, sizeof(::rl::common::v1::ContractIdentity)},
  { 20, -1, -1, sizeof(::rl::common::v1::SchemaIdentity)},
  { 29, -1, -1, sizeof(::rl::common::v1::ServiceInstanceIdentity)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::rl::common::v1::_ContentDigest_default_instance_._instance,
  &::rl::common::v1::_ContractIdentity_default_instance_._instance,
  &::rl::common::v1::_SchemaIdentity_default_instance_._instance,
  &::rl::common::v1::_ServiceInstanceIdentity_default_instance_._instance,
};

const char descriptor_table_protodef_common_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014common.proto\022\014rl.common.v1\"N\n\rContentD"
  "igest\0220\n\talgorithm\030\001 \001(\0162\035.rl.common.v1."
  "DigestAlgorithm\022\013\n\003hex\030\002 \001(\t\"\331\001\n\020Contrac"
  "tIdentity\022\024\n\014package_name\030\001 \001(\t\022\027\n\017packa"
  "ge_version\030\002 \001(\t\0222\n\rsource_digest\030\003 \001(\0132"
  "\033.rl.common.v1.ContentDigest\0224\n\017artifact"
  "_digest\030\004 \001(\0132\033.rl.common.v1.ContentDige"
  "st\022\020\n\010platform\030\005 \001(\t\022\032\n\022generator_identi"
  "ty\030\006 \001(\t\"r\n\016SchemaIdentity\022\021\n\tschema_id\030"
  "\001 \001(\t\022\026\n\016schema_version\030\002 \001(\r\0225\n\020canonic"
  "al_digest\030\003 \001(\0132\033.rl.common.v1.ContentDi"
  "gest\"Z\n\027ServiceInstanceIdentity\022\021\n\tcompo"
  "nent\030\001 \001(\t\022\023\n\013instance_id\030\002 \001(\t\022\027\n\017lifec"
  "ycle_epoch\030\003 \001(\004*\226\001\n\017OperationResult\022 \n\034"
  "OPERATION_RESULT_UNSPECIFIED\020\000\022\034\n\030OPERAT"
  "ION_RESULT_APPLIED\020\001\022$\n OPERATION_RESULT"
  "_ALREADY_APPLIED\020\002\022\035\n\031OPERATION_RESULT_R"
  "EJECTED\020\003*P\n\017DigestAlgorithm\022 \n\034DIGEST_A"
  "LGORITHM_UNSPECIFIED\020\000\022\033\n\027DIGEST_ALGORIT"
  "HM_SHA256\020\001B\003\200\001\000b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_common_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_common_2eproto = {
    false, false, 784, descriptor_table_protodef_common_2eproto,
    "common.proto",
    &descriptor_table_common_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_common_2eproto::offsets,
    file_level_metadata_common_2eproto, file_level_enum_descriptors_common_2eproto,
    file_level_service_descriptors_common_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_common_2eproto_getter() {
  return &descriptor_table_common_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_common_2eproto(&descriptor_table_common_2eproto);
namespace rl {
namespace common {
namespace v1 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* OperationResult_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_common_2eproto);
  return file_level_enum_descriptors_common_2eproto[0];
}
bool OperationResult_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DigestAlgorithm_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_common_2eproto);
  return file_level_enum_descriptors_common_2eproto[1];
}
bool DigestAlgorithm_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class ContentDigest::_Internal {
 public:
};

ContentDigest::ContentDigest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:rl.common.v1.ContentDigest)
}
ContentDigest::ContentDigest(const ContentDigest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ContentDigest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.hex_){}
    , decltype(_impl_.algorithm_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.hex_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.hex_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_hex().empty()) {
    _this->_impl_.hex_.Set(from._internal_hex(),
      _this->GetArenaForAllocation());
  }
  _this->_impl_.algorithm_ = from._impl_.algorithm_;
  // @@protoc_insertion_point(copy_constructor:rl.common.v1.ContentDigest)
}

inline void ContentDigest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.hex_){}
    , decltype(_impl_.algorithm_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.hex_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.hex_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ContentDigest::~ContentDigest() {
  // @@protoc_insertion_point(destructor:rl.common.v1.ContentDigest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ContentDigest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.hex_.Destroy();
}

void ContentDigest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ContentDigest::Clear() {
// @@protoc_insertion_point(message_clear_start:rl.common.v1.ContentDigest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.hex_.ClearToEmpty();
  _impl_.algorithm_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ContentDigest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .rl.common.v1.DigestAlgorithm algorithm = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_algorithm(static_cast<::rl::common::v1::DigestAlgorithm>(val));
        } else
          goto handle_unusual;
        continue;
      // string hex = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_hex();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "rl.common.v1.ContentDigest.hex"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ContentDigest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rl.common.v1.ContentDigest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .rl.common.v1.DigestAlgorithm algorithm = 1;
  if (this->_internal_algorithm() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_algorithm(), target);
  }

  // string hex = 2;
  if (!this->_internal_hex().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_hex().data(), static_cast<int>(this->_internal_hex().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "rl.common.v1.ContentDigest.hex");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_hex(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rl.common.v1.ContentDigest)
  return target;
}

size_t ContentDigest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rl.common.v1.ContentDigest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string hex = 2;
  if (!this->_internal_hex().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_hex());
  }

  // .rl.common.v1.DigestAlgorithm algorithm = 1;
  if (this->_internal_algorithm() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_algorithm());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ContentDigest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ContentDigest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ContentDigest::GetClassData() const { return &_class_data_; }


void ContentDigest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ContentDigest*>(&to_msg);
  auto& from = static_cast<const ContentDigest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rl.common.v1.ContentDigest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_hex().empty()) {
    _this->_internal_set_hex(from._internal_hex());
  }
  if (from._internal_algorithm() != 0) {
    _this->_internal_set_algorithm(from._internal_algorithm());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ContentDigest::CopyFrom(const ContentDigest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rl.common.v1.ContentDigest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ContentDigest::IsInitialized() const {
  return true;
}

void ContentDigest::InternalSwap(ContentDigest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.hex_, lhs_arena,
      &other->_impl_.hex_, rhs_arena
  );
  swap(_impl_.algorithm_, other->_impl_.algorithm_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ContentDigest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_common_2eproto_getter, &descriptor_table_common_2eproto_once,
      file_level_metadata_common_2eproto[0]);
}

// ===================================================================

class ContractIdentity::_Internal {
 public:
  static const ::rl::common::v1::ContentDigest& source_digest(const ContractIdentity* msg);
  static const ::rl::common::v1::ContentDigest& artifact_digest(const ContractIdentity* msg);
};

const ::rl::common::v1::ContentDigest&
ContractIdentity::_Internal::source_digest(const ContractIdentity* msg) {
  return *msg->_impl_.source_digest_;
}
const ::rl::common::v1::ContentDigest&
ContractIdentity::_Internal::artifact_digest(const ContractIdentity* msg) {
  return *msg->_impl_.artifact_digest_;
}
ContractIdentity::ContractIdentity(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:rl.common.v1.ContractIdentity)
}
ContractIdentity::ContractIdentity(const ContractIdentity& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ContractIdentity* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.package_name_){}
    , decltype(_impl_.package_version_){}
    , decltype(_impl_.platform_){}
    , decltype(_impl_.generator_identity_){}
    , decltype(_impl_.source_digest_){nullptr}
    , decltype(_impl_.artifact_digest_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.package_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.package_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_package_name().empty()) {
    _this->_impl_.package_name_.Set(from._internal_package_name(),
      _this->GetArenaForAllocation());
  }
  _impl_.package_version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.package_version_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_package_version().empty()) {
    _this->_impl_.package_version_.Set(from._internal_package_version(),
      _this->GetArenaForAllocation());
  }
  _impl_.platform_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.platform_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_platform().empty()) {
    _this->_impl_.platform_.Set(from._internal_platform(),
      _this->GetArenaForAllocation());
  }
  _impl_.generator_identity_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.generator_identity_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_generator_identity().empty()) {
    _this->_impl_.generator_identity_.Set(from._internal_generator_identity(),
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_source_digest()) {
    _this->_impl_.source_digest_ = new ::rl::common::v1::ContentDigest(*from._impl_.source_digest_);
  }
  if (from._internal_has_artifact_digest()) {
    _this->_impl_.artifact_digest_ = new ::rl::common::v1::ContentDigest(*from._impl_.artifact_digest_);
  }
  // @@protoc_insertion_point(copy_constructor:rl.common.v1.ContractIdentity)
}

inline void ContractIdentity::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.package_name_){}
    , decltype(_impl_.package_version_){}
    , decltype(_impl_.platform_){}
    , decltype(_impl_.generator_identity_){}
    , decltype(_impl_.source_digest_){nullptr}
    , decltype(_impl_.artifact_digest_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.package_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.package_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.package_version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.package_version_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.platform_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.platform_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.generator_identity_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.generator_identity_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ContractIdentity::~ContractIdentity() {
  // @@protoc_insertion_point(destructor:rl.common.v1.ContractIdentity)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ContractIdentity::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.package_name_.Destroy();
  _impl_.package_version_.Destroy();
  _impl_.platform_.Destroy();
  _impl_.generator_identity_.Destroy();
  if (this != internal_default_instance()) delete _impl_.source_digest_;
  if (this != internal_default_instance()) delete _impl_.artifact_digest_;
}

void ContractIdentity::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ContractIdentity::Clear() {
// @@protoc_insertion_point(message_clear_start:rl.common.v1.ContractIdentity)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.package_name_.ClearToEmpty();
  _impl_.package_version_.ClearToEmpty();
  _impl_.platform_.ClearToEmpty();
  _impl_.generator_identity_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.source_digest_ != nullptr) {
    delete _impl_.source_digest_;
  }
  _impl_.source_digest_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.artifact_digest_ != nullptr) {
    delete _impl_.artifact_digest_;
  }
  _impl_.artifact_digest_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ContractIdentity::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string package_name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_package_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "rl.common.v1.ContractIdentity.package_name"));
        } else
          goto handle_unusual;
        continue;
      // string package_version = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_package_version();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "rl.common.v1.ContractIdentity.package_version"));
        } else
          goto handle_unusual;
        continue;
      // .rl.common.v1.ContentDigest source_digest = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_source_digest(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .rl.common.v1.ContentDigest artifact_digest = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_artifact_digest(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string platform = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_platform();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "rl.common.v1.ContractIdentity.platform"));
        } else
          goto handle_unusual;
        continue;
      // string generator_identity = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_generator_identity();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "rl.common.v1.ContractIdentity.generator_identity"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ContractIdentity::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rl.common.v1.ContractIdentity)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string package_name = 1;
  if (!this->_internal_package_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_package_name().data(), static_cast<int>(this->_internal_package_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "rl.common.v1.ContractIdentity.package_name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_package_name(), target);
  }

  // string package_version = 2;
  if (!this->_internal_package_version().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_package_version().data(), static_cast<int>(this->_internal_package_version().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "rl.common.v1.ContractIdentity.package_version");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_package_version(), target);
  }

  // .rl.common.v1.ContentDigest source_digest = 3;
  if (this->_internal_has_source_digest()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::source_digest(this),
        _Internal::source_digest(this).GetCachedSize(), target, stream);
  }

  // .rl.common.v1.ContentDigest artifact_digest = 4;
  if (this->_internal_has_artifact_digest()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::artifact_digest(this),
        _Internal::artifact_digest(this).GetCachedSize(), target, stream);
  }

  // string platform = 5;
  if (!this->_internal_platform().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_platform().data(), static_cast<int>(this->_internal_platform().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "rl.common.v1.ContractIdentity.platform");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_platform(), target);
  }

  // string generator_identity = 6;
  if (!this->_internal_generator_identity().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_generator_identity().data(), static_cast<int>(this->_internal_generator_identity().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "rl.common.v1.ContractIdentity.generator_identity");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_generator_identity(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rl.common.v1.ContractIdentity)
  return target;
}

size_t ContractIdentity::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rl.common.v1.ContractIdentity)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string package_name = 1;
  if (!this->_internal_package_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_package_name());
  }

  // string package_version = 2;
  if (!this->_internal_package_version().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_package_version());
  }

  // string platform = 5;
  if (!this->_internal_platform().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_platform());
  }

  // string generator_identity = 6;
  if (!this->_internal_generator_identity().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_generator_identity());
  }

  // .rl.common.v1.ContentDigest source_digest = 3;
  if (this->_internal_has_source_digest()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.source_digest_);
  }

  // .rl.common.v1.ContentDigest artifact_digest = 4;
  if (this->_internal_has_artifact_digest()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.artifact_digest_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ContractIdentity::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ContractIdentity::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ContractIdentity::GetClassData() const { return &_class_data_; }


void ContractIdentity::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ContractIdentity*>(&to_msg);
  auto& from = static_cast<const ContractIdentity&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rl.common.v1.ContractIdentity)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_package_name().empty()) {
    _this->_internal_set_package_name(from._internal_package_name());
  }
  if (!from._internal_package_version().empty()) {
    _this->_internal_set_package_version(from._internal_package_version());
  }
  if (!from._internal_platform().empty()) {
    _this->_internal_set_platform(from._internal_platform());
  }
  if (!from._internal_generator_identity().empty()) {
    _this->_internal_set_generator_identity(from._internal_generator_identity());
  }
  if (from._internal_has_source_digest()) {
    _this->_internal_mutable_source_digest()->::rl::common::v1::ContentDigest::MergeFrom(
        from._internal_source_digest());
  }
  if (from._internal_has_artifact_digest()) {
    _this->_internal_mutable_artifact_digest()->::rl::common::v1::ContentDigest::MergeFrom(
        from._internal_artifact_digest());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ContractIdentity::CopyFrom(const ContractIdentity& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rl.common.v1.ContractIdentity)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ContractIdentity::IsInitialized() const {
  return true;
}

void ContractIdentity::InternalSwap(ContractIdentity* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.package_name_, lhs_arena,
      &other->_impl_.package_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.package_version_, lhs_arena,
      &other->_impl_.package_version_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.platform_, lhs_arena,
      &other->_impl_.platform_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.generator_identity_, lhs_arena,
      &other->_impl_.generator_identity_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ContractIdentity, _impl_.artifact_digest_)
      + sizeof(ContractIdentity::_impl_.artifact_digest_)
      - PROTOBUF_FIELD_OFFSET(ContractIdentity, _impl_.source_digest_)>(
          reinterpret_cast<char*>(&_impl_.source_digest_),
          reinterpret_cast<char*>(&other->_impl_.source_digest_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ContractIdentity::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_common_2eproto_getter, &descriptor_table_common_2eproto_once,
      file_level_metadata_common_2eproto[1]);
}

// ===================================================================

class SchemaIdentity::_Internal {
 public:
  static const ::rl::common::v1::ContentDigest& canonical_digest(const SchemaIdentity* msg);
};

const ::rl::common::v1::ContentDigest&
SchemaIdentity::_Internal::canonical_digest(const SchemaIdentity* msg) {
  return *msg->_impl_.canonical_digest_;
}
SchemaIdentity::SchemaIdentity(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:rl.common.v1.SchemaIdentity)
}
SchemaIdentity::SchemaIdentity(const SchemaIdentity& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SchemaIdentity* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.schema_id_){}
    , decltype(_impl_.canonical_digest_){nullptr}
    , decltype(_impl_.schema_version_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.schema_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.schema_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_schema_id().empty()) {
    _this->_impl_.schema_id_.Set(from._internal_schema_id(),
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_canonical_digest()) {
    _this->_impl_.canonical_digest_ = new ::rl::common::v1::ContentDigest(*from._impl_.canonical_digest_);
  }
  _this->_impl_.schema_version_ = from._impl_.schema_version_;
  // @@protoc_insertion_point(copy_constructor:rl.common.v1.SchemaIdentity)
}

inline void SchemaIdentity::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.schema_id_){}
    , decltype(_impl_.canonical_digest_){nullptr}
    , decltype(_impl_.schema_version_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.schema_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.schema_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SchemaIdentity::~SchemaIdentity() {
  // @@protoc_insertion_point(destructor:rl.common.v1.SchemaIdentity)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SchemaIdentity::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.schema_id_.Destroy();
  if (this != internal_default_instance()) delete _impl_.canonical_digest_;
}

void SchemaIdentity::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SchemaIdentity::Clear() {
// @@protoc_insertion_point(message_clear_start:rl.common.v1.SchemaIdentity)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.schema_id_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.canonical_digest_ != nullptr) {
    delete _impl_.canonical_digest_;
  }
  _impl_.canonical_digest_ = nullptr;
  _impl_.schema_version_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SchemaIdentity::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string schema_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_schema_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "rl.common.v1.SchemaIdentity.schema_id"));
        } else
          goto handle_unusual;
        continue;
      // uint32 schema_version = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.schema_version_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .rl.common.v1.ContentDigest canonical_digest = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_canonical_digest(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SchemaIdentity::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rl.common.v1.SchemaIdentity)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string schema_id = 1;
  if (!this->_internal_schema_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_schema_id().data(), static_cast<int>(this->_internal_schema_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "rl.common.v1.SchemaIdentity.schema_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_schema_id(), target);
  }

  // uint32 schema_version = 2;
  if (this->_internal_schema_version() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_schema_version(), target);
  }

  // .rl.common.v1.ContentDigest canonical_digest = 3;
  if (this->_internal_has_canonical_digest()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::canonical_digest(this),
        _Internal::canonical_digest(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rl.common.v1.SchemaIdentity)
  return target;
}

size_t SchemaIdentity::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rl.common.v1.SchemaIdentity)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string schema_id = 1;
  if (!this->_internal_schema_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_schema_id());
  }

  // .rl.common.v1.ContentDigest canonical_digest = 3;
  if (this->_internal_has_canonical_digest()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.canonical_digest_);
  }

  // uint32 schema_version = 2;
  if (this->_internal_schema_version() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_schema_version());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SchemaIdentity::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SchemaIdentity::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SchemaIdentity::GetClassData() const { return &_class_data_; }


void SchemaIdentity::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SchemaIdentity*>(&to_msg);
  auto& from = static_cast<const SchemaIdentity&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rl.common.v1.SchemaIdentity)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_schema_id().empty()) {
    _this->_internal_set_schema_id(from._internal_schema_id());
  }
  if (from._internal_has_canonical_digest()) {
    _this->_internal_mutable_canonical_digest()->::rl::common::v1::ContentDigest::MergeFrom(
        from._internal_canonical_digest());
  }
  if (from._internal_schema_version() != 0) {
    _this->_internal_set_schema_version(from._internal_schema_version());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SchemaIdentity::CopyFrom(const SchemaIdentity& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rl.common.v1.SchemaIdentity)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SchemaIdentity::IsInitialized() const {
  return true;
}

void SchemaIdentity::InternalSwap(SchemaIdentity* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.schema_id_, lhs_arena,
      &other->_impl_.schema_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SchemaIdentity, _impl_.schema_version_)
      + sizeof(SchemaIdentity::_impl_.schema_version_)
      - PROTOBUF_FIELD_OFFSET(SchemaIdentity, _impl_.canonical_digest_)>(
          reinterpret_cast<char*>(&_impl_.canonical_digest_),
          reinterpret_cast<char*>(&other->_impl_.canonical_digest_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SchemaIdentity::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_common_2eproto_getter, &descriptor_table_common_2eproto_once,
      file_level_metadata_common_2eproto[2]);
}

// ===================================================================

class ServiceInstanceIdentity::_Internal {
 public:
};

ServiceInstanceIdentity::ServiceInstanceIdentity(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:rl.common.v1.ServiceInstanceIdentity)
}
ServiceInstanceIdentity::ServiceInstanceIdentity(const ServiceInstanceIdentity& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ServiceInstanceIdentity* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.component_){}
    , decltype(_impl_.instance_id_){}
    , decltype(_impl_.lifecycle_epoch_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.component_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.component_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_component().empty()) {
    _this->_impl_.component_.Set(from._internal_component(),
      _this->GetArenaForAllocation());
  }
  _impl_.instance_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.instance_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_instance_id().empty()) {
    _this->_impl_.instance_id_.Set(from._internal_instance_id(),
      _this->GetArenaForAllocation());
  }
  _this->_impl_.lifecycle_epoch_ = from._impl_.lifecycle_epoch_;
  // @@protoc_insertion_point(copy_constructor:rl.common.v1.ServiceInstanceIdentity)
}

inline void ServiceInstanceIdentity::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.component_){}
    , decltype(_impl_.instance_id_){}
    , decltype(_impl_.lifecycle_epoch_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.component_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.component_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.instance_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.instance_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ServiceInstanceIdentity::~ServiceInstanceIdentity() {
  // @@protoc_insertion_point(destructor:rl.common.v1.ServiceInstanceIdentity)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ServiceInstanceIdentity::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.component_.Destroy();
  _impl_.instance_id_.Destroy();
}

void ServiceInstanceIdentity::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ServiceInstanceIdentity::Clear() {
// @@protoc_insertion_point(message_clear_start:rl.common.v1.ServiceInstanceIdentity)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.component_.ClearToEmpty();
  _impl_.instance_id_.ClearToEmpty();
  _impl_.lifecycle_epoch_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ServiceInstanceIdentity::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string component = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_component();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "rl.common.v1.ServiceInstanceIdentity.component"));
        } else
          goto handle_unusual;
        continue;
      // string instance_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_instance_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "rl.common.v1.ServiceInstanceIdentity.instance_id"));
        } else
          goto handle_unusual;
        continue;
      // uint64 lifecycle_epoch = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.lifecycle_epoch_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ServiceInstanceIdentity::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rl.common.v1.ServiceInstanceIdentity)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string component = 1;
  if (!this->_internal_component().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_component().data(), static_cast<int>(this->_internal_component().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "rl.common.v1.ServiceInstanceIdentity.component");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_component(), target);
  }

  // string instance_id = 2;
  if (!this->_internal_instance_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_instance_id().data(), static_cast<int>(this->_internal_instance_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "rl.common.v1.ServiceInstanceIdentity.instance_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_instance_id(), target);
  }

  // uint64 lifecycle_epoch = 3;
  if (this->_internal_lifecycle_epoch() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_lifecycle_epoch(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rl.common.v1.ServiceInstanceIdentity)
  return target;
}

size_t ServiceInstanceIdentity::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rl.common.v1.ServiceInstanceIdentity)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string component = 1;
  if (!this->_internal_component().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_component());
  }

  // string instance_id = 2;
  if (!this->_internal_instance_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_instance_id());
  }

  // uint64 lifecycle_epoch = 3;
  if (this->_internal_lifecycle_epoch() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_lifecycle_epoch());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ServiceInstanceIdentity::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ServiceInstanceIdentity::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ServiceInstanceIdentity::GetClassData() const { return &_class_data_; }


void ServiceInstanceIdentity::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ServiceInstanceIdentity*>(&to_msg);
  auto& from = static_cast<const ServiceInstanceIdentity&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rl.common.v1.ServiceInstanceIdentity)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_component().empty()) {
    _this->_internal_set_component(from._internal_component());
  }
  if (!from._internal_instance_id().empty()) {
    _this->_internal_set_instance_id(from._internal_instance_id());
  }
  if (from._internal_lifecycle_epoch() != 0) {
    _this->_internal_set_lifecycle_epoch(from._internal_lifecycle_epoch());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ServiceInstanceIdentity::CopyFrom(const ServiceInstanceIdentity& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rl.common.v1.ServiceInstanceIdentity)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ServiceInstanceIdentity::IsInitialized() const {
  return true;
}

void ServiceInstanceIdentity::InternalSwap(ServiceInstanceIdentity* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.component_, lhs_arena,
      &other->_impl_.component_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.instance_id_, lhs_arena,
      &other->_impl_.instance_id_, rhs_arena
  );
  swap(_impl_.lifecycle_epoch_, other->_impl_.lifecycle_epoch_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ServiceInstanceIdentity::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_common_2eproto_getter, &descriptor_table_common_2eproto_once,
      file_level_metadata_common_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace common
}  // namespace rl
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::rl::common::v1::ContentDigest*
Arena::CreateMaybeMessage< ::rl::common::v1::ContentDigest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rl::common::v1::ContentDigest >(arena);
}
template<> PROTOBUF_NOINLINE ::rl::common::v1::ContractIdentity*
Arena::CreateMaybeMessage< ::rl::common::v1::ContractIdentity >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rl::common::v1::ContractIdentity >(arena);
}
template<> PROTOBUF_NOINLINE ::rl::common::v1::SchemaIdentity*
Arena::CreateMaybeMessage< ::rl::common::v1::SchemaIdentity >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rl::common::v1::SchemaIdentity >(arena);
}
template<> PROTOBUF_NOINLINE ::rl::common::v1::ServiceInstanceIdentity*
Arena::CreateMaybeMessage< ::rl::common::v1::ServiceInstanceIdentity >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rl::common::v1::ServiceInstanceIdentity >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
