// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_common_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_common_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_common_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_common_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_common_2eproto;
namespace rl {
namespace common {
namespace v1 {
class ContentDigest;
struct ContentDigestDefaultTypeInternal;
extern ContentDigestDefaultTypeInternal _ContentDigest_default_instance_;
class ContractIdentity;
struct ContractIdentityDefaultTypeInternal;
extern ContractIdentityDefaultTypeInternal _ContractIdentity_default_instance_;
class SchemaIdentity;
struct SchemaIdentityDefaultTypeInternal;
extern SchemaIdentityDefaultTypeInternal _SchemaIdentity_default_instance_;
class ServiceInstanceIdentity;
struct ServiceInstanceIdentityDefaultTypeInternal;
extern ServiceInstanceIdentityDefaultTypeInternal _ServiceInstanceIdentity_default_instance_;
}  // namespace v1
}  // namespace common
}  // namespace rl
PROTOBUF_NAMESPACE_OPEN
template<> ::rl::common::v1::ContentDigest* Arena::CreateMaybeMessage<::rl::common::v1::ContentDigest>(Arena*);
template<> ::rl::common::v1::ContractIdentity* Arena::CreateMaybeMessage<::rl::common::v1::ContractIdentity>(Arena*);
template<> ::rl::common::v1::SchemaIdentity* Arena::CreateMaybeMessage<::rl::common::v1::SchemaIdentity>(Arena*);
template<> ::rl::common::v1::ServiceInstanceIdentity* Arena::CreateMaybeMessage<::rl::common::v1::ServiceInstanceIdentity>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace rl {
namespace common {
namespace v1 {

enum OperationResult : int {
  OPERATION_RESULT_UNSPECIFIED = 0,
  OPERATION_RESULT_APPLIED = 1,
  OPERATION_RESULT_ALREADY_APPLIED = 2,
  OPERATION_RESULT_REJECTED = 3,
  OperationResult_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  OperationResult_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool OperationResult_IsValid(int value);
constexpr OperationResult OperationResult_MIN = OPERATION_RESULT_UNSPECIFIED;
constexpr OperationResult OperationResult_MAX = OPERATION_RESULT_REJECTED;
constexpr int OperationResult_ARRAYSIZE = OperationResult_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* OperationResult_descriptor();
template<typename T>
inline const std::string& OperationResult_Name(T enum_t_value) {
  static_assert(::std::is_same<T, OperationResult>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function OperationResult_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    OperationResult_descriptor(), enum_t_value);
}
inline bool OperationResult_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, OperationResult* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<OperationResult>(
    OperationResult_descriptor(), name, value);
}
enum DigestAlgorithm : int {
  DIGEST_ALGORITHM_UNSPECIFIED = 0,
  DIGEST_ALGORITHM_SHA256 = 1,
  DigestAlgorithm_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  DigestAlgorithm_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool DigestAlgorithm_IsValid(int value);
constexpr DigestAlgorithm DigestAlgorithm_MIN = DIGEST_ALGORITHM_UNSPECIFIED;
constexpr DigestAlgorithm DigestAlgorithm_MAX = DIGEST_ALGORITHM_SHA256;
constexpr int DigestAlgorithm_ARRAYSIZE = DigestAlgorithm_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DigestAlgorithm_descriptor();
template<typename T>
inline const std::string& DigestAlgorithm_Name(T enum_t_value) {
  static_assert(::std::is_same<T, DigestAlgorithm>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function DigestAlgorithm_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DigestAlgorithm_descriptor(), enum_t_value);
}
inline bool DigestAlgorithm_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, DigestAlgorithm* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DigestAlgorithm>(
    DigestAlgorithm_descriptor(), name, value);
}
// ===================================================================

class ContentDigest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rl.common.v1.ContentDigest) */ {
 public:
  inline ContentDigest() : ContentDigest(nullptr) {}
  ~ContentDigest() override;
  explicit PROTOBUF_CONSTEXPR ContentDigest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ContentDigest(const ContentDigest& from);
  ContentDigest(ContentDigest&& from) noexcept
    : ContentDigest() {
    *this = ::std::move(from);
  }

  inline ContentDigest& operator=(const ContentDigest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ContentDigest& operator=(ContentDigest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ContentDigest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ContentDigest* internal_default_instance() {
    return reinterpret_cast<const ContentDigest*>(
               &_ContentDigest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ContentDigest& a, ContentDigest& b) {
    a.Swap(&b);
  }
  inline void Swap(ContentDigest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ContentDigest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ContentDigest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ContentDigest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ContentDigest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ContentDigest& from) {
    ContentDigest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ContentDigest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rl.common.v1.ContentDigest";
  }
  protected:
  explicit ContentDigest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHexFieldNumber = 2,
    kAlgorithmFieldNumber = 1,
  };
  // string hex = 2;
  void clear_hex();
  const std::string& hex() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_hex(ArgT0&& arg0, ArgT... args);
  std::string* mutable_hex();
  PROTOBUF_NODISCARD std::string* release_hex();
  void set_allocated_hex(std::string* hex);
  private:
  const std::string& _internal_hex() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_hex(const std::string& value);
  std::string* _internal_mutable_hex();
  public:

  // .rl.common.v1.DigestAlgorithm algorithm = 1;
  void clear_algorithm();
  ::rl::common::v1::DigestAlgorithm algorithm() const;
  void set_algorithm(::rl::common::v1::DigestAlgorithm value);
  private:
  ::rl::common::v1::DigestAlgorithm _internal_algorithm() const;
  void _internal_set_algorithm(::rl::common::v1::DigestAlgorithm value);
  public:

  // @@protoc_insertion_point(class_scope:rl.common.v1.ContentDigest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr hex_;
    int algorithm_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_common_2eproto;
};
// -------------------------------------------------------------------

class ContractIdentity final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rl.common.v1.ContractIdentity) */ {
 public:
  inline ContractIdentity() : ContractIdentity(nullptr) {}
  ~ContractIdentity() override;
  explicit PROTOBUF_CONSTEXPR ContractIdentity(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ContractIdentity(const ContractIdentity& from);
  ContractIdentity(ContractIdentity&& from) noexcept
    : ContractIdentity() {
    *this = ::std::move(from);
  }

  inline ContractIdentity& operator=(const ContractIdentity& from) {
    CopyFrom(from);
    return *this;
  }
  inline ContractIdentity& operator=(ContractIdentity&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ContractIdentity& default_instance() {
    return *internal_default_instance();
  }
  static inline const ContractIdentity* internal_default_instance() {
    return reinterpret_cast<const ContractIdentity*>(
               &_ContractIdentity_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ContractIdentity& a, ContractIdentity& b) {
    a.Swap(&b);
  }
  inline void Swap(ContractIdentity* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ContractIdentity* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ContractIdentity* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ContractIdentity>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ContractIdentity& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ContractIdentity& from) {
    ContractIdentity::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ContractIdentity* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rl.common.v1.ContractIdentity";
  }
  protected:
  explicit ContractIdentity(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPackageNameFieldNumber = 1,
    kPackageVersionFieldNumber = 2,
    kPlatformFieldNumber = 5,
    kGeneratorIdentityFieldNumber = 6,
    kSourceDigestFieldNumber = 3,
    kArtifactDigestFieldNumber = 4,
  };
  // string package_name = 1;
  void clear_package_name();
  const std::string& package_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_package_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_package_name();
  PROTOBUF_NODISCARD std::string* release_package_name();
  void set_allocated_package_name(std::string* package_name);
  private:
  const std::string& _internal_package_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_package_name(const std::string& value);
  std::string* _internal_mutable_package_name();
  public:

  // string package_version = 2;
  void clear_package_version();
  const std::string& package_version() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_package_version(ArgT0&& arg0, ArgT... args);
  std::string* mutable_package_version();
  PROTOBUF_NODISCARD std::string* release_package_version();
  void set_allocated_package_version(std::string* package_version);
  private:
  const std::string& _internal_package_version() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_package_version(const std::string& value);
  std::string* _internal_mutable_package_version();
  public:

  // string platform = 5;
  void clear_platform();
  const std::string& platform() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_platform(ArgT0&& arg0, ArgT... args);
  std::string* mutable_platform();
  PROTOBUF_NODISCARD std::string* release_platform();
  void set_allocated_platform(std::string* platform);
  private:
  const std::string& _internal_platform() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_platform(const std::string& value);
  std::string* _internal_mutable_platform();
  public:

  // string generator_identity = 6;
  void clear_generator_identity();
  const std::string& generator_identity() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_generator_identity(ArgT0&& arg0, ArgT... args);
  std::string* mutable_generator_identity();
  PROTOBUF_NODISCARD std::string* release_generator_identity();
  void set_allocated_generator_identity(std::string* generator_identity);
  private:
  const std::string& _internal_generator_identity() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_generator_identity(const std::string& value);
  std::string* _internal_mutable_generator_identity();
  public:

  // .rl.common.v1.ContentDigest source_digest = 3;
  bool has_source_digest() const;
  private:
  bool _internal_has_source_digest() const;
  public:
  void clear_source_digest();
  const ::rl::common::v1::ContentDigest& source_digest() const;
  PROTOBUF_NODISCARD ::rl::common::v1::ContentDigest* release_source_digest();
  ::rl::common::v1::ContentDigest* mutable_source_digest();
  void set_allocated_source_digest(::rl::common::v1::ContentDigest* source_digest);
  private:
  const ::rl::common::v1::ContentDigest& _internal_source_digest() const;
  ::rl::common::v1::ContentDigest* _internal_mutable_source_digest();
  public:
  void unsafe_arena_set_allocated_source_digest(
      ::rl::common::v1::ContentDigest* source_digest);
  ::rl::common::v1::ContentDigest* unsafe_arena_release_source_digest();

  // .rl.common.v1.ContentDigest artifact_digest = 4;
  bool has_artifact_digest() const;
  private:
  bool _internal_has_artifact_digest() const;
  public:
  void clear_artifact_digest();
  const ::rl::common::v1::ContentDigest& artifact_digest() const;
  PROTOBUF_NODISCARD ::rl::common::v1::ContentDigest* release_artifact_digest();
  ::rl::common::v1::ContentDigest* mutable_artifact_digest();
  void set_allocated_artifact_digest(::rl::common::v1::ContentDigest* artifact_digest);
  private:
  const ::rl::common::v1::ContentDigest& _internal_artifact_digest() const;
  ::rl::common::v1::ContentDigest* _internal_mutable_artifact_digest();
  public:
  void unsafe_arena_set_allocated_artifact_digest(
      ::rl::common::v1::ContentDigest* artifact_digest);
  ::rl::common::v1::ContentDigest* unsafe_arena_release_artifact_digest();

  // @@protoc_insertion_point(class_scope:rl.common.v1.ContractIdentity)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr package_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr package_version_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr platform_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr generator_identity_;
    ::rl::common::v1::ContentDigest* source_digest_;
    ::rl::common::v1::ContentDigest* artifact_digest_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_common_2eproto;
};
// -------------------------------------------------------------------

class SchemaIdentity final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rl.common.v1.SchemaIdentity) */ {
 public:
  inline SchemaIdentity() : SchemaIdentity(nullptr) {}
  ~SchemaIdentity() override;
  explicit PROTOBUF_CONSTEXPR SchemaIdentity(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SchemaIdentity(const SchemaIdentity& from);
  SchemaIdentity(SchemaIdentity&& from) noexcept
    : SchemaIdentity() {
    *this = ::std::move(from);
  }

  inline SchemaIdentity& operator=(const SchemaIdentity& from) {
    CopyFrom(from);
    return *this;
  }
  inline SchemaIdentity& operator=(SchemaIdentity&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SchemaIdentity& default_instance() {
    return *internal_default_instance();
  }
  static inline const SchemaIdentity* internal_default_instance() {
    return reinterpret_cast<const SchemaIdentity*>(
               &_SchemaIdentity_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(SchemaIdentity& a, SchemaIdentity& b) {
    a.Swap(&b);
  }
  inline void Swap(SchemaIdentity* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SchemaIdentity* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SchemaIdentity* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SchemaIdentity>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SchemaIdentity& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SchemaIdentity& from) {
    SchemaIdentity::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SchemaIdentity* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rl.common.v1.SchemaIdentity";
  }
  protected:
  explicit SchemaIdentity(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSchemaIdFieldNumber = 1,
    kCanonicalDigestFieldNumber = 3,
    kSchemaVersionFieldNumber = 2,
  };
  // string schema_id = 1;
  void clear_schema_id();
  const std::string& schema_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_schema_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_schema_id();
  PROTOBUF_NODISCARD std::string* release_schema_id();
  void set_allocated_schema_id(std::string* schema_id);
  private:
  const std::string& _internal_schema_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_schema_id(const std::string& value);
  std::string* _internal_mutable_schema_id();
  public:

  // .rl.common.v1.ContentDigest canonical_digest = 3;
  bool has_canonical_digest() const;
  private:
  bool _internal_has_canonical_digest() const;
  public:
  void clear_canonical_digest();
  const ::rl::common::v1::ContentDigest& canonical_digest() const;
  PROTOBUF_NODISCARD ::rl::common::v1::ContentDigest* release_canonical_digest();
  ::rl::common::v1::ContentDigest* mutable_canonical_digest();
  void set_allocated_canonical_digest(::rl::common::v1::ContentDigest* canonical_digest);
  private:
  const ::rl::common::v1::ContentDigest& _internal_canonical_digest() const;
  ::rl::common::v1::ContentDigest* _internal_mutable_canonical_digest();
  public:
  void unsafe_arena_set_allocated_canonical_digest(
      ::rl::common::v1::ContentDigest* canonical_digest);
  ::rl::common::v1::ContentDigest* unsafe_arena_release_canonical_digest();

  // uint32 schema_version = 2;
  void clear_schema_version();
  uint32_t schema_version() const;
  void set_schema_version(uint32_t value);
  private:
  uint32_t _internal_schema_version() const;
  void _internal_set_schema_version(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:rl.common.v1.SchemaIdentity)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr schema_id_;
    ::rl::common::v1::ContentDigest* canonical_digest_;
    uint32_t schema_version_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_common_2eproto;
};
// -------------------------------------------------------------------

class ServiceInstanceIdentity final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rl.common.v1.ServiceInstanceIdentity) */ {
 public:
  inline ServiceInstanceIdentity() : ServiceInstanceIdentity(nullptr) {}
  ~ServiceInstanceIdentity() override;
  explicit PROTOBUF_CONSTEXPR ServiceInstanceIdentity(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ServiceInstanceIdentity(const ServiceInstanceIdentity& from);
  ServiceInstanceIdentity(ServiceInstanceIdentity&& from) noexcept
    : ServiceInstanceIdentity() {
    *this = ::std::move(from);
  }

  inline ServiceInstanceIdentity& operator=(const ServiceInstanceIdentity& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServiceInstanceIdentity& operator=(ServiceInstanceIdentity&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ServiceInstanceIdentity& default_instance() {
    return *internal_default_instance();
  }
  static inline const ServiceInstanceIdentity* internal_default_instance() {
    return reinterpret_cast<const ServiceInstanceIdentity*>(
               &_ServiceInstanceIdentity_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ServiceInstanceIdentity& a, ServiceInstanceIdentity& b) {
    a.Swap(&b);
  }
  inline void Swap(ServiceInstanceIdentity* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ServiceInstanceIdentity* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ServiceInstanceIdentity* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ServiceInstanceIdentity>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ServiceInstanceIdentity& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ServiceInstanceIdentity& from) {
    ServiceInstanceIdentity::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ServiceInstanceIdentity* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rl.common.v1.ServiceInstanceIdentity";
  }
  protected:
  explicit ServiceInstanceIdentity(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kComponentFieldNumber = 1,
    kInstanceIdFieldNumber = 2,
    kLifecycleEpochFieldNumber = 3,
  };
  // string component = 1;
  void clear_component();
  const std::string& component() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_component(ArgT0&& arg0, ArgT... args);
  std::string* mutable_component();
  PROTOBUF_NODISCARD std::string* release_component();
  void set_allocated_component(std::string* component);
  private:
  const std::string& _internal_component() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_component(const std::string& value);
  std::string* _internal_mutable_component();
  public:

  // string instance_id = 2;
  void clear_instance_id();
  const std::string& instance_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_instance_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_instance_id();
  PROTOBUF_NODISCARD std::string* release_instance_id();
  void set_allocated_instance_id(std::string* instance_id);
  private:
  const std::string& _internal_instance_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_instance_id(const std::string& value);
  std::string* _internal_mutable_instance_id();
  public:

  // uint64 lifecycle_epoch = 3;
  void clear_lifecycle_epoch();
  uint64_t lifecycle_epoch() const;
  void set_lifecycle_epoch(uint64_t value);
  private:
  uint64_t _internal_lifecycle_epoch() const;
  void _internal_set_lifecycle_epoch(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:rl.common.v1.ServiceInstanceIdentity)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr component_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr instance_id_;
    uint64_t lifecycle_epoch_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_common_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ContentDigest

// .rl.common.v1.DigestAlgorithm algorithm = 1;
inline void ContentDigest::clear_algorithm() {
  _impl_.algorithm_ = 0;
}
inline ::rl::common::v1::DigestAlgorithm ContentDigest::_internal_algorithm() const {
  return static_cast< ::rl::common::v1::DigestAlgorithm >(_impl_.algorithm_);
}
inline ::rl::common::v1::DigestAlgorithm ContentDigest::algorithm() const {
  // @@protoc_insertion_point(field_get:rl.common.v1.ContentDigest.algorithm)
  return _internal_algorithm();
}
inline void ContentDigest::_internal_set_algorithm(::rl::common::v1::DigestAlgorithm value) {
  
  _impl_.algorithm_ = value;
}
inline void ContentDigest::set_algorithm(::rl::common::v1::DigestAlgorithm value) {
  _internal_set_algorithm(value);
  // @@protoc_insertion_point(field_set:rl.common.v1.ContentDigest.algorithm)
}

// string hex = 2;
inline void ContentDigest::clear_hex() {
  _impl_.hex_.ClearToEmpty();
}
inline const std::string& ContentDigest::hex() const {
  // @@protoc_insertion_point(field_get:rl.common.v1.ContentDigest.hex)
  return _internal_hex();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ContentDigest::set_hex(ArgT0&& arg0, ArgT... args) {
 
 _impl_.hex_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:rl.common.v1.ContentDigest.hex)
}
inline std::string* ContentDigest::mutable_hex() {
  std::string* _s = _internal_mutable_hex();
  // @@protoc_insertion_point(field_mutable:rl.common.v1.ContentDigest.hex)
  return _s;
}
inline const std::string& ContentDigest::_internal_hex() const {
  return _impl_.hex_.Get();
}
inline void ContentDigest::_internal_set_hex(const std::string& value) {
  
  _impl_.hex_.Set(value, GetArenaForAllocation());
}
inline std::string* ContentDigest::_internal_mutable_hex() {
  
  return _impl_.hex_.Mutable(GetArenaForAllocation());
}
inline std::string* ContentDigest::release_hex() {
  // @@protoc_insertion_point(field_release:rl.common.v1.ContentDigest.hex)
  return _impl_.hex_.Release();
}
inline void ContentDigest::set_allocated_hex(std::string* hex) {
  if (hex != nullptr) {
    
  } else {
    
  }
  _impl_.hex_.SetAllocated(hex, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.hex_.IsDefault()) {
    _impl_.hex_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:rl.common.v1.ContentDigest.hex)
}

// -------------------------------------------------------------------

// ContractIdentity

// string package_name = 1;
inline void ContractIdentity::clear_package_name() {
  _impl_.package_name_.ClearToEmpty();
}
inline const std::string& ContractIdentity::package_name() const {
  // @@protoc_insertion_point(field_get:rl.common.v1.ContractIdentity.package_name)
  return _internal_package_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ContractIdentity::set_package_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.package_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:rl.common.v1.ContractIdentity.package_name)
}
inline std::string* ContractIdentity::mutable_package_name() {
  std::string* _s = _internal_mutable_package_name();
  // @@protoc_insertion_point(field_mutable:rl.common.v1.ContractIdentity.package_name)
  return _s;
}
inline const std::string& ContractIdentity::_internal_package_name() const {
  return _impl_.package_name_.Get();
}
inline void ContractIdentity::_internal_set_package_name(const std::string& value) {
  
  _impl_.package_name_.Set(value, GetArenaForAllocation());
}
inline std::string* ContractIdentity::_internal_mutable_package_name() {
  
  return _impl_.package_name_.Mutable(GetArenaForAllocation());
}
inline std::string* ContractIdentity::release_package_name() {
  // @@protoc_insertion_point(field_release:rl.common.v1.ContractIdentity.package_name)
  return _impl_.package_name_.Release();
}
inline void ContractIdentity::set_allocated_package_name(std::string* package_name) {
  if (package_name != nullptr) {
    
  } else {
    
  }
  _impl_.package_name_.SetAllocated(package_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.package_name_.IsDefault()) {
    _impl_.package_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:rl.common.v1.ContractIdentity.package_name)
}

// string package_version = 2;
inline void ContractIdentity::clear_package_version() {
  _impl_.package_version_.ClearToEmpty();
}
inline const std::string& ContractIdentity::package_version() const {
  // @@protoc_insertion_point(field_get:rl.common.v1.ContractIdentity.package_version)
  return _internal_package_version();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ContractIdentity::set_package_version(ArgT0&& arg0, ArgT... args) {
 
 _impl_.package_version_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:rl.common.v1.ContractIdentity.package_version)
}
inline std::string* ContractIdentity::mutable_package_version() {
  std::string* _s = _internal_mutable_package_version();
  // @@protoc_insertion_point(field_mutable:rl.common.v1.ContractIdentity.package_version)
  return _s;
}
inline const std::string& ContractIdentity::_internal_package_version() const {
  return _impl_.package_version_.Get();
}
inline void ContractIdentity::_internal_set_package_version(const std::string& value) {
  
  _impl_.package_version_.Set(value, GetArenaForAllocation());
}
inline std::string* ContractIdentity::_internal_mutable_package_version() {
  
  return _impl_.package_version_.Mutable(GetArenaForAllocation());
}
inline std::string* ContractIdentity::release_package_version() {
  // @@protoc_insertion_point(field_release:rl.common.v1.ContractIdentity.package_version)
  return _impl_.package_version_.Release();
}
inline void ContractIdentity::set_allocated_package_version(std::string* package_version) {
  if (package_version != nullptr) {
    
  } else {
    
  }
  _impl_.package_version_.SetAllocated(package_version, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.package_version_.IsDefault()) {
    _impl_.package_version_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:rl.common.v1.ContractIdentity.package_version)
}

// .rl.common.v1.ContentDigest source_digest = 3;
inline bool ContractIdentity::_internal_has_source_digest() const {
  return this != internal_default_instance() && _impl_.source_digest_ != nullptr;
}
inline bool ContractIdentity::has_source_digest() const {
  return _internal_has_source_digest();
}
inline void ContractIdentity::clear_source_digest() {
  if (GetArenaForAllocation() == nullptr && _impl_.source_digest_ != nullptr) {
    delete _impl_.source_digest_;
  }
  _impl_.source_digest_ = nullptr;
}
inline const ::rl::common::v1::ContentDigest& ContractIdentity::_internal_source_digest() const {
  const ::rl::common::v1::ContentDigest* p = _impl_.source_digest_;
  return p != nullptr ? *p : reinterpret_cast<const ::rl::common::v1::ContentDigest&>(
      ::rl::common::v1::_ContentDigest_default_instance_);
}
inline const ::rl::common::v1::ContentDigest& ContractIdentity::source_digest() const {
  // @@protoc_insertion_point(field_get:rl.common.v1.ContractIdentity.source_digest)
  return _internal_source_digest();
}
inline void ContractIdentity::unsafe_arena_set_allocated_source_digest(
    ::rl::common::v1::ContentDigest* source_digest) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.source_digest_);
  }
  _impl_.source_digest_ = source_digest;
  if (source_digest) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:rl.common.v1.ContractIdentity.source_digest)
}
inline ::rl::common::v1::ContentDigest* ContractIdentity::release_source_digest() {
  
  ::rl::common::v1::ContentDigest* temp = _impl_.source_digest_;
  _impl_.source_digest_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::rl::common::v1::ContentDigest* ContractIdentity::unsafe_arena_release_source_digest() {
  // @@protoc_insertion_point(field_release:rl.common.v1.ContractIdentity.source_digest)
  
  ::rl::common::v1::ContentDigest* temp = _impl_.source_digest_;
  _impl_.source_digest_ = nullptr;
  return temp;
}
inline ::rl::common::v1::ContentDigest* ContractIdentity::_internal_mutable_source_digest() {
  
  if (_impl_.source_digest_ == nullptr) {
    auto* p = CreateMaybeMessage<::rl::common::v1::ContentDigest>(GetArenaForAllocation());
    _impl_.source_digest_ = p;
  }
  return _impl_.source_digest_;
}
inline ::rl::common::v1::ContentDigest* ContractIdentity::mutable_source_digest() {
  ::rl::common::v1::ContentDigest* _msg = _internal_mutable_source_digest();
  // @@protoc_insertion_point(field_mutable:rl.common.v1.ContractIdentity.source_digest)
  return _msg;
}
inline void ContractIdentity::set_allocated_source_digest(::rl::common::v1::ContentDigest* source_digest) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.source_digest_;
  }
  if (source_digest) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(source_digest);
    if (message_arena != submessage_arena) {
      source_digest = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, source_digest, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.source_digest_ = source_digest;
  // @@protoc_insertion_point(field_set_allocated:rl.common.v1.ContractIdentity.source_digest)
}

// .rl.common.v1.ContentDigest artifact_digest = 4;
inline bool ContractIdentity::_internal_has_artifact_digest() const {
  return this != internal_default_instance() && _impl_.artifact_digest_ != nullptr;
}
inline bool ContractIdentity::has_artifact_digest() const {
  return _internal_has_artifact_digest();
}
inline void ContractIdentity::clear_artifact_digest() {
  if (GetArenaForAllocation() == nullptr && _impl_.artifact_digest_ != nullptr) {
    delete _impl_.artifact_digest_;
  }
  _impl_.artifact_digest_ = nullptr;
}
inline const ::rl::common::v1::ContentDigest& ContractIdentity::_internal_artifact_digest() const {
  const ::rl::common::v1::ContentDigest* p = _impl_.artifact_digest_;
  return p != nullptr ? *p : reinterpret_cast<const ::rl::common::v1::ContentDigest&>(
      ::rl::common::v1::_ContentDigest_default_instance_);
}
inline const ::rl::common::v1::ContentDigest& ContractIdentity::artifact_digest() const {
  // @@protoc_insertion_point(field_get:rl.common.v1.ContractIdentity.artifact_digest)
  return _internal_artifact_digest();
}
inline void ContractIdentity::unsafe_arena_set_allocated_artifact_digest(
    ::rl::common::v1::ContentDigest* artifact_digest) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.artifact_digest_);
  }
  _impl_.artifact_digest_ = artifact_digest;
  if (artifact_digest) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:rl.common.v1.ContractIdentity.artifact_digest)
}
inline ::rl::common::v1::ContentDigest* ContractIdentity::release_artifact_digest() {
  
  ::rl::common::v1::ContentDigest* temp = _impl_.artifact_digest_;
  _impl_.artifact_digest_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::rl::common::v1::ContentDigest* ContractIdentity::unsafe_arena_release_artifact_digest() {
  // @@protoc_insertion_point(field_release:rl.common.v1.ContractIdentity.artifact_digest)
  
  ::rl::common::v1::ContentDigest* temp = _impl_.artifact_digest_;
  _impl_.artifact_digest_ = nullptr;
  return temp;
}
inline ::rl::common::v1::ContentDigest* ContractIdentity::_internal_mutable_artifact_digest() {
  
  if (_impl_.artifact_digest_ == nullptr) {
    auto* p = CreateMaybeMessage<::rl::common::v1::ContentDigest>(GetArenaForAllocation());
    _impl_.artifact_digest_ = p;
  }
  return _impl_.artifact_digest_;
}
inline ::rl::common::v1::ContentDigest* ContractIdentity::mutable_artifact_digest() {
  ::rl::common::v1::ContentDigest* _msg = _internal_mutable_artifact_digest();
  // @@protoc_insertion_point(field_mutable:rl.common.v1.ContractIdentity.artifact_digest)
  return _msg;
}
inline void ContractIdentity::set_allocated_artifact_digest(::rl::common::v1::ContentDigest* artifact_digest) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.artifact_digest_;
  }
  if (artifact_digest) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(artifact_digest);
    if (message_arena != submessage_arena) {
      artifact_digest = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, artifact_digest, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.artifact_digest_ = artifact_digest;
  // @@protoc_insertion_point(field_set_allocated:rl.common.v1.ContractIdentity.artifact_digest)
}

// string platform = 5;
inline void ContractIdentity::clear_platform() {
  _impl_.platform_.ClearToEmpty();
}
inline const std::string& ContractIdentity::platform() const {
  // @@protoc_insertion_point(field_get:rl.common.v1.ContractIdentity.platform)
  return _internal_platform();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ContractIdentity::set_platform(ArgT0&& arg0, ArgT... args) {
 
 _impl_.platform_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:rl.common.v1.ContractIdentity.platform)
}
inline std::string* ContractIdentity::mutable_platform() {
  std::string* _s = _internal_mutable_platform();
  // @@protoc_insertion_point(field_mutable:rl.common.v1.ContractIdentity.platform)
  return _s;
}
inline const std::string& ContractIdentity::_internal_platform() const {
  return _impl_.platform_.Get();
}
inline void ContractIdentity::_internal_set_platform(const std::string& value) {
  
  _impl_.platform_.Set(value, GetArenaForAllocation());
}
inline std::string* ContractIdentity::_internal_mutable_platform() {
  
  return _impl_.platform_.Mutable(GetArenaForAllocation());
}
inline std::string* ContractIdentity::release_platform() {
  // @@protoc_insertion_point(field_release:rl.common.v1.ContractIdentity.platform)
  return _impl_.platform_.Release();
}
inline void ContractIdentity::set_allocated_platform(std::string* platform) {
  if (platform != nullptr) {
    
  } else {
    
  }
  _impl_.platform_.SetAllocated(platform, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.platform_.IsDefault()) {
    _impl_.platform_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:rl.common.v1.ContractIdentity.platform)
}

// string generator_identity = 6;
inline void ContractIdentity::clear_generator_identity() {
  _impl_.generator_identity_.ClearToEmpty();
}
inline const std::string& ContractIdentity::generator_identity() const {
  // @@protoc_insertion_point(field_get:rl.common.v1.ContractIdentity.generator_identity)
  return _internal_generator_identity();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ContractIdentity::set_generator_identity(ArgT0&& arg0, ArgT... args) {
 
 _impl_.generator_identity_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:rl.common.v1.ContractIdentity.generator_identity)
}
inline std::string* ContractIdentity::mutable_generator_identity() {
  std::string* _s = _internal_mutable_generator_identity();
  // @@protoc_insertion_point(field_mutable:rl.common.v1.ContractIdentity.generator_identity)
  return _s;
}
inline const std::string& ContractIdentity::_internal_generator_identity() const {
  return _impl_.generator_identity_.Get();
}
inline void ContractIdentity::_internal_set_generator_identity(const std::string& value) {
  
  _impl_.generator_identity_.Set(value, GetArenaForAllocation());
}
inline std::string* ContractIdentity::_internal_mutable_generator_identity() {
  
  return _impl_.generator_identity_.Mutable(GetArenaForAllocation());
}
inline std::string* ContractIdentity::release_generator_identity() {
  // @@protoc_insertion_point(field_release:rl.common.v1.ContractIdentity.generator_identity)
  return _impl_.generator_identity_.Release();
}
inline void ContractIdentity::set_allocated_generator_identity(std::string* generator_identity) {
  if (generator_identity != nullptr) {
    
  } else {
    
  }
  _impl_.generator_identity_.SetAllocated(generator_identity, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.generator_identity_.IsDefault()) {
    _impl_.generator_identity_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:rl.common.v1.ContractIdentity.generator_identity)
}

// -------------------------------------------------------------------

// SchemaIdentity

// string schema_id = 1;
inline void SchemaIdentity::clear_schema_id() {
  _impl_.schema_id_.ClearToEmpty();
}
inline const std::string& SchemaIdentity::schema_id() const {
  // @@protoc_insertion_point(field_get:rl.common.v1.SchemaIdentity.schema_id)
  return _internal_schema_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SchemaIdentity::set_schema_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.schema_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:rl.common.v1.SchemaIdentity.schema_id)
}
inline std::string* SchemaIdentity::mutable_schema_id() {
  std::string* _s = _internal_mutable_schema_id();
  // @@protoc_insertion_point(field_mutable:rl.common.v1.SchemaIdentity.schema_id)
  return _s;
}
inline const std::string& SchemaIdentity::_internal_schema_id() const {
  return _impl_.schema_id_.Get();
}
inline void SchemaIdentity::_internal_set_schema_id(const std::string& value) {
  
  _impl_.schema_id_.Set(value, GetArenaForAllocation());
}
inline std::string* SchemaIdentity::_internal_mutable_schema_id() {
  
  return _impl_.schema_id_.Mutable(GetArenaForAllocation());
}
inline std::string* SchemaIdentity::release_schema_id() {
  // @@protoc_insertion_point(field_release:rl.common.v1.SchemaIdentity.schema_id)
  return _impl_.schema_id_.Release();
}
inline void SchemaIdentity::set_allocated_schema_id(std::string* schema_id) {
  if (schema_id != nullptr) {
    
  } else {
    
  }
  _impl_.schema_id_.SetAllocated(schema_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.schema_id_.IsDefault()) {
    _impl_.schema_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:rl.common.v1.SchemaIdentity.schema_id)
}

// uint32 schema_version = 2;
inline void SchemaIdentity::clear_schema_version() {
  _impl_.schema_version_ = 0u;
}
inline uint32_t SchemaIdentity::_internal_schema_version() const {
  return _impl_.schema_version_;
}
inline uint32_t SchemaIdentity::schema_version() const {
  // @@protoc_insertion_point(field_get:rl.common.v1.SchemaIdentity.schema_version)
  return _internal_schema_version();
}
inline void SchemaIdentity::_internal_set_schema_version(uint32_t value) {
  
  _impl_.schema_version_ = value;
}
inline void SchemaIdentity::set_schema_version(uint32_t value) {
  _internal_set_schema_version(value);
  // @@protoc_insertion_point(field_set:rl.common.v1.SchemaIdentity.schema_version)
}

// .rl.common.v1.ContentDigest canonical_digest = 3;
inline bool SchemaIdentity::_internal_has_canonical_digest() const {
  return this != internal_default_instance() && _impl_.canonical_digest_ != nullptr;
}
inline bool SchemaIdentity::has_canonical_digest() const {
  return _internal_has_canonical_digest();
}
inline void SchemaIdentity::clear_canonical_digest() {
  if (GetArenaForAllocation() == nullptr && _impl_.canonical_digest_ != nullptr) {
    delete _impl_.canonical_digest_;
  }
  _impl_.canonical_digest_ = nullptr;
}
inline const ::rl::common::v1::ContentDigest& SchemaIdentity::_internal_canonical_digest() const {
  const ::rl::common::v1::ContentDigest* p = _impl_.canonical_digest_;
  return p != nullptr ? *p : reinterpret_cast<const ::rl::common::v1::ContentDigest&>(
      ::rl::common::v1::_ContentDigest_default_instance_);
}
inline const ::rl::common::v1::ContentDigest& SchemaIdentity::canonical_digest() const {
  // @@protoc_insertion_point(field_get:rl.common.v1.SchemaIdentity.canonical_digest)
  return _internal_canonical_digest();
}
inline void SchemaIdentity::unsafe_arena_set_allocated_canonical_digest(
    ::rl::common::v1::ContentDigest* canonical_digest) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.canonical_digest_);
  }
  _impl_.canonical_digest_ = canonical_digest;
  if (canonical_digest) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:rl.common.v1.SchemaIdentity.canonical_digest)
}
inline ::rl::common::v1::ContentDigest* SchemaIdentity::release_canonical_digest() {
  
  ::rl::common::v1::ContentDigest* temp = _impl_.canonical_digest_;
  _impl_.canonical_digest_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::rl::common::v1::ContentDigest* SchemaIdentity::unsafe_arena_release_canonical_digest() {
  // @@protoc_insertion_point(field_release:rl.common.v1.SchemaIdentity.canonical_digest)
  
  ::rl::common::v1::ContentDigest* temp = _impl_.canonical_digest_;
  _impl_.canonical_digest_ = nullptr;
  return temp;
}
inline ::rl::common::v1::ContentDigest* SchemaIdentity::_internal_mutable_canonical_digest() {
  
  if (_impl_.canonical_digest_ == nullptr) {
    auto* p = CreateMaybeMessage<::rl::common::v1::ContentDigest>(GetArenaForAllocation());
    _impl_.canonical_digest_ = p;
  }
  return _impl_.canonical_digest_;
}
inline ::rl::common::v1::ContentDigest* SchemaIdentity::mutable_canonical_digest() {
  ::rl::common::v1::ContentDigest* _msg = _internal_mutable_canonical_digest();
  // @@protoc_insertion_point(field_mutable:rl.common.v1.SchemaIdentity.canonical_digest)
  return _msg;
}
inline void SchemaIdentity::set_allocated_canonical_digest(::rl::common::v1::ContentDigest* canonical_digest) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.canonical_digest_;
  }
  if (canonical_digest) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(canonical_digest);
    if (message_arena != submessage_arena) {
      canonical_digest = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, canonical_digest, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.canonical_digest_ = canonical_digest;
  // @@protoc_insertion_point(field_set_allocated:rl.common.v1.SchemaIdentity.canonical_digest)
}

// -------------------------------------------------------------------

// ServiceInstanceIdentity

// string component = 1;
inline void ServiceInstanceIdentity::clear_component() {
  _impl_.component_.ClearToEmpty();
}
inline const std::string& ServiceInstanceIdentity::component() const {
  // @@protoc_insertion_point(field_get:rl.common.v1.ServiceInstanceIdentity.component)
  return _internal_component();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ServiceInstanceIdentity::set_component(ArgT0&& arg0, ArgT... args) {
 
 _impl_.component_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:rl.common.v1.ServiceInstanceIdentity.component)
}
inline std::string* ServiceInstanceIdentity::mutable_component() {
  std::string* _s = _internal_mutable_component();
  // @@protoc_insertion_point(field_mutable:rl.common.v1.ServiceInstanceIdentity.component)
  return _s;
}
inline const std::string& ServiceInstanceIdentity::_internal_component() const {
  return _impl_.component_.Get();
}
inline void ServiceInstanceIdentity::_internal_set_component(const std::string& value) {
  
  _impl_.component_.Set(value, GetArenaForAllocation());
}
inline std::string* ServiceInstanceIdentity::_internal_mutable_component() {
  
  return _impl_.component_.Mutable(GetArenaForAllocation());
}
inline std::string* ServiceInstanceIdentity::release_component() {
  // @@protoc_insertion_point(field_release:rl.common.v1.ServiceInstanceIdentity.component)
  return _impl_.component_.Release();
}
inline void ServiceInstanceIdentity::set_allocated_component(std::string* component) {
  if (component != nullptr) {
    
  } else {
    
  }
  _impl_.component_.SetAllocated(component, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.component_.IsDefault()) {
    _impl_.component_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:rl.common.v1.ServiceInstanceIdentity.component)
}

// string instance_id = 2;
inline void ServiceInstanceIdentity::clear_instance_id() {
  _impl_.instance_id_.ClearToEmpty();
}
inline const std::string& ServiceInstanceIdentity::instance_id() const {
  // @@protoc_insertion_point(field_get:rl.common.v1.ServiceInstanceIdentity.instance_id)
  return _internal_instance_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ServiceInstanceIdentity::set_instance_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.instance_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:rl.common.v1.ServiceInstanceIdentity.instance_id)
}
inline std::string* ServiceInstanceIdentity::mutable_instance_id() {
  std::string* _s = _internal_mutable_instance_id();
  // @@protoc_insertion_point(field_mutable:rl.common.v1.ServiceInstanceIdentity.instance_id)
  return _s;
}
inline const std::string& ServiceInstanceIdentity::_internal_instance_id() const {
  return _impl_.instance_id_.Get();
}
inline void ServiceInstanceIdentity::_internal_set_instance_id(const std::string& value) {
  
  _impl_.instance_id_.Set(value, GetArenaForAllocation());
}
inline std::string* ServiceInstanceIdentity::_internal_mutable_instance_id() {
  
  return _impl_.instance_id_.Mutable(GetArenaForAllocation());
}
inline std::string* ServiceInstanceIdentity::release_instance_id() {
  // @@protoc_insertion_point(field_release:rl.common.v1.ServiceInstanceIdentity.instance_id)
  return _impl_.instance_id_.Release();
}
inline void ServiceInstanceIdentity::set_allocated_instance_id(std::string* instance_id) {
  if (instance_id != nullptr) {
    
  } else {
    
  }
  _impl_.instance_id_.SetAllocated(instance_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.instance_id_.IsDefault()) {
    _impl_.instance_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:rl.common.v1.ServiceInstanceIdentity.instance_id)
}

// uint64 lifecycle_epoch = 3;
inline void ServiceInstanceIdentity::clear_lifecycle_epoch() {
  _impl_.lifecycle_epoch_ = uint64_t{0u};
}
inline uint64_t ServiceInstanceIdentity::_internal_lifecycle_epoch() const {
  return _impl_.lifecycle_epoch_;
}
inline uint64_t ServiceInstanceIdentity::lifecycle_epoch() const {
  // @@protoc_insertion_point(field_get:rl.common.v1.ServiceInstanceIdentity.lifecycle_epoch)
  return _internal_lifecycle_epoch();
}
inline void ServiceInstanceIdentity::_internal_set_lifecycle_epoch(uint64_t value) {
  
  _impl_.lifecycle_epoch_ = value;
}
inline void ServiceInstanceIdentity::set_lifecycle_epoch(uint64_t value) {
  _internal_set_lifecycle_epoch(value);
  // @@protoc_insertion_point(field_set:rl.common.v1.ServiceInstanceIdentity.lifecycle_epoch)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace common
}  // namespace rl

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::rl::common::v1::OperationResult> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::rl::common::v1::OperationResult>() {
  return ::rl::common::v1::OperationResult_descriptor();
}
template <> struct is_proto_enum< ::rl::common::v1::DigestAlgorithm> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::rl::common::v1::DigestAlgorithm>() {
  return ::rl::common::v1::DigestAlgorithm_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_common_2eproto
