// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: training.proto

#include "training.pb.h"
#include "training.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace rl {
namespace training {
namespace v1 {

static const char* AIServerTrainingStatusService_method_names[] = {
  "/rl.training.v1.AIServerTrainingStatusService/GetAIServerStatus",
};

std::unique_ptr< AIServerTrainingStatusService::Stub> AIServerTrainingStatusService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AIServerTrainingStatusService::Stub> stub(new AIServerTrainingStatusService::Stub(channel, options));
  return stub;
}

AIServerTrainingStatusService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetAIServerStatus_(AIServerTrainingStatusService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AIServerTrainingStatusService::Stub::GetAIServerStatus(::grpc::ClientContext* context, const ::rl::training::v1::AIServerStatusReq& request, ::rl::training::v1::AIServerStatusRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rl::training::v1::AIServerStatusReq, ::rl::training::v1::AIServerStatusRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetAIServerStatus_, context, request, response);
}

void AIServerTrainingStatusService::Stub::async::GetAIServerStatus(::grpc::ClientContext* context, const ::rl::training::v1::AIServerStatusReq* request, ::rl::training::v1::AIServerStatusRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rl::training::v1::AIServerStatusReq, ::rl::training::v1::AIServerStatusRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAIServerStatus_, context, request, response, std::move(f));
}

void AIServerTrainingStatusService::Stub::async::GetAIServerStatus(::grpc::ClientContext* context, const ::rl::training::v1::AIServerStatusReq* request, ::rl::training::v1::AIServerStatusRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAIServerStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::AIServerStatusRsp>* AIServerTrainingStatusService::Stub::PrepareAsyncGetAIServerStatusRaw(::grpc::ClientContext* context, const ::rl::training::v1::AIServerStatusReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rl::training::v1::AIServerStatusRsp, ::rl::training::v1::AIServerStatusReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetAIServerStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::AIServerStatusRsp>* AIServerTrainingStatusService::Stub::AsyncGetAIServerStatusRaw(::grpc::ClientContext* context, const ::rl::training::v1::AIServerStatusReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetAIServerStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

AIServerTrainingStatusService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AIServerTrainingStatusService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AIServerTrainingStatusService::Service, ::rl::training::v1::AIServerStatusReq, ::rl::training::v1::AIServerStatusRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AIServerTrainingStatusService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rl::training::v1::AIServerStatusReq* req,
             ::rl::training::v1::AIServerStatusRsp* resp) {
               return service->GetAIServerStatus(ctx, req, resp);
             }, this)));
}

AIServerTrainingStatusService::Service::~Service() {
}

::grpc::Status AIServerTrainingStatusService::Service::GetAIServerStatus(::grpc::ServerContext* context, const ::rl::training::v1::AIServerStatusReq* request, ::rl::training::v1::AIServerStatusRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* LearnerService_method_names[] = {
  "/rl.training.v1.LearnerService/SendSamples",
};

std::unique_ptr< LearnerService::Stub> LearnerService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< LearnerService::Stub> stub(new LearnerService::Stub(channel, options));
  return stub;
}

LearnerService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendSamples_(LearnerService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status LearnerService::Stub::SendSamples(::grpc::ClientContext* context, const ::rl::training::v1::SampleBatch& request, ::rl::training::v1::SampleResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rl::training::v1::SampleBatch, ::rl::training::v1::SampleResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendSamples_, context, request, response);
}

void LearnerService::Stub::async::SendSamples(::grpc::ClientContext* context, const ::rl::training::v1::SampleBatch* request, ::rl::training::v1::SampleResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rl::training::v1::SampleBatch, ::rl::training::v1::SampleResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendSamples_, context, request, response, std::move(f));
}

void LearnerService::Stub::async::SendSamples(::grpc::ClientContext* context, const ::rl::training::v1::SampleBatch* request, ::rl::training::v1::SampleResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendSamples_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::SampleResponse>* LearnerService::Stub::PrepareAsyncSendSamplesRaw(::grpc::ClientContext* context, const ::rl::training::v1::SampleBatch& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rl::training::v1::SampleResponse, ::rl::training::v1::SampleBatch, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendSamples_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::SampleResponse>* LearnerService::Stub::AsyncSendSamplesRaw(::grpc::ClientContext* context, const ::rl::training::v1::SampleBatch& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendSamplesRaw(context, request, cq);
  result->StartCall();
  return result;
}

LearnerService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LearnerService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LearnerService::Service, ::rl::training::v1::SampleBatch, ::rl::training::v1::SampleResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LearnerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rl::training::v1::SampleBatch* req,
             ::rl::training::v1::SampleResponse* resp) {
               return service->SendSamples(ctx, req, resp);
             }, this)));
}

LearnerService::Service::~Service() {
}

::grpc::Status LearnerService::Service::SendSamples(::grpc::ServerContext* context, const ::rl::training::v1::SampleBatch* request, ::rl::training::v1::SampleResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* SampleDistributorService_method_names[] = {
  "/rl.training.v1.SampleDistributorService/UpsertSampleDemand",
  "/rl.training.v1.SampleDistributorService/ReleaseSampleDemand",
  "/rl.training.v1.SampleDistributorService/GetSampleDemandStatus",
  "/rl.training.v1.SampleDistributorService/AcquireSampleCredit",
  "/rl.training.v1.SampleDistributorService/ReleaseSampleCredit",
  "/rl.training.v1.SampleDistributorService/PushSamples",
  "/rl.training.v1.SampleDistributorService/GetBatch",
  "/rl.training.v1.SampleDistributorService/AckBatch",
  "/rl.training.v1.SampleDistributorService/NackBatch",
  "/rl.training.v1.SampleDistributorService/RenewLease",
  "/rl.training.v1.SampleDistributorService/GetStatus",
};

std::unique_ptr< SampleDistributorService::Stub> SampleDistributorService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SampleDistributorService::Stub> stub(new SampleDistributorService::Stub(channel, options));
  return stub;
}

SampleDistributorService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_UpsertSampleDemand_(SampleDistributorService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReleaseSampleDemand_(SampleDistributorService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetSampleDemandStatus_(SampleDistributorService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AcquireSampleCredit_(SampleDistributorService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReleaseSampleCredit_(SampleDistributorService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PushSamples_(SampleDistributorService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetBatch_(SampleDistributorService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AckBatch_(SampleDistributorService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_NackBatch_(SampleDistributorService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RenewLease_(SampleDistributorService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetStatus_(SampleDistributorService_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SampleDistributorService::Stub::UpsertSampleDemand(::grpc::ClientContext* context, const ::rl::training::v1::UpsertSampleDemandReq& request, ::rl::training::v1::SampleDemandRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rl::training::v1::UpsertSampleDemandReq, ::rl::training::v1::SampleDemandRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpsertSampleDemand_, context, request, response);
}

void SampleDistributorService::Stub::async::UpsertSampleDemand(::grpc::ClientContext* context, const ::rl::training::v1::UpsertSampleDemandReq* request, ::rl::training::v1::SampleDemandRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rl::training::v1::UpsertSampleDemandReq, ::rl::training::v1::SampleDemandRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpsertSampleDemand_, context, request, response, std::move(f));
}

void SampleDistributorService::Stub::async::UpsertSampleDemand(::grpc::ClientContext* context, const ::rl::training::v1::UpsertSampleDemandReq* request, ::rl::training::v1::SampleDemandRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpsertSampleDemand_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::SampleDemandRsp>* SampleDistributorService::Stub::PrepareAsyncUpsertSampleDemandRaw(::grpc::ClientContext* context, const ::rl::training::v1::UpsertSampleDemandReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rl::training::v1::SampleDemandRsp, ::rl::training::v1::UpsertSampleDemandReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpsertSampleDemand_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::SampleDemandRsp>* SampleDistributorService::Stub::AsyncUpsertSampleDemandRaw(::grpc::ClientContext* context, const ::rl::training::v1::UpsertSampleDemandReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpsertSampleDemandRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SampleDistributorService::Stub::ReleaseSampleDemand(::grpc::ClientContext* context, const ::rl::training::v1::ReleaseSampleDemandReq& request, ::rl::training::v1::SampleDemandRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rl::training::v1::ReleaseSampleDemandReq, ::rl::training::v1::SampleDemandRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReleaseSampleDemand_, context, request, response);
}

void SampleDistributorService::Stub::async::ReleaseSampleDemand(::grpc::ClientContext* context, const ::rl::training::v1::ReleaseSampleDemandReq* request, ::rl::training::v1::SampleDemandRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rl::training::v1::ReleaseSampleDemandReq, ::rl::training::v1::SampleDemandRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReleaseSampleDemand_, context, request, response, std::move(f));
}

void SampleDistributorService::Stub::async::ReleaseSampleDemand(::grpc::ClientContext* context, const ::rl::training::v1::ReleaseSampleDemandReq* request, ::rl::training::v1::SampleDemandRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReleaseSampleDemand_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::SampleDemandRsp>* SampleDistributorService::Stub::PrepareAsyncReleaseSampleDemandRaw(::grpc::ClientContext* context, const ::rl::training::v1::ReleaseSampleDemandReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rl::training::v1::SampleDemandRsp, ::rl::training::v1::ReleaseSampleDemandReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReleaseSampleDemand_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::SampleDemandRsp>* SampleDistributorService::Stub::AsyncReleaseSampleDemandRaw(::grpc::ClientContext* context, const ::rl::training::v1::ReleaseSampleDemandReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReleaseSampleDemandRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SampleDistributorService::Stub::GetSampleDemandStatus(::grpc::ClientContext* context, const ::rl::training::v1::GetSampleDemandStatusReq& request, ::rl::training::v1::SampleDemandStatusRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rl::training::v1::GetSampleDemandStatusReq, ::rl::training::v1::SampleDemandStatusRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetSampleDemandStatus_, context, request, response);
}

void SampleDistributorService::Stub::async::GetSampleDemandStatus(::grpc::ClientContext* context, const ::rl::training::v1::GetSampleDemandStatusReq* request, ::rl::training::v1::SampleDemandStatusRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rl::training::v1::GetSampleDemandStatusReq, ::rl::training::v1::SampleDemandStatusRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSampleDemandStatus_, context, request, response, std::move(f));
}

void SampleDistributorService::Stub::async::GetSampleDemandStatus(::grpc::ClientContext* context, const ::rl::training::v1::GetSampleDemandStatusReq* request, ::rl::training::v1::SampleDemandStatusRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSampleDemandStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::SampleDemandStatusRsp>* SampleDistributorService::Stub::PrepareAsyncGetSampleDemandStatusRaw(::grpc::ClientContext* context, const ::rl::training::v1::GetSampleDemandStatusReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rl::training::v1::SampleDemandStatusRsp, ::rl::training::v1::GetSampleDemandStatusReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetSampleDemandStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::SampleDemandStatusRsp>* SampleDistributorService::Stub::AsyncGetSampleDemandStatusRaw(::grpc::ClientContext* context, const ::rl::training::v1::GetSampleDemandStatusReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetSampleDemandStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SampleDistributorService::Stub::AcquireSampleCredit(::grpc::ClientContext* context, const ::rl::training::v1::AcquireSampleCreditReq& request, ::rl::training::v1::SampleCreditGrant* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rl::training::v1::AcquireSampleCreditReq, ::rl::training::v1::SampleCreditGrant, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AcquireSampleCredit_, context, request, response);
}

void SampleDistributorService::Stub::async::AcquireSampleCredit(::grpc::ClientContext* context, const ::rl::training::v1::AcquireSampleCreditReq* request, ::rl::training::v1::SampleCreditGrant* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rl::training::v1::AcquireSampleCreditReq, ::rl::training::v1::SampleCreditGrant, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AcquireSampleCredit_, context, request, response, std::move(f));
}

void SampleDistributorService::Stub::async::AcquireSampleCredit(::grpc::ClientContext* context, const ::rl::training::v1::AcquireSampleCreditReq* request, ::rl::training::v1::SampleCreditGrant* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AcquireSampleCredit_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::SampleCreditGrant>* SampleDistributorService::Stub::PrepareAsyncAcquireSampleCreditRaw(::grpc::ClientContext* context, const ::rl::training::v1::AcquireSampleCreditReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rl::training::v1::SampleCreditGrant, ::rl::training::v1::AcquireSampleCreditReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AcquireSampleCredit_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::SampleCreditGrant>* SampleDistributorService::Stub::AsyncAcquireSampleCreditRaw(::grpc::ClientContext* context, const ::rl::training::v1::AcquireSampleCreditReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAcquireSampleCreditRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SampleDistributorService::Stub::ReleaseSampleCredit(::grpc::ClientContext* context, const ::rl::training::v1::ReleaseSampleCreditReq& request, ::rl::training::v1::ReleaseSampleCreditRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rl::training::v1::ReleaseSampleCreditReq, ::rl::training::v1::ReleaseSampleCreditRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReleaseSampleCredit_, context, request, response);
}

void SampleDistributorService::Stub::async::ReleaseSampleCredit(::grpc::ClientContext* context, const ::rl::training::v1::ReleaseSampleCreditReq* request, ::rl::training::v1::ReleaseSampleCreditRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rl::training::v1::ReleaseSampleCreditReq, ::rl::training::v1::ReleaseSampleCreditRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReleaseSampleCredit_, context, request, response, std::move(f));
}

void SampleDistributorService::Stub::async::ReleaseSampleCredit(::grpc::ClientContext* context, const ::rl::training::v1::ReleaseSampleCreditReq* request, ::rl::training::v1::ReleaseSampleCreditRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReleaseSampleCredit_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::ReleaseSampleCreditRsp>* SampleDistributorService::Stub::PrepareAsyncReleaseSampleCreditRaw(::grpc::ClientContext* context, const ::rl::training::v1::ReleaseSampleCreditReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rl::training::v1::ReleaseSampleCreditRsp, ::rl::training::v1::ReleaseSampleCreditReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReleaseSampleCredit_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::ReleaseSampleCreditRsp>* SampleDistributorService::Stub::AsyncReleaseSampleCreditRaw(::grpc::ClientContext* context, const ::rl::training::v1::ReleaseSampleCreditReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReleaseSampleCreditRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SampleDistributorService::Stub::PushSamples(::grpc::ClientContext* context, const ::rl::training::v1::PushSamplesReq& request, ::rl::training::v1::PushSamplesRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rl::training::v1::PushSamplesReq, ::rl::training::v1::PushSamplesRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PushSamples_, context, request, response);
}

void SampleDistributorService::Stub::async::PushSamples(::grpc::ClientContext* context, const ::rl::training::v1::PushSamplesReq* request, ::rl::training::v1::PushSamplesRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rl::training::v1::PushSamplesReq, ::rl::training::v1::PushSamplesRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushSamples_, context, request, response, std::move(f));
}

void SampleDistributorService::Stub::async::PushSamples(::grpc::ClientContext* context, const ::rl::training::v1::PushSamplesReq* request, ::rl::training::v1::PushSamplesRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushSamples_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::PushSamplesRsp>* SampleDistributorService::Stub::PrepareAsyncPushSamplesRaw(::grpc::ClientContext* context, const ::rl::training::v1::PushSamplesReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rl::training::v1::PushSamplesRsp, ::rl::training::v1::PushSamplesReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PushSamples_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::PushSamplesRsp>* SampleDistributorService::Stub::AsyncPushSamplesRaw(::grpc::ClientContext* context, const ::rl::training::v1::PushSamplesReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPushSamplesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SampleDistributorService::Stub::GetBatch(::grpc::ClientContext* context, const ::rl::training::v1::GetBatchReq& request, ::rl::training::v1::GetBatchRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rl::training::v1::GetBatchReq, ::rl::training::v1::GetBatchRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetBatch_, context, request, response);
}

void SampleDistributorService::Stub::async::GetBatch(::grpc::ClientContext* context, const ::rl::training::v1::GetBatchReq* request, ::rl::training::v1::GetBatchRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rl::training::v1::GetBatchReq, ::rl::training::v1::GetBatchRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetBatch_, context, request, response, std::move(f));
}

void SampleDistributorService::Stub::async::GetBatch(::grpc::ClientContext* context, const ::rl::training::v1::GetBatchReq* request, ::rl::training::v1::GetBatchRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetBatch_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::GetBatchRsp>* SampleDistributorService::Stub::PrepareAsyncGetBatchRaw(::grpc::ClientContext* context, const ::rl::training::v1::GetBatchReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rl::training::v1::GetBatchRsp, ::rl::training::v1::GetBatchReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetBatch_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::GetBatchRsp>* SampleDistributorService::Stub::AsyncGetBatchRaw(::grpc::ClientContext* context, const ::rl::training::v1::GetBatchReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetBatchRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SampleDistributorService::Stub::AckBatch(::grpc::ClientContext* context, const ::rl::training::v1::AckBatchReq& request, ::rl::training::v1::DeliveryRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rl::training::v1::AckBatchReq, ::rl::training::v1::DeliveryRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AckBatch_, context, request, response);
}

void SampleDistributorService::Stub::async::AckBatch(::grpc::ClientContext* context, const ::rl::training::v1::AckBatchReq* request, ::rl::training::v1::DeliveryRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rl::training::v1::AckBatchReq, ::rl::training::v1::DeliveryRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AckBatch_, context, request, response, std::move(f));
}

void SampleDistributorService::Stub::async::AckBatch(::grpc::ClientContext* context, const ::rl::training::v1::AckBatchReq* request, ::rl::training::v1::DeliveryRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AckBatch_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::DeliveryRsp>* SampleDistributorService::Stub::PrepareAsyncAckBatchRaw(::grpc::ClientContext* context, const ::rl::training::v1::AckBatchReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rl::training::v1::DeliveryRsp, ::rl::training::v1::AckBatchReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AckBatch_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::DeliveryRsp>* SampleDistributorService::Stub::AsyncAckBatchRaw(::grpc::ClientContext* context, const ::rl::training::v1::AckBatchReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAckBatchRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SampleDistributorService::Stub::NackBatch(::grpc::ClientContext* context, const ::rl::training::v1::NackBatchReq& request, ::rl::training::v1::DeliveryRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rl::training::v1::NackBatchReq, ::rl::training::v1::DeliveryRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_NackBatch_, context, request, response);
}

void SampleDistributorService::Stub::async::NackBatch(::grpc::ClientContext* context, const ::rl::training::v1::NackBatchReq* request, ::rl::training::v1::DeliveryRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rl::training::v1::NackBatchReq, ::rl::training::v1::DeliveryRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NackBatch_, context, request, response, std::move(f));
}

void SampleDistributorService::Stub::async::NackBatch(::grpc::ClientContext* context, const ::rl::training::v1::NackBatchReq* request, ::rl::training::v1::DeliveryRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NackBatch_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::DeliveryRsp>* SampleDistributorService::Stub::PrepareAsyncNackBatchRaw(::grpc::ClientContext* context, const ::rl::training::v1::NackBatchReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rl::training::v1::DeliveryRsp, ::rl::training::v1::NackBatchReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_NackBatch_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::DeliveryRsp>* SampleDistributorService::Stub::AsyncNackBatchRaw(::grpc::ClientContext* context, const ::rl::training::v1::NackBatchReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNackBatchRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SampleDistributorService::Stub::RenewLease(::grpc::ClientContext* context, const ::rl::training::v1::RenewLeaseReq& request, ::rl::training::v1::DeliveryRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rl::training::v1::RenewLeaseReq, ::rl::training::v1::DeliveryRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RenewLease_, context, request, response);
}

void SampleDistributorService::Stub::async::RenewLease(::grpc::ClientContext* context, const ::rl::training::v1::RenewLeaseReq* request, ::rl::training::v1::DeliveryRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rl::training::v1::RenewLeaseReq, ::rl::training::v1::DeliveryRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RenewLease_, context, request, response, std::move(f));
}

void SampleDistributorService::Stub::async::RenewLease(::grpc::ClientContext* context, const ::rl::training::v1::RenewLeaseReq* request, ::rl::training::v1::DeliveryRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RenewLease_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::DeliveryRsp>* SampleDistributorService::Stub::PrepareAsyncRenewLeaseRaw(::grpc::ClientContext* context, const ::rl::training::v1::RenewLeaseReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rl::training::v1::DeliveryRsp, ::rl::training::v1::RenewLeaseReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RenewLease_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::DeliveryRsp>* SampleDistributorService::Stub::AsyncRenewLeaseRaw(::grpc::ClientContext* context, const ::rl::training::v1::RenewLeaseReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRenewLeaseRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SampleDistributorService::Stub::GetStatus(::grpc::ClientContext* context, const ::rl::training::v1::DistributorStatusReq& request, ::rl::training::v1::DistributorStatusRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rl::training::v1::DistributorStatusReq, ::rl::training::v1::DistributorStatusRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetStatus_, context, request, response);
}

void SampleDistributorService::Stub::async::GetStatus(::grpc::ClientContext* context, const ::rl::training::v1::DistributorStatusReq* request, ::rl::training::v1::DistributorStatusRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rl::training::v1::DistributorStatusReq, ::rl::training::v1::DistributorStatusRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStatus_, context, request, response, std::move(f));
}

void SampleDistributorService::Stub::async::GetStatus(::grpc::ClientContext* context, const ::rl::training::v1::DistributorStatusReq* request, ::rl::training::v1::DistributorStatusRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::DistributorStatusRsp>* SampleDistributorService::Stub::PrepareAsyncGetStatusRaw(::grpc::ClientContext* context, const ::rl::training::v1::DistributorStatusReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rl::training::v1::DistributorStatusRsp, ::rl::training::v1::DistributorStatusReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::DistributorStatusRsp>* SampleDistributorService::Stub::AsyncGetStatusRaw(::grpc::ClientContext* context, const ::rl::training::v1::DistributorStatusReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

SampleDistributorService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SampleDistributorService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SampleDistributorService::Service, ::rl::training::v1::UpsertSampleDemandReq, ::rl::training::v1::SampleDemandRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SampleDistributorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rl::training::v1::UpsertSampleDemandReq* req,
             ::rl::training::v1::SampleDemandRsp* resp) {
               return service->UpsertSampleDemand(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SampleDistributorService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SampleDistributorService::Service, ::rl::training::v1::ReleaseSampleDemandReq, ::rl::training::v1::SampleDemandRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SampleDistributorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rl::training::v1::ReleaseSampleDemandReq* req,
             ::rl::training::v1::SampleDemandRsp* resp) {
               return service->ReleaseSampleDemand(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SampleDistributorService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SampleDistributorService::Service, ::rl::training::v1::GetSampleDemandStatusReq, ::rl::training::v1::SampleDemandStatusRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SampleDistributorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rl::training::v1::GetSampleDemandStatusReq* req,
             ::rl::training::v1::SampleDemandStatusRsp* resp) {
               return service->GetSampleDemandStatus(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SampleDistributorService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SampleDistributorService::Service, ::rl::training::v1::AcquireSampleCreditReq, ::rl::training::v1::SampleCreditGrant, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SampleDistributorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rl::training::v1::AcquireSampleCreditReq* req,
             ::rl::training::v1::SampleCreditGrant* resp) {
               return service->AcquireSampleCredit(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SampleDistributorService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SampleDistributorService::Service, ::rl::training::v1::ReleaseSampleCreditReq, ::rl::training::v1::ReleaseSampleCreditRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SampleDistributorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rl::training::v1::ReleaseSampleCreditReq* req,
             ::rl::training::v1::ReleaseSampleCreditRsp* resp) {
               return service->ReleaseSampleCredit(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SampleDistributorService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SampleDistributorService::Service, ::rl::training::v1::PushSamplesReq, ::rl::training::v1::PushSamplesRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SampleDistributorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rl::training::v1::PushSamplesReq* req,
             ::rl::training::v1::PushSamplesRsp* resp) {
               return service->PushSamples(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SampleDistributorService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SampleDistributorService::Service, ::rl::training::v1::GetBatchReq, ::rl::training::v1::GetBatchRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SampleDistributorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rl::training::v1::GetBatchReq* req,
             ::rl::training::v1::GetBatchRsp* resp) {
               return service->GetBatch(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SampleDistributorService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SampleDistributorService::Service, ::rl::training::v1::AckBatchReq, ::rl::training::v1::DeliveryRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SampleDistributorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rl::training::v1::AckBatchReq* req,
             ::rl::training::v1::DeliveryRsp* resp) {
               return service->AckBatch(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SampleDistributorService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SampleDistributorService::Service, ::rl::training::v1::NackBatchReq, ::rl::training::v1::DeliveryRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SampleDistributorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rl::training::v1::NackBatchReq* req,
             ::rl::training::v1::DeliveryRsp* resp) {
               return service->NackBatch(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SampleDistributorService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SampleDistributorService::Service, ::rl::training::v1::RenewLeaseReq, ::rl::training::v1::DeliveryRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SampleDistributorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rl::training::v1::RenewLeaseReq* req,
             ::rl::training::v1::DeliveryRsp* resp) {
               return service->RenewLease(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SampleDistributorService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SampleDistributorService::Service, ::rl::training::v1::DistributorStatusReq, ::rl::training::v1::DistributorStatusRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SampleDistributorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rl::training::v1::DistributorStatusReq* req,
             ::rl::training::v1::DistributorStatusRsp* resp) {
               return service->GetStatus(ctx, req, resp);
             }, this)));
}

SampleDistributorService::Service::~Service() {
}

::grpc::Status SampleDistributorService::Service::UpsertSampleDemand(::grpc::ServerContext* context, const ::rl::training::v1::UpsertSampleDemandReq* request, ::rl::training::v1::SampleDemandRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SampleDistributorService::Service::ReleaseSampleDemand(::grpc::ServerContext* context, const ::rl::training::v1::ReleaseSampleDemandReq* request, ::rl::training::v1::SampleDemandRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SampleDistributorService::Service::GetSampleDemandStatus(::grpc::ServerContext* context, const ::rl::training::v1::GetSampleDemandStatusReq* request, ::rl::training::v1::SampleDemandStatusRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SampleDistributorService::Service::AcquireSampleCredit(::grpc::ServerContext* context, const ::rl::training::v1::AcquireSampleCreditReq* request, ::rl::training::v1::SampleCreditGrant* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SampleDistributorService::Service::ReleaseSampleCredit(::grpc::ServerContext* context, const ::rl::training::v1::ReleaseSampleCreditReq* request, ::rl::training::v1::ReleaseSampleCreditRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SampleDistributorService::Service::PushSamples(::grpc::ServerContext* context, const ::rl::training::v1::PushSamplesReq* request, ::rl::training::v1::PushSamplesRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SampleDistributorService::Service::GetBatch(::grpc::ServerContext* context, const ::rl::training::v1::GetBatchReq* request, ::rl::training::v1::GetBatchRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SampleDistributorService::Service::AckBatch(::grpc::ServerContext* context, const ::rl::training::v1::AckBatchReq* request, ::rl::training::v1::DeliveryRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SampleDistributorService::Service::NackBatch(::grpc::ServerContext* context, const ::rl::training::v1::NackBatchReq* request, ::rl::training::v1::DeliveryRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SampleDistributorService::Service::RenewLease(::grpc::ServerContext* context, const ::rl::training::v1::RenewLeaseReq* request, ::rl::training::v1::DeliveryRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SampleDistributorService::Service::GetStatus(::grpc::ServerContext* context, const ::rl::training::v1::DistributorStatusReq* request, ::rl::training::v1::DistributorStatusRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* ModelDistributorService_method_names[] = {
  "/rl.training.v1.ModelDistributorService/RegisterModel",
  "/rl.training.v1.ModelDistributorService/GetModelManifest",
  "/rl.training.v1.ModelDistributorService/DownloadModel",
  "/rl.training.v1.ModelDistributorService/AckModel",
  "/rl.training.v1.ModelDistributorService/GetModelDistributorStatus",
};

std::unique_ptr< ModelDistributorService::Stub> ModelDistributorService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ModelDistributorService::Stub> stub(new ModelDistributorService::Stub(channel, options));
  return stub;
}

ModelDistributorService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RegisterModel_(ModelDistributorService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetModelManifest_(ModelDistributorService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DownloadModel_(ModelDistributorService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_AckModel_(ModelDistributorService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetModelDistributorStatus_(ModelDistributorService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ModelDistributorService::Stub::RegisterModel(::grpc::ClientContext* context, const ::rl::training::v1::RegisterModelReq& request, ::rl::training::v1::RegisterModelRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rl::training::v1::RegisterModelReq, ::rl::training::v1::RegisterModelRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RegisterModel_, context, request, response);
}

void ModelDistributorService::Stub::async::RegisterModel(::grpc::ClientContext* context, const ::rl::training::v1::RegisterModelReq* request, ::rl::training::v1::RegisterModelRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rl::training::v1::RegisterModelReq, ::rl::training::v1::RegisterModelRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterModel_, context, request, response, std::move(f));
}

void ModelDistributorService::Stub::async::RegisterModel(::grpc::ClientContext* context, const ::rl::training::v1::RegisterModelReq* request, ::rl::training::v1::RegisterModelRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterModel_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::RegisterModelRsp>* ModelDistributorService::Stub::PrepareAsyncRegisterModelRaw(::grpc::ClientContext* context, const ::rl::training::v1::RegisterModelReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rl::training::v1::RegisterModelRsp, ::rl::training::v1::RegisterModelReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RegisterModel_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::RegisterModelRsp>* ModelDistributorService::Stub::AsyncRegisterModelRaw(::grpc::ClientContext* context, const ::rl::training::v1::RegisterModelReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterModelRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ModelDistributorService::Stub::GetModelManifest(::grpc::ClientContext* context, const ::rl::training::v1::GetModelManifestReq& request, ::rl::training::v1::GetModelManifestRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rl::training::v1::GetModelManifestReq, ::rl::training::v1::GetModelManifestRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetModelManifest_, context, request, response);
}

void ModelDistributorService::Stub::async::GetModelManifest(::grpc::ClientContext* context, const ::rl::training::v1::GetModelManifestReq* request, ::rl::training::v1::GetModelManifestRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rl::training::v1::GetModelManifestReq, ::rl::training::v1::GetModelManifestRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetModelManifest_, context, request, response, std::move(f));
}

void ModelDistributorService::Stub::async::GetModelManifest(::grpc::ClientContext* context, const ::rl::training::v1::GetModelManifestReq* request, ::rl::training::v1::GetModelManifestRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetModelManifest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::GetModelManifestRsp>* ModelDistributorService::Stub::PrepareAsyncGetModelManifestRaw(::grpc::ClientContext* context, const ::rl::training::v1::GetModelManifestReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rl::training::v1::GetModelManifestRsp, ::rl::training::v1::GetModelManifestReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetModelManifest_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::GetModelManifestRsp>* ModelDistributorService::Stub::AsyncGetModelManifestRaw(::grpc::ClientContext* context, const ::rl::training::v1::GetModelManifestReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetModelManifestRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::rl::training::v1::ModelChunk>* ModelDistributorService::Stub::DownloadModelRaw(::grpc::ClientContext* context, const ::rl::training::v1::DownloadModelReq& request) {
  return ::grpc::internal::ClientReaderFactory< ::rl::training::v1::ModelChunk>::Create(channel_.get(), rpcmethod_DownloadModel_, context, request);
}

void ModelDistributorService::Stub::async::DownloadModel(::grpc::ClientContext* context, const ::rl::training::v1::DownloadModelReq* request, ::grpc::ClientReadReactor< ::rl::training::v1::ModelChunk>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::rl::training::v1::ModelChunk>::Create(stub_->channel_.get(), stub_->rpcmethod_DownloadModel_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::rl::training::v1::ModelChunk>* ModelDistributorService::Stub::AsyncDownloadModelRaw(::grpc::ClientContext* context, const ::rl::training::v1::DownloadModelReq& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::rl::training::v1::ModelChunk>::Create(channel_.get(), cq, rpcmethod_DownloadModel_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::rl::training::v1::ModelChunk>* ModelDistributorService::Stub::PrepareAsyncDownloadModelRaw(::grpc::ClientContext* context, const ::rl::training::v1::DownloadModelReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::rl::training::v1::ModelChunk>::Create(channel_.get(), cq, rpcmethod_DownloadModel_, context, request, false, nullptr);
}

::grpc::Status ModelDistributorService::Stub::AckModel(::grpc::ClientContext* context, const ::rl::training::v1::AckModelReq& request, ::rl::training::v1::AckModelRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rl::training::v1::AckModelReq, ::rl::training::v1::AckModelRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AckModel_, context, request, response);
}

void ModelDistributorService::Stub::async::AckModel(::grpc::ClientContext* context, const ::rl::training::v1::AckModelReq* request, ::rl::training::v1::AckModelRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rl::training::v1::AckModelReq, ::rl::training::v1::AckModelRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AckModel_, context, request, response, std::move(f));
}

void ModelDistributorService::Stub::async::AckModel(::grpc::ClientContext* context, const ::rl::training::v1::AckModelReq* request, ::rl::training::v1::AckModelRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AckModel_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::AckModelRsp>* ModelDistributorService::Stub::PrepareAsyncAckModelRaw(::grpc::ClientContext* context, const ::rl::training::v1::AckModelReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rl::training::v1::AckModelRsp, ::rl::training::v1::AckModelReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AckModel_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::AckModelRsp>* ModelDistributorService::Stub::AsyncAckModelRaw(::grpc::ClientContext* context, const ::rl::training::v1::AckModelReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAckModelRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ModelDistributorService::Stub::GetModelDistributorStatus(::grpc::ClientContext* context, const ::rl::training::v1::ModelDistributorStatusReq& request, ::rl::training::v1::ModelDistributorStatusRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rl::training::v1::ModelDistributorStatusReq, ::rl::training::v1::ModelDistributorStatusRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetModelDistributorStatus_, context, request, response);
}

void ModelDistributorService::Stub::async::GetModelDistributorStatus(::grpc::ClientContext* context, const ::rl::training::v1::ModelDistributorStatusReq* request, ::rl::training::v1::ModelDistributorStatusRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rl::training::v1::ModelDistributorStatusReq, ::rl::training::v1::ModelDistributorStatusRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetModelDistributorStatus_, context, request, response, std::move(f));
}

void ModelDistributorService::Stub::async::GetModelDistributorStatus(::grpc::ClientContext* context, const ::rl::training::v1::ModelDistributorStatusReq* request, ::rl::training::v1::ModelDistributorStatusRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetModelDistributorStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::ModelDistributorStatusRsp>* ModelDistributorService::Stub::PrepareAsyncGetModelDistributorStatusRaw(::grpc::ClientContext* context, const ::rl::training::v1::ModelDistributorStatusReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rl::training::v1::ModelDistributorStatusRsp, ::rl::training::v1::ModelDistributorStatusReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetModelDistributorStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rl::training::v1::ModelDistributorStatusRsp>* ModelDistributorService::Stub::AsyncGetModelDistributorStatusRaw(::grpc::ClientContext* context, const ::rl::training::v1::ModelDistributorStatusReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetModelDistributorStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

ModelDistributorService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ModelDistributorService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ModelDistributorService::Service, ::rl::training::v1::RegisterModelReq, ::rl::training::v1::RegisterModelRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ModelDistributorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rl::training::v1::RegisterModelReq* req,
             ::rl::training::v1::RegisterModelRsp* resp) {
               return service->RegisterModel(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ModelDistributorService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ModelDistributorService::Service, ::rl::training::v1::GetModelManifestReq, ::rl::training::v1::GetModelManifestRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ModelDistributorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rl::training::v1::GetModelManifestReq* req,
             ::rl::training::v1::GetModelManifestRsp* resp) {
               return service->GetModelManifest(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ModelDistributorService_method_names[2],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< ModelDistributorService::Service, ::rl::training::v1::DownloadModelReq, ::rl::training::v1::ModelChunk>(
          [](ModelDistributorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rl::training::v1::DownloadModelReq* req,
             ::grpc::ServerWriter<::rl::training::v1::ModelChunk>* writer) {
               return service->DownloadModel(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ModelDistributorService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ModelDistributorService::Service, ::rl::training::v1::AckModelReq, ::rl::training::v1::AckModelRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ModelDistributorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rl::training::v1::AckModelReq* req,
             ::rl::training::v1::AckModelRsp* resp) {
               return service->AckModel(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ModelDistributorService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ModelDistributorService::Service, ::rl::training::v1::ModelDistributorStatusReq, ::rl::training::v1::ModelDistributorStatusRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ModelDistributorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rl::training::v1::ModelDistributorStatusReq* req,
             ::rl::training::v1::ModelDistributorStatusRsp* resp) {
               return service->GetModelDistributorStatus(ctx, req, resp);
             }, this)));
}

ModelDistributorService::Service::~Service() {
}

::grpc::Status ModelDistributorService::Service::RegisterModel(::grpc::ServerContext* context, const ::rl::training::v1::RegisterModelReq* request, ::rl::training::v1::RegisterModelRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ModelDistributorService::Service::GetModelManifest(::grpc::ServerContext* context, const ::rl::training::v1::GetModelManifestReq* request, ::rl::training::v1::GetModelManifestRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ModelDistributorService::Service::DownloadModel(::grpc::ServerContext* context, const ::rl::training::v1::DownloadModelReq* request, ::grpc::ServerWriter< ::rl::training::v1::ModelChunk>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ModelDistributorService::Service::AckModel(::grpc::ServerContext* context, const ::rl::training::v1::AckModelReq* request, ::rl::training::v1::AckModelRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ModelDistributorService::Service::GetModelDistributorStatus(::grpc::ServerContext* context, const ::rl::training::v1::ModelDistributorStatusReq* request, ::rl::training::v1::ModelDistributorStatusRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace rl
}  // namespace training
}  // namespace v1

