// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: training_metrics.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_training_5fmetrics_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_training_5fmetrics_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
#include "training.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_training_5fmetrics_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_training_5fmetrics_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_training_5fmetrics_2eproto;
namespace rl {
namespace training {
namespace metrics {
namespace v1 {
class TrainUpdateMetricFact;
struct TrainUpdateMetricFactDefaultTypeInternal;
extern TrainUpdateMetricFactDefaultTypeInternal _TrainUpdateMetricFact_default_instance_;
}  // namespace v1
}  // namespace metrics
}  // namespace training
}  // namespace rl
PROTOBUF_NAMESPACE_OPEN
template<> ::rl::training::metrics::v1::TrainUpdateMetricFact* Arena::CreateMaybeMessage<::rl::training::metrics::v1::TrainUpdateMetricFact>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace rl {
namespace training {
namespace metrics {
namespace v1 {

// ===================================================================

class TrainUpdateMetricFact final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rl.training.metrics.v1.TrainUpdateMetricFact) */ {
 public:
  inline TrainUpdateMetricFact() : TrainUpdateMetricFact(nullptr) {}
  ~TrainUpdateMetricFact() override;
  explicit PROTOBUF_CONSTEXPR TrainUpdateMetricFact(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TrainUpdateMetricFact(const TrainUpdateMetricFact& from);
  TrainUpdateMetricFact(TrainUpdateMetricFact&& from) noexcept
    : TrainUpdateMetricFact() {
    *this = ::std::move(from);
  }

  inline TrainUpdateMetricFact& operator=(const TrainUpdateMetricFact& from) {
    CopyFrom(from);
    return *this;
  }
  inline TrainUpdateMetricFact& operator=(TrainUpdateMetricFact&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TrainUpdateMetricFact& default_instance() {
    return *internal_default_instance();
  }
  static inline const TrainUpdateMetricFact* internal_default_instance() {
    return reinterpret_cast<const TrainUpdateMetricFact*>(
               &_TrainUpdateMetricFact_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TrainUpdateMetricFact& a, TrainUpdateMetricFact& b) {
    a.Swap(&b);
  }
  inline void Swap(TrainUpdateMetricFact* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TrainUpdateMetricFact* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TrainUpdateMetricFact* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TrainUpdateMetricFact>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TrainUpdateMetricFact& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TrainUpdateMetricFact& from) {
    TrainUpdateMetricFact::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TrainUpdateMetricFact* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rl.training.metrics.v1.TrainUpdateMetricFact";
  }
  protected:
  explicit TrainUpdateMetricFact(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPpoStatisticsFieldNumber = 10,
    kTrainUpdateIdFieldNumber = 1,
    kDeliveryIdFieldNumber = 4,
    kBehaviorModelLineageIdFieldNumber = 11,
    kPublishedModelFieldNumber = 3,
    kTrainingContractDigestFieldNumber = 5,
    kRolloutEstimatorProfileDigestFieldNumber = 18,
    kTrainUpdateSequenceFieldNumber = 2,
    kCumulativeTrainedSamplesFieldNumber = 6,
    kActualBatchSizeFieldNumber = 7,
    kMinimumBehaviorModelStepFieldNumber = 8,
    kMaximumBehaviorModelStepFieldNumber = 9,
    kRequestedTrainBatchSizeFieldNumber = 12,
    kPoolDrawSlotCountFieldNumber = 13,
    kUniqueItemCountFieldNumber = 14,
    kDuplicateItemSlotCountFieldNumber = 15,
    kSampleEvaluationCountFieldNumber = 16,
    kOptimizerStepCountFieldNumber = 17,
  };
  // repeated .rl.training.v1.RawMetricSumCount ppo_statistics = 10;
  int ppo_statistics_size() const;
  private:
  int _internal_ppo_statistics_size() const;
  public:
  void clear_ppo_statistics();
  ::rl::training::v1::RawMetricSumCount* mutable_ppo_statistics(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rl::training::v1::RawMetricSumCount >*
      mutable_ppo_statistics();
  private:
  const ::rl::training::v1::RawMetricSumCount& _internal_ppo_statistics(int index) const;
  ::rl::training::v1::RawMetricSumCount* _internal_add_ppo_statistics();
  public:
  const ::rl::training::v1::RawMetricSumCount& ppo_statistics(int index) const;
  ::rl::training::v1::RawMetricSumCount* add_ppo_statistics();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rl::training::v1::RawMetricSumCount >&
      ppo_statistics() const;

  // string train_update_id = 1;
  void clear_train_update_id();
  const std::string& train_update_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_train_update_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_train_update_id();
  PROTOBUF_NODISCARD std::string* release_train_update_id();
  void set_allocated_train_update_id(std::string* train_update_id);
  private:
  const std::string& _internal_train_update_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_train_update_id(const std::string& value);
  std::string* _internal_mutable_train_update_id();
  public:

  // string delivery_id = 4;
  void clear_delivery_id();
  const std::string& delivery_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_delivery_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_delivery_id();
  PROTOBUF_NODISCARD std::string* release_delivery_id();
  void set_allocated_delivery_id(std::string* delivery_id);
  private:
  const std::string& _internal_delivery_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_delivery_id(const std::string& value);
  std::string* _internal_mutable_delivery_id();
  public:

  // string behavior_model_lineage_id = 11;
  void clear_behavior_model_lineage_id();
  const std::string& behavior_model_lineage_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_behavior_model_lineage_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_behavior_model_lineage_id();
  PROTOBUF_NODISCARD std::string* release_behavior_model_lineage_id();
  void set_allocated_behavior_model_lineage_id(std::string* behavior_model_lineage_id);
  private:
  const std::string& _internal_behavior_model_lineage_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_behavior_model_lineage_id(const std::string& value);
  std::string* _internal_mutable_behavior_model_lineage_id();
  public:

  // .rl.training.v1.ModelIdentity published_model = 3;
  bool has_published_model() const;
  private:
  bool _internal_has_published_model() const;
  public:
  void clear_published_model();
  const ::rl::training::v1::ModelIdentity& published_model() const;
  PROTOBUF_NODISCARD ::rl::training::v1::ModelIdentity* release_published_model();
  ::rl::training::v1::ModelIdentity* mutable_published_model();
  void set_allocated_published_model(::rl::training::v1::ModelIdentity* published_model);
  private:
  const ::rl::training::v1::ModelIdentity& _internal_published_model() const;
  ::rl::training::v1::ModelIdentity* _internal_mutable_published_model();
  public:
  void unsafe_arena_set_allocated_published_model(
      ::rl::training::v1::ModelIdentity* published_model);
  ::rl::training::v1::ModelIdentity* unsafe_arena_release_published_model();

  // .rl.common.v1.ContentDigest training_contract_digest = 5;
  bool has_training_contract_digest() const;
  private:
  bool _internal_has_training_contract_digest() const;
  public:
  void clear_training_contract_digest();
  const ::rl::common::v1::ContentDigest& training_contract_digest() const;
  PROTOBUF_NODISCARD ::rl::common::v1::ContentDigest* release_training_contract_digest();
  ::rl::common::v1::ContentDigest* mutable_training_contract_digest();
  void set_allocated_training_contract_digest(::rl::common::v1::ContentDigest* training_contract_digest);
  private:
  const ::rl::common::v1::ContentDigest& _internal_training_contract_digest() const;
  ::rl::common::v1::ContentDigest* _internal_mutable_training_contract_digest();
  public:
  void unsafe_arena_set_allocated_training_contract_digest(
      ::rl::common::v1::ContentDigest* training_contract_digest);
  ::rl::common::v1::ContentDigest* unsafe_arena_release_training_contract_digest();

  // .rl.common.v1.ContentDigest rollout_estimator_profile_digest = 18;
  bool has_rollout_estimator_profile_digest() const;
  private:
  bool _internal_has_rollout_estimator_profile_digest() const;
  public:
  void clear_rollout_estimator_profile_digest();
  const ::rl::common::v1::ContentDigest& rollout_estimator_profile_digest() const;
  PROTOBUF_NODISCARD ::rl::common::v1::ContentDigest* release_rollout_estimator_profile_digest();
  ::rl::common::v1::ContentDigest* mutable_rollout_estimator_profile_digest();
  void set_allocated_rollout_estimator_profile_digest(::rl::common::v1::ContentDigest* rollout_estimator_profile_digest);
  private:
  const ::rl::common::v1::ContentDigest& _internal_rollout_estimator_profile_digest() const;
  ::rl::common::v1::ContentDigest* _internal_mutable_rollout_estimator_profile_digest();
  public:
  void unsafe_arena_set_allocated_rollout_estimator_profile_digest(
      ::rl::common::v1::ContentDigest* rollout_estimator_profile_digest);
  ::rl::common::v1::ContentDigest* unsafe_arena_release_rollout_estimator_profile_digest();

  // uint64 train_update_sequence = 2;
  void clear_train_update_sequence();
  uint64_t train_update_sequence() const;
  void set_train_update_sequence(uint64_t value);
  private:
  uint64_t _internal_train_update_sequence() const;
  void _internal_set_train_update_sequence(uint64_t value);
  public:

  // int64 cumulative_trained_samples = 6;
  void clear_cumulative_trained_samples();
  int64_t cumulative_trained_samples() const;
  void set_cumulative_trained_samples(int64_t value);
  private:
  int64_t _internal_cumulative_trained_samples() const;
  void _internal_set_cumulative_trained_samples(int64_t value);
  public:

  // int64 actual_batch_size = 7;
  void clear_actual_batch_size();
  int64_t actual_batch_size() const;
  void set_actual_batch_size(int64_t value);
  private:
  int64_t _internal_actual_batch_size() const;
  void _internal_set_actual_batch_size(int64_t value);
  public:

  // optional uint64 minimum_behavior_model_step = 8;
  bool has_minimum_behavior_model_step() const;
  private:
  bool _internal_has_minimum_behavior_model_step() const;
  public:
  void clear_minimum_behavior_model_step();
  uint64_t minimum_behavior_model_step() const;
  void set_minimum_behavior_model_step(uint64_t value);
  private:
  uint64_t _internal_minimum_behavior_model_step() const;
  void _internal_set_minimum_behavior_model_step(uint64_t value);
  public:

  // optional uint64 maximum_behavior_model_step = 9;
  bool has_maximum_behavior_model_step() const;
  private:
  bool _internal_has_maximum_behavior_model_step() const;
  public:
  void clear_maximum_behavior_model_step();
  uint64_t maximum_behavior_model_step() const;
  void set_maximum_behavior_model_step(uint64_t value);
  private:
  uint64_t _internal_maximum_behavior_model_step() const;
  void _internal_set_maximum_behavior_model_step(uint64_t value);
  public:

  // int64 requested_train_batch_size = 12;
  void clear_requested_train_batch_size();
  int64_t requested_train_batch_size() const;
  void set_requested_train_batch_size(int64_t value);
  private:
  int64_t _internal_requested_train_batch_size() const;
  void _internal_set_requested_train_batch_size(int64_t value);
  public:

  // int64 pool_draw_slot_count = 13;
  void clear_pool_draw_slot_count();
  int64_t pool_draw_slot_count() const;
  void set_pool_draw_slot_count(int64_t value);
  private:
  int64_t _internal_pool_draw_slot_count() const;
  void _internal_set_pool_draw_slot_count(int64_t value);
  public:

  // int64 unique_item_count = 14;
  void clear_unique_item_count();
  int64_t unique_item_count() const;
  void set_unique_item_count(int64_t value);
  private:
  int64_t _internal_unique_item_count() const;
  void _internal_set_unique_item_count(int64_t value);
  public:

  // int64 duplicate_item_slot_count = 15;
  void clear_duplicate_item_slot_count();
  int64_t duplicate_item_slot_count() const;
  void set_duplicate_item_slot_count(int64_t value);
  private:
  int64_t _internal_duplicate_item_slot_count() const;
  void _internal_set_duplicate_item_slot_count(int64_t value);
  public:

  // int64 sample_evaluation_count = 16;
  void clear_sample_evaluation_count();
  int64_t sample_evaluation_count() const;
  void set_sample_evaluation_count(int64_t value);
  private:
  int64_t _internal_sample_evaluation_count() const;
  void _internal_set_sample_evaluation_count(int64_t value);
  public:

  // int64 optimizer_step_count = 17;
  void clear_optimizer_step_count();
  int64_t optimizer_step_count() const;
  void set_optimizer_step_count(int64_t value);
  private:
  int64_t _internal_optimizer_step_count() const;
  void _internal_set_optimizer_step_count(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:rl.training.metrics.v1.TrainUpdateMetricFact)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rl::training::v1::RawMetricSumCount > ppo_statistics_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr train_update_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr delivery_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr behavior_model_lineage_id_;
    ::rl::training::v1::ModelIdentity* published_model_;
    ::rl::common::v1::ContentDigest* training_contract_digest_;
    ::rl::common::v1::ContentDigest* rollout_estimator_profile_digest_;
    uint64_t train_update_sequence_;
    int64_t cumulative_trained_samples_;
    int64_t actual_batch_size_;
    uint64_t minimum_behavior_model_step_;
    uint64_t maximum_behavior_model_step_;
    int64_t requested_train_batch_size_;
    int64_t pool_draw_slot_count_;
    int64_t unique_item_count_;
    int64_t duplicate_item_slot_count_;
    int64_t sample_evaluation_count_;
    int64_t optimizer_step_count_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_training_5fmetrics_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TrainUpdateMetricFact

// string train_update_id = 1;
inline void TrainUpdateMetricFact::clear_train_update_id() {
  _impl_.train_update_id_.ClearToEmpty();
}
inline const std::string& TrainUpdateMetricFact::train_update_id() const {
  // @@protoc_insertion_point(field_get:rl.training.metrics.v1.TrainUpdateMetricFact.train_update_id)
  return _internal_train_update_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TrainUpdateMetricFact::set_train_update_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.train_update_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:rl.training.metrics.v1.TrainUpdateMetricFact.train_update_id)
}
inline std::string* TrainUpdateMetricFact::mutable_train_update_id() {
  std::string* _s = _internal_mutable_train_update_id();
  // @@protoc_insertion_point(field_mutable:rl.training.metrics.v1.TrainUpdateMetricFact.train_update_id)
  return _s;
}
inline const std::string& TrainUpdateMetricFact::_internal_train_update_id() const {
  return _impl_.train_update_id_.Get();
}
inline void TrainUpdateMetricFact::_internal_set_train_update_id(const std::string& value) {
  
  _impl_.train_update_id_.Set(value, GetArenaForAllocation());
}
inline std::string* TrainUpdateMetricFact::_internal_mutable_train_update_id() {
  
  return _impl_.train_update_id_.Mutable(GetArenaForAllocation());
}
inline std::string* TrainUpdateMetricFact::release_train_update_id() {
  // @@protoc_insertion_point(field_release:rl.training.metrics.v1.TrainUpdateMetricFact.train_update_id)
  return _impl_.train_update_id_.Release();
}
inline void TrainUpdateMetricFact::set_allocated_train_update_id(std::string* train_update_id) {
  if (train_update_id != nullptr) {
    
  } else {
    
  }
  _impl_.train_update_id_.SetAllocated(train_update_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.train_update_id_.IsDefault()) {
    _impl_.train_update_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:rl.training.metrics.v1.TrainUpdateMetricFact.train_update_id)
}

// uint64 train_update_sequence = 2;
inline void TrainUpdateMetricFact::clear_train_update_sequence() {
  _impl_.train_update_sequence_ = uint64_t{0u};
}
inline uint64_t TrainUpdateMetricFact::_internal_train_update_sequence() const {
  return _impl_.train_update_sequence_;
}
inline uint64_t TrainUpdateMetricFact::train_update_sequence() const {
  // @@protoc_insertion_point(field_get:rl.training.metrics.v1.TrainUpdateMetricFact.train_update_sequence)
  return _internal_train_update_sequence();
}
inline void TrainUpdateMetricFact::_internal_set_train_update_sequence(uint64_t value) {
  
  _impl_.train_update_sequence_ = value;
}
inline void TrainUpdateMetricFact::set_train_update_sequence(uint64_t value) {
  _internal_set_train_update_sequence(value);
  // @@protoc_insertion_point(field_set:rl.training.metrics.v1.TrainUpdateMetricFact.train_update_sequence)
}

// .rl.training.v1.ModelIdentity published_model = 3;
inline bool TrainUpdateMetricFact::_internal_has_published_model() const {
  return this != internal_default_instance() && _impl_.published_model_ != nullptr;
}
inline bool TrainUpdateMetricFact::has_published_model() const {
  return _internal_has_published_model();
}
inline const ::rl::training::v1::ModelIdentity& TrainUpdateMetricFact::_internal_published_model() const {
  const ::rl::training::v1::ModelIdentity* p = _impl_.published_model_;
  return p != nullptr ? *p : reinterpret_cast<const ::rl::training::v1::ModelIdentity&>(
      ::rl::training::v1::_ModelIdentity_default_instance_);
}
inline const ::rl::training::v1::ModelIdentity& TrainUpdateMetricFact::published_model() const {
  // @@protoc_insertion_point(field_get:rl.training.metrics.v1.TrainUpdateMetricFact.published_model)
  return _internal_published_model();
}
inline void TrainUpdateMetricFact::unsafe_arena_set_allocated_published_model(
    ::rl::training::v1::ModelIdentity* published_model) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.published_model_);
  }
  _impl_.published_model_ = published_model;
  if (published_model) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:rl.training.metrics.v1.TrainUpdateMetricFact.published_model)
}
inline ::rl::training::v1::ModelIdentity* TrainUpdateMetricFact::release_published_model() {
  
  ::rl::training::v1::ModelIdentity* temp = _impl_.published_model_;
  _impl_.published_model_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::rl::training::v1::ModelIdentity* TrainUpdateMetricFact::unsafe_arena_release_published_model() {
  // @@protoc_insertion_point(field_release:rl.training.metrics.v1.TrainUpdateMetricFact.published_model)
  
  ::rl::training::v1::ModelIdentity* temp = _impl_.published_model_;
  _impl_.published_model_ = nullptr;
  return temp;
}
inline ::rl::training::v1::ModelIdentity* TrainUpdateMetricFact::_internal_mutable_published_model() {
  
  if (_impl_.published_model_ == nullptr) {
    auto* p = CreateMaybeMessage<::rl::training::v1::ModelIdentity>(GetArenaForAllocation());
    _impl_.published_model_ = p;
  }
  return _impl_.published_model_;
}
inline ::rl::training::v1::ModelIdentity* TrainUpdateMetricFact::mutable_published_model() {
  ::rl::training::v1::ModelIdentity* _msg = _internal_mutable_published_model();
  // @@protoc_insertion_point(field_mutable:rl.training.metrics.v1.TrainUpdateMetricFact.published_model)
  return _msg;
}
inline void TrainUpdateMetricFact::set_allocated_published_model(::rl::training::v1::ModelIdentity* published_model) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.published_model_);
  }
  if (published_model) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(published_model));
    if (message_arena != submessage_arena) {
      published_model = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, published_model, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.published_model_ = published_model;
  // @@protoc_insertion_point(field_set_allocated:rl.training.metrics.v1.TrainUpdateMetricFact.published_model)
}

// string delivery_id = 4;
inline void TrainUpdateMetricFact::clear_delivery_id() {
  _impl_.delivery_id_.ClearToEmpty();
}
inline const std::string& TrainUpdateMetricFact::delivery_id() const {
  // @@protoc_insertion_point(field_get:rl.training.metrics.v1.TrainUpdateMetricFact.delivery_id)
  return _internal_delivery_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TrainUpdateMetricFact::set_delivery_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.delivery_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:rl.training.metrics.v1.TrainUpdateMetricFact.delivery_id)
}
inline std::string* TrainUpdateMetricFact::mutable_delivery_id() {
  std::string* _s = _internal_mutable_delivery_id();
  // @@protoc_insertion_point(field_mutable:rl.training.metrics.v1.TrainUpdateMetricFact.delivery_id)
  return _s;
}
inline const std::string& TrainUpdateMetricFact::_internal_delivery_id() const {
  return _impl_.delivery_id_.Get();
}
inline void TrainUpdateMetricFact::_internal_set_delivery_id(const std::string& value) {
  
  _impl_.delivery_id_.Set(value, GetArenaForAllocation());
}
inline std::string* TrainUpdateMetricFact::_internal_mutable_delivery_id() {
  
  return _impl_.delivery_id_.Mutable(GetArenaForAllocation());
}
inline std::string* TrainUpdateMetricFact::release_delivery_id() {
  // @@protoc_insertion_point(field_release:rl.training.metrics.v1.TrainUpdateMetricFact.delivery_id)
  return _impl_.delivery_id_.Release();
}
inline void TrainUpdateMetricFact::set_allocated_delivery_id(std::string* delivery_id) {
  if (delivery_id != nullptr) {
    
  } else {
    
  }
  _impl_.delivery_id_.SetAllocated(delivery_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.delivery_id_.IsDefault()) {
    _impl_.delivery_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:rl.training.metrics.v1.TrainUpdateMetricFact.delivery_id)
}

// .rl.common.v1.ContentDigest training_contract_digest = 5;
inline bool TrainUpdateMetricFact::_internal_has_training_contract_digest() const {
  return this != internal_default_instance() && _impl_.training_contract_digest_ != nullptr;
}
inline bool TrainUpdateMetricFact::has_training_contract_digest() const {
  return _internal_has_training_contract_digest();
}
inline const ::rl::common::v1::ContentDigest& TrainUpdateMetricFact::_internal_training_contract_digest() const {
  const ::rl::common::v1::ContentDigest* p = _impl_.training_contract_digest_;
  return p != nullptr ? *p : reinterpret_cast<const ::rl::common::v1::ContentDigest&>(
      ::rl::common::v1::_ContentDigest_default_instance_);
}
inline const ::rl::common::v1::ContentDigest& TrainUpdateMetricFact::training_contract_digest() const {
  // @@protoc_insertion_point(field_get:rl.training.metrics.v1.TrainUpdateMetricFact.training_contract_digest)
  return _internal_training_contract_digest();
}
inline void TrainUpdateMetricFact::unsafe_arena_set_allocated_training_contract_digest(
    ::rl::common::v1::ContentDigest* training_contract_digest) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.training_contract_digest_);
  }
  _impl_.training_contract_digest_ = training_contract_digest;
  if (training_contract_digest) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:rl.training.metrics.v1.TrainUpdateMetricFact.training_contract_digest)
}
inline ::rl::common::v1::ContentDigest* TrainUpdateMetricFact::release_training_contract_digest() {
  
  ::rl::common::v1::ContentDigest* temp = _impl_.training_contract_digest_;
  _impl_.training_contract_digest_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::rl::common::v1::ContentDigest* TrainUpdateMetricFact::unsafe_arena_release_training_contract_digest() {
  // @@protoc_insertion_point(field_release:rl.training.metrics.v1.TrainUpdateMetricFact.training_contract_digest)
  
  ::rl::common::v1::ContentDigest* temp = _impl_.training_contract_digest_;
  _impl_.training_contract_digest_ = nullptr;
  return temp;
}
inline ::rl::common::v1::ContentDigest* TrainUpdateMetricFact::_internal_mutable_training_contract_digest() {
  
  if (_impl_.training_contract_digest_ == nullptr) {
    auto* p = CreateMaybeMessage<::rl::common::v1::ContentDigest>(GetArenaForAllocation());
    _impl_.training_contract_digest_ = p;
  }
  return _impl_.training_contract_digest_;
}
inline ::rl::common::v1::ContentDigest* TrainUpdateMetricFact::mutable_training_contract_digest() {
  ::rl::common::v1::ContentDigest* _msg = _internal_mutable_training_contract_digest();
  // @@protoc_insertion_point(field_mutable:rl.training.metrics.v1.TrainUpdateMetricFact.training_contract_digest)
  return _msg;
}
inline void TrainUpdateMetricFact::set_allocated_training_contract_digest(::rl::common::v1::ContentDigest* training_contract_digest) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.training_contract_digest_);
  }
  if (training_contract_digest) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(training_contract_digest));
    if (message_arena != submessage_arena) {
      training_contract_digest = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, training_contract_digest, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.training_contract_digest_ = training_contract_digest;
  // @@protoc_insertion_point(field_set_allocated:rl.training.metrics.v1.TrainUpdateMetricFact.training_contract_digest)
}

// int64 cumulative_trained_samples = 6;
inline void TrainUpdateMetricFact::clear_cumulative_trained_samples() {
  _impl_.cumulative_trained_samples_ = int64_t{0};
}
inline int64_t TrainUpdateMetricFact::_internal_cumulative_trained_samples() const {
  return _impl_.cumulative_trained_samples_;
}
inline int64_t TrainUpdateMetricFact::cumulative_trained_samples() const {
  // @@protoc_insertion_point(field_get:rl.training.metrics.v1.TrainUpdateMetricFact.cumulative_trained_samples)
  return _internal_cumulative_trained_samples();
}
inline void TrainUpdateMetricFact::_internal_set_cumulative_trained_samples(int64_t value) {
  
  _impl_.cumulative_trained_samples_ = value;
}
inline void TrainUpdateMetricFact::set_cumulative_trained_samples(int64_t value) {
  _internal_set_cumulative_trained_samples(value);
  // @@protoc_insertion_point(field_set:rl.training.metrics.v1.TrainUpdateMetricFact.cumulative_trained_samples)
}

// int64 actual_batch_size = 7;
inline void TrainUpdateMetricFact::clear_actual_batch_size() {
  _impl_.actual_batch_size_ = int64_t{0};
}
inline int64_t TrainUpdateMetricFact::_internal_actual_batch_size() const {
  return _impl_.actual_batch_size_;
}
inline int64_t TrainUpdateMetricFact::actual_batch_size() const {
  // @@protoc_insertion_point(field_get:rl.training.metrics.v1.TrainUpdateMetricFact.actual_batch_size)
  return _internal_actual_batch_size();
}
inline void TrainUpdateMetricFact::_internal_set_actual_batch_size(int64_t value) {
  
  _impl_.actual_batch_size_ = value;
}
inline void TrainUpdateMetricFact::set_actual_batch_size(int64_t value) {
  _internal_set_actual_batch_size(value);
  // @@protoc_insertion_point(field_set:rl.training.metrics.v1.TrainUpdateMetricFact.actual_batch_size)
}

// optional uint64 minimum_behavior_model_step = 8;
inline bool TrainUpdateMetricFact::_internal_has_minimum_behavior_model_step() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool TrainUpdateMetricFact::has_minimum_behavior_model_step() const {
  return _internal_has_minimum_behavior_model_step();
}
inline void TrainUpdateMetricFact::clear_minimum_behavior_model_step() {
  _impl_.minimum_behavior_model_step_ = uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline uint64_t TrainUpdateMetricFact::_internal_minimum_behavior_model_step() const {
  return _impl_.minimum_behavior_model_step_;
}
inline uint64_t TrainUpdateMetricFact::minimum_behavior_model_step() const {
  // @@protoc_insertion_point(field_get:rl.training.metrics.v1.TrainUpdateMetricFact.minimum_behavior_model_step)
  return _internal_minimum_behavior_model_step();
}
inline void TrainUpdateMetricFact::_internal_set_minimum_behavior_model_step(uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.minimum_behavior_model_step_ = value;
}
inline void TrainUpdateMetricFact::set_minimum_behavior_model_step(uint64_t value) {
  _internal_set_minimum_behavior_model_step(value);
  // @@protoc_insertion_point(field_set:rl.training.metrics.v1.TrainUpdateMetricFact.minimum_behavior_model_step)
}

// optional uint64 maximum_behavior_model_step = 9;
inline bool TrainUpdateMetricFact::_internal_has_maximum_behavior_model_step() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool TrainUpdateMetricFact::has_maximum_behavior_model_step() const {
  return _internal_has_maximum_behavior_model_step();
}
inline void TrainUpdateMetricFact::clear_maximum_behavior_model_step() {
  _impl_.maximum_behavior_model_step_ = uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline uint64_t TrainUpdateMetricFact::_internal_maximum_behavior_model_step() const {
  return _impl_.maximum_behavior_model_step_;
}
inline uint64_t TrainUpdateMetricFact::maximum_behavior_model_step() const {
  // @@protoc_insertion_point(field_get:rl.training.metrics.v1.TrainUpdateMetricFact.maximum_behavior_model_step)
  return _internal_maximum_behavior_model_step();
}
inline void TrainUpdateMetricFact::_internal_set_maximum_behavior_model_step(uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.maximum_behavior_model_step_ = value;
}
inline void TrainUpdateMetricFact::set_maximum_behavior_model_step(uint64_t value) {
  _internal_set_maximum_behavior_model_step(value);
  // @@protoc_insertion_point(field_set:rl.training.metrics.v1.TrainUpdateMetricFact.maximum_behavior_model_step)
}

// repeated .rl.training.v1.RawMetricSumCount ppo_statistics = 10;
inline int TrainUpdateMetricFact::_internal_ppo_statistics_size() const {
  return _impl_.ppo_statistics_.size();
}
inline int TrainUpdateMetricFact::ppo_statistics_size() const {
  return _internal_ppo_statistics_size();
}
inline ::rl::training::v1::RawMetricSumCount* TrainUpdateMetricFact::mutable_ppo_statistics(int index) {
  // @@protoc_insertion_point(field_mutable:rl.training.metrics.v1.TrainUpdateMetricFact.ppo_statistics)
  return _impl_.ppo_statistics_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rl::training::v1::RawMetricSumCount >*
TrainUpdateMetricFact::mutable_ppo_statistics() {
  // @@protoc_insertion_point(field_mutable_list:rl.training.metrics.v1.TrainUpdateMetricFact.ppo_statistics)
  return &_impl_.ppo_statistics_;
}
inline const ::rl::training::v1::RawMetricSumCount& TrainUpdateMetricFact::_internal_ppo_statistics(int index) const {
  return _impl_.ppo_statistics_.Get(index);
}
inline const ::rl::training::v1::RawMetricSumCount& TrainUpdateMetricFact::ppo_statistics(int index) const {
  // @@protoc_insertion_point(field_get:rl.training.metrics.v1.TrainUpdateMetricFact.ppo_statistics)
  return _internal_ppo_statistics(index);
}
inline ::rl::training::v1::RawMetricSumCount* TrainUpdateMetricFact::_internal_add_ppo_statistics() {
  return _impl_.ppo_statistics_.Add();
}
inline ::rl::training::v1::RawMetricSumCount* TrainUpdateMetricFact::add_ppo_statistics() {
  ::rl::training::v1::RawMetricSumCount* _add = _internal_add_ppo_statistics();
  // @@protoc_insertion_point(field_add:rl.training.metrics.v1.TrainUpdateMetricFact.ppo_statistics)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rl::training::v1::RawMetricSumCount >&
TrainUpdateMetricFact::ppo_statistics() const {
  // @@protoc_insertion_point(field_list:rl.training.metrics.v1.TrainUpdateMetricFact.ppo_statistics)
  return _impl_.ppo_statistics_;
}

// string behavior_model_lineage_id = 11;
inline void TrainUpdateMetricFact::clear_behavior_model_lineage_id() {
  _impl_.behavior_model_lineage_id_.ClearToEmpty();
}
inline const std::string& TrainUpdateMetricFact::behavior_model_lineage_id() const {
  // @@protoc_insertion_point(field_get:rl.training.metrics.v1.TrainUpdateMetricFact.behavior_model_lineage_id)
  return _internal_behavior_model_lineage_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TrainUpdateMetricFact::set_behavior_model_lineage_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.behavior_model_lineage_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:rl.training.metrics.v1.TrainUpdateMetricFact.behavior_model_lineage_id)
}
inline std::string* TrainUpdateMetricFact::mutable_behavior_model_lineage_id() {
  std::string* _s = _internal_mutable_behavior_model_lineage_id();
  // @@protoc_insertion_point(field_mutable:rl.training.metrics.v1.TrainUpdateMetricFact.behavior_model_lineage_id)
  return _s;
}
inline const std::string& TrainUpdateMetricFact::_internal_behavior_model_lineage_id() const {
  return _impl_.behavior_model_lineage_id_.Get();
}
inline void TrainUpdateMetricFact::_internal_set_behavior_model_lineage_id(const std::string& value) {
  
  _impl_.behavior_model_lineage_id_.Set(value, GetArenaForAllocation());
}
inline std::string* TrainUpdateMetricFact::_internal_mutable_behavior_model_lineage_id() {
  
  return _impl_.behavior_model_lineage_id_.Mutable(GetArenaForAllocation());
}
inline std::string* TrainUpdateMetricFact::release_behavior_model_lineage_id() {
  // @@protoc_insertion_point(field_release:rl.training.metrics.v1.TrainUpdateMetricFact.behavior_model_lineage_id)
  return _impl_.behavior_model_lineage_id_.Release();
}
inline void TrainUpdateMetricFact::set_allocated_behavior_model_lineage_id(std::string* behavior_model_lineage_id) {
  if (behavior_model_lineage_id != nullptr) {
    
  } else {
    
  }
  _impl_.behavior_model_lineage_id_.SetAllocated(behavior_model_lineage_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.behavior_model_lineage_id_.IsDefault()) {
    _impl_.behavior_model_lineage_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:rl.training.metrics.v1.TrainUpdateMetricFact.behavior_model_lineage_id)
}

// int64 requested_train_batch_size = 12;
inline void TrainUpdateMetricFact::clear_requested_train_batch_size() {
  _impl_.requested_train_batch_size_ = int64_t{0};
}
inline int64_t TrainUpdateMetricFact::_internal_requested_train_batch_size() const {
  return _impl_.requested_train_batch_size_;
}
inline int64_t TrainUpdateMetricFact::requested_train_batch_size() const {
  // @@protoc_insertion_point(field_get:rl.training.metrics.v1.TrainUpdateMetricFact.requested_train_batch_size)
  return _internal_requested_train_batch_size();
}
inline void TrainUpdateMetricFact::_internal_set_requested_train_batch_size(int64_t value) {
  
  _impl_.requested_train_batch_size_ = value;
}
inline void TrainUpdateMetricFact::set_requested_train_batch_size(int64_t value) {
  _internal_set_requested_train_batch_size(value);
  // @@protoc_insertion_point(field_set:rl.training.metrics.v1.TrainUpdateMetricFact.requested_train_batch_size)
}

// int64 pool_draw_slot_count = 13;
inline void TrainUpdateMetricFact::clear_pool_draw_slot_count() {
  _impl_.pool_draw_slot_count_ = int64_t{0};
}
inline int64_t TrainUpdateMetricFact::_internal_pool_draw_slot_count() const {
  return _impl_.pool_draw_slot_count_;
}
inline int64_t TrainUpdateMetricFact::pool_draw_slot_count() const {
  // @@protoc_insertion_point(field_get:rl.training.metrics.v1.TrainUpdateMetricFact.pool_draw_slot_count)
  return _internal_pool_draw_slot_count();
}
inline void TrainUpdateMetricFact::_internal_set_pool_draw_slot_count(int64_t value) {
  
  _impl_.pool_draw_slot_count_ = value;
}
inline void TrainUpdateMetricFact::set_pool_draw_slot_count(int64_t value) {
  _internal_set_pool_draw_slot_count(value);
  // @@protoc_insertion_point(field_set:rl.training.metrics.v1.TrainUpdateMetricFact.pool_draw_slot_count)
}

// int64 unique_item_count = 14;
inline void TrainUpdateMetricFact::clear_unique_item_count() {
  _impl_.unique_item_count_ = int64_t{0};
}
inline int64_t TrainUpdateMetricFact::_internal_unique_item_count() const {
  return _impl_.unique_item_count_;
}
inline int64_t TrainUpdateMetricFact::unique_item_count() const {
  // @@protoc_insertion_point(field_get:rl.training.metrics.v1.TrainUpdateMetricFact.unique_item_count)
  return _internal_unique_item_count();
}
inline void TrainUpdateMetricFact::_internal_set_unique_item_count(int64_t value) {
  
  _impl_.unique_item_count_ = value;
}
inline void TrainUpdateMetricFact::set_unique_item_count(int64_t value) {
  _internal_set_unique_item_count(value);
  // @@protoc_insertion_point(field_set:rl.training.metrics.v1.TrainUpdateMetricFact.unique_item_count)
}

// int64 duplicate_item_slot_count = 15;
inline void TrainUpdateMetricFact::clear_duplicate_item_slot_count() {
  _impl_.duplicate_item_slot_count_ = int64_t{0};
}
inline int64_t TrainUpdateMetricFact::_internal_duplicate_item_slot_count() const {
  return _impl_.duplicate_item_slot_count_;
}
inline int64_t TrainUpdateMetricFact::duplicate_item_slot_count() const {
  // @@protoc_insertion_point(field_get:rl.training.metrics.v1.TrainUpdateMetricFact.duplicate_item_slot_count)
  return _internal_duplicate_item_slot_count();
}
inline void TrainUpdateMetricFact::_internal_set_duplicate_item_slot_count(int64_t value) {
  
  _impl_.duplicate_item_slot_count_ = value;
}
inline void TrainUpdateMetricFact::set_duplicate_item_slot_count(int64_t value) {
  _internal_set_duplicate_item_slot_count(value);
  // @@protoc_insertion_point(field_set:rl.training.metrics.v1.TrainUpdateMetricFact.duplicate_item_slot_count)
}

// int64 sample_evaluation_count = 16;
inline void TrainUpdateMetricFact::clear_sample_evaluation_count() {
  _impl_.sample_evaluation_count_ = int64_t{0};
}
inline int64_t TrainUpdateMetricFact::_internal_sample_evaluation_count() const {
  return _impl_.sample_evaluation_count_;
}
inline int64_t TrainUpdateMetricFact::sample_evaluation_count() const {
  // @@protoc_insertion_point(field_get:rl.training.metrics.v1.TrainUpdateMetricFact.sample_evaluation_count)
  return _internal_sample_evaluation_count();
}
inline void TrainUpdateMetricFact::_internal_set_sample_evaluation_count(int64_t value) {
  
  _impl_.sample_evaluation_count_ = value;
}
inline void TrainUpdateMetricFact::set_sample_evaluation_count(int64_t value) {
  _internal_set_sample_evaluation_count(value);
  // @@protoc_insertion_point(field_set:rl.training.metrics.v1.TrainUpdateMetricFact.sample_evaluation_count)
}

// int64 optimizer_step_count = 17;
inline void TrainUpdateMetricFact::clear_optimizer_step_count() {
  _impl_.optimizer_step_count_ = int64_t{0};
}
inline int64_t TrainUpdateMetricFact::_internal_optimizer_step_count() const {
  return _impl_.optimizer_step_count_;
}
inline int64_t TrainUpdateMetricFact::optimizer_step_count() const {
  // @@protoc_insertion_point(field_get:rl.training.metrics.v1.TrainUpdateMetricFact.optimizer_step_count)
  return _internal_optimizer_step_count();
}
inline void TrainUpdateMetricFact::_internal_set_optimizer_step_count(int64_t value) {
  
  _impl_.optimizer_step_count_ = value;
}
inline void TrainUpdateMetricFact::set_optimizer_step_count(int64_t value) {
  _internal_set_optimizer_step_count(value);
  // @@protoc_insertion_point(field_set:rl.training.metrics.v1.TrainUpdateMetricFact.optimizer_step_count)
}

// .rl.common.v1.ContentDigest rollout_estimator_profile_digest = 18;
inline bool TrainUpdateMetricFact::_internal_has_rollout_estimator_profile_digest() const {
  return this != internal_default_instance() && _impl_.rollout_estimator_profile_digest_ != nullptr;
}
inline bool TrainUpdateMetricFact::has_rollout_estimator_profile_digest() const {
  return _internal_has_rollout_estimator_profile_digest();
}
inline const ::rl::common::v1::ContentDigest& TrainUpdateMetricFact::_internal_rollout_estimator_profile_digest() const {
  const ::rl::common::v1::ContentDigest* p = _impl_.rollout_estimator_profile_digest_;
  return p != nullptr ? *p : reinterpret_cast<const ::rl::common::v1::ContentDigest&>(
      ::rl::common::v1::_ContentDigest_default_instance_);
}
inline const ::rl::common::v1::ContentDigest& TrainUpdateMetricFact::rollout_estimator_profile_digest() const {
  // @@protoc_insertion_point(field_get:rl.training.metrics.v1.TrainUpdateMetricFact.rollout_estimator_profile_digest)
  return _internal_rollout_estimator_profile_digest();
}
inline void TrainUpdateMetricFact::unsafe_arena_set_allocated_rollout_estimator_profile_digest(
    ::rl::common::v1::ContentDigest* rollout_estimator_profile_digest) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.rollout_estimator_profile_digest_);
  }
  _impl_.rollout_estimator_profile_digest_ = rollout_estimator_profile_digest;
  if (rollout_estimator_profile_digest) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:rl.training.metrics.v1.TrainUpdateMetricFact.rollout_estimator_profile_digest)
}
inline ::rl::common::v1::ContentDigest* TrainUpdateMetricFact::release_rollout_estimator_profile_digest() {
  
  ::rl::common::v1::ContentDigest* temp = _impl_.rollout_estimator_profile_digest_;
  _impl_.rollout_estimator_profile_digest_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::rl::common::v1::ContentDigest* TrainUpdateMetricFact::unsafe_arena_release_rollout_estimator_profile_digest() {
  // @@protoc_insertion_point(field_release:rl.training.metrics.v1.TrainUpdateMetricFact.rollout_estimator_profile_digest)
  
  ::rl::common::v1::ContentDigest* temp = _impl_.rollout_estimator_profile_digest_;
  _impl_.rollout_estimator_profile_digest_ = nullptr;
  return temp;
}
inline ::rl::common::v1::ContentDigest* TrainUpdateMetricFact::_internal_mutable_rollout_estimator_profile_digest() {
  
  if (_impl_.rollout_estimator_profile_digest_ == nullptr) {
    auto* p = CreateMaybeMessage<::rl::common::v1::ContentDigest>(GetArenaForAllocation());
    _impl_.rollout_estimator_profile_digest_ = p;
  }
  return _impl_.rollout_estimator_profile_digest_;
}
inline ::rl::common::v1::ContentDigest* TrainUpdateMetricFact::mutable_rollout_estimator_profile_digest() {
  ::rl::common::v1::ContentDigest* _msg = _internal_mutable_rollout_estimator_profile_digest();
  // @@protoc_insertion_point(field_mutable:rl.training.metrics.v1.TrainUpdateMetricFact.rollout_estimator_profile_digest)
  return _msg;
}
inline void TrainUpdateMetricFact::set_allocated_rollout_estimator_profile_digest(::rl::common::v1::ContentDigest* rollout_estimator_profile_digest) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.rollout_estimator_profile_digest_);
  }
  if (rollout_estimator_profile_digest) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(rollout_estimator_profile_digest));
    if (message_arena != submessage_arena) {
      rollout_estimator_profile_digest = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, rollout_estimator_profile_digest, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.rollout_estimator_profile_digest_ = rollout_estimator_profile_digest;
  // @@protoc_insertion_point(field_set_allocated:rl.training.metrics.v1.TrainUpdateMetricFact.rollout_estimator_profile_digest)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace metrics
}  // namespace training
}  // namespace rl

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_training_5fmetrics_2eproto
